### ISSUE TITLE
Multiple issues with left (green) edge of clips

### ISSUE THREAD

**Issue by Efenstor** [mltframework/shotcut#137] opened 2015-11-06 19:15 UTC
1. Put two clips into the timeline. Drag the left (green) edge of the second one left - no transition is obviously created. Now play the timeline - looks like the clip remains in the old place.
2. Put two clips into the timeline. Drag the second one left 5 seconds left - transition is created. Drag the left (green) edge of the second clip 5 seconds right. Now drag the transition right for half its length: two transitions are created. Try to delete the right one, then the left one - CRASH.

And one more thing, although I'm not sure whether it's a bug or a feature: put two clips into the timeline, drag the second one left - transition is created, now move the same clip right - the transition remains in place, including portion of the clip. Is this an intended behavior?

**Comment by Efenstor** [comment] 2015-12-02 14:23
Still not fixed in 15.12.01.

**Comment by ddennedy** [comment] 2015-12-02 16:20
Make separate issues, please, and indicate what your OS.

For now, commenting on only the first one, I have not been able to reproduce it, or it is by design. Maybe it needs a better explanation. If you have clips with a gap between them, then dragging the in point left green edge is suppose to leave the clip in its place. It increases the length by adjusting the clip's in point.

**Comment by Efenstor** [comment] 2015-12-03 11:12
Thanks for responding! As it seems to me, those are basically the same issue, that's why only one ticket. My OS is Debian Jessie 64 bit. I don't add any gap between the clips, I just drag the left edge of the second clip left and it moves over the first one, while logically it either shouldn't or should create a transition. If I zoom out then I see that the clip actually didn't move at all.

**Comment by ddennedy** [comment] 2015-12-03 16:17
I understand it now and reproduced the problem.
Regarding "one more thing" there are some things around adjusting and editing transitions and its neighbors that are simply not implemented yet. I have been leaving some work like that open to give to new volunteers.

**Comment by Efenstor** [comment] 2015-12-03 17:57
Thanks! Even in its current form Shotcut is the best open-source video editor for Linux out there!

**Comment by ddennedy** [comment] 2015-12-04 04:47
This is fixed in git commit 20feb1a. It was a regression I introduced in v15.11 while trying to make a minor improvement.

**Closed by ddennedy** 2015-12-04 04:47 UTC
Labels: reproduced-by-dev, resolved
