### ISSUE TITLE
Segmentation Fault on using Timeline Functionality

### ISSUE THREAD

**Issue by JarredAllen** [mltframework/shotcut#1257] opened 2022-05-02 00:01 UTC
I'm using Ubuntu 20.04, and I have the version of shotcut which comes by default via apt (Shotcut 20.02.21).

Whenever I attempt to use the timeline feature, I get a segmentation fault. I can't find any log files (though if they may be somewhere I couldn't find), and the debugging information printed to terminal has a [DEBUG] level before the crash. Here's the debug info:
```
[AVIOContext @ 0x7f48c4058980] Statistics: 65536 bytes read, 0 seeks
[AVIOContext @ 0x7f48c4098380] Statistics: 65536 bytes read, 0 seeks
[AVIOContext @ 0x7f48c41026c0] Statistics: 65536 bytes read, 0 seeks
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f48c4384e00] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]
[h264 @ 0x7f48c43cb340] Reinit context to 3840x2064, pix_fmt: yuv420p
[h264 @ 0x7f483800c880] Reinit context to 3840x2064, pix_fmt: yuv420p
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f48a00bd700] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]
[h264 @ 0x7f48a0f38800] Reinit context to 3840x2064, pix_fmt: yuv420p
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f483810e9c0] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]
[h264 @ 0x7f483a487800] Reinit context to 3840x2064, pix_fmt: yuv420p
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f486c0b50c0] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]
[h264 @ 0x7f486c057a80] Reinit context to 3840x2064, pix_fmt: yuv420p
[h264 @ 0x7f48c4102000] Reinit context to 3840x2064, pix_fmt: yuv420p
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 0 total_channels 1 max_channels 1
[AVIOContext @ 0x7f483800e880] Statistics: 65536 bytes read, 0 seeks
[Debug  ] <MLT> [producer avformat-novalidate] "<video.mp4>" checking VFR: pkt.duration 1200
[Info   ] <MLT> [filter swresample] 1(mono) s16 32000Hz -> 2(stereo) s16 48000Hz
[h264 @ 0x7f483801ae00] Reinit context to 3840x2064, pix_fmt: yuv420p
[AVIOContext @ 0x7f48a0075000] Statistics: 65536 bytes read, 0 seeks
[Debug  ] <MLT> [producer avformat] "<video.mp4>" checking VFR: pkt.duration 1200
[h264 @ 0x7f48a0074180] Reinit context to 3840x2064, pix_fmt: yuv420p
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 0 total_channels 1 max_channels 1
[AVIOContext @ 0x7f486c05ebc0] Statistics: 65536 bytes read, 0 seeks
[AVIOContext @ 0x7f486c0b6400] Statistics: 65536 bytes read, 0 seeks
[AVIOContext @ 0x7f486c05da80] Statistics: 65536 bytes read, 0 seeks
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f486c05cdc0] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]
[h264 @ 0x7f486c02ef40] Reinit context to 3840x2064, pix_fmt: yuv420p
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f48c4056e40] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]
[h264 @ 0x7f48c40b1f80] Reinit context to 3840x2064, pix_fmt: yuv420p
[h264 @ 0x7f486c057a80] Reinit context to 3840x2064, pix_fmt: yuv420p
[AVIOContext @ 0x7f48c4058980] Statistics: 65536 bytes read, 0 seeks
[Debug  ] <MLT> [producer avformat] "<video.mp4>" checking VFR: pkt.duration 1200
[h264 @ 0x7f48c4001100] Reinit context to 3840x2064, pix_fmt: yuv420p
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f486c019200] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]
[h264 @ 0x7f486c08c700] Reinit context to 3840x2064, pix_fmt: yuv420p
[AVIOContext @ 0x7f486c05ebc0] Statistics: 65536 bytes read, 0 seeks
[Debug  ] <MLT> [producer avformat] "<video.mp4>" checking VFR: pkt.duration 1200
[h264 @ 0x7f486c2976c0] Reinit context to 3840x2064, pix_fmt: yuv420p
[Debug  ] <Timeline::OverwriteCommand::redo> trackIndex 0 position 0 
Segmentation fault (core dumped)
```

When run in GDB: here is the backtrace at the segementation fault:
```
Thread 1 "shotcut" received signal SIGSEGV, Segmentation fault.                                                                                                               
0x00007ffff7f5478f in mlt_service_connect_producer () from /usr/lib/x86_64-linux-gnu/libmlt.so.6                                                                              
(gdb) bt                                                                                                                                                                      
#0  0x00007ffff7f5478f in mlt_service_connect_producer () at /usr/lib/x86_64-linux-gnu/libmlt.so.6                                                                            
#1  0x00007ffff7f5e3bd in mlt_transition_connect () at /usr/lib/x86_64-linux-gnu/libmlt.so.6                                      
#2  0x00007ffff7f5ecfa in mlt_field_plant_transition () at /usr/lib/x86_64-linux-gnu/libmlt.so.6                                                  
#3  0x00005555556f8ea4 in  ()                                                                                                                                                 
#4  0x00005555556f7229 in  ()                                                                                                                                                 
#5  0x00005555556f90d4 in  ()                                                                                                                                                 
#6  0x0000555555716db1 in  ()                                                                                                                                                 
#7  0x00007ffff7ce2d8a in QUndoStack::push(QUndoCommand*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5                                                                  
#8  0x0000555555794628 in  ()                                                                                                                                                 
#9  0x0000555555794b93 in  ()                                                                                                                                                 
#10 0x00007ffff69c8f65 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#11 0x00007ffff68b816c in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#12 0x00007ffff68ba1b9 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#13 0x00007ffff68bafde in QV4::QObjectMethod::callInternal(QV4::Value const*, QV4::Value const*, int) const () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                    
#14 0x00007ffff68d8401 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#15 0x00007ffff68da2c7 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#16 0x00007ffff686764f in QV4::Function::call(QV4::Value const*, QV4::Value const*, int, QV4::ExecutionContext const*) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5         
#17 0x00007ffff69f1587 in QQmlJavaScriptExpression::evaluate(QV4::CallData*, bool*) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                   
#18 0x00007ffff699038c in QQmlBoundSignalExpression::evaluate(void**) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5              
#19 0x00007ffff6991528 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#20 0x00007ffff69d474d in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                              
#21 0x00007ffff6970715 in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                            
#22 0x00007ffff6204aa3 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5       
#23 0x00007fffb8f23d30 in  () at /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/libqtquickcontrolsplugin.so                                   
#24 0x00007ffff62051d0 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5   
#25 0x00007fffb8f217c3 in  () at /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/libqtquickcontrolsplugin.so                               
#26 0x00007fffb8eff668 in  () at /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/libqtquickcontrolsplugin.so                                                     [21/97162]
#27 0x00007fffb8f23c6a in  () at /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/libqtquickcontrolsplugin.so                                                               
#28 0x00007fffb8f247e3 in  () at /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/libqtquickcontrolsplugin.so                                                               
#29 0x00007ffff69c8f65 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#30 0x00007ffff68b816c in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5              
#31 0x00007ffff68ba1b9 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#32 0x00007ffff68bafde in QV4::QObjectMethod::callInternal(QV4::Value const*, QV4::Value const*, int) const () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                    
#33 0x00007ffff68d8401 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#34 0x00007ffff68da2c7 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#35 0x00007ffff68681a0 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#36 0x00007ffff68d8401 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#37 0x00007ffff68da2c7 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#38 0x00007ffff686764f in QV4::Function::call(QV4::Value const*, QV4::Value const*, int, QV4::ExecutionContext const*) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5         
#39 0x00007ffff69f1587 in QQmlJavaScriptExpression::evaluate(QV4::CallData*, bool*) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                            
#40 0x00007ffff699038c in QQmlBoundSignalExpression::evaluate(void**) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                          
#41 0x00007ffff6991528 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#42 0x00007ffff69d474d in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5  
#43 0x00007ffff6970715 in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#44 0x00007ffff6204aa3 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5                                                   
#45 0x00007ffff696bccd in QQmlVMEMetaObject::metaCall(QObject*, QMetaObject::Call, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                
#46 0x00007ffff69c8f65 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#47 0x00007ffff68b7dad in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#48 0x00007ffff68ba1e4 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#49 0x00007ffff68bafde in QV4::QObjectMethod::callInternal(QV4::Value const*, QV4::Value const*, int) const () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                    
#50 0x00007ffff68d8401 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#51 0x00007ffff68da2c7 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#52 0x00007ffff686764f in QV4::Function::call(QV4::Value const*, QV4::Value const*, int, QV4::ExecutionContext const*) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5         
#53 0x00007ffff69f1587 in QQmlJavaScriptExpression::evaluate(QV4::CallData*, bool*) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                            
#54 0x00007ffff699038c in QQmlBoundSignalExpression::evaluate(void**) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                          
#55 0x00007ffff6991528 in  () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                                                                                     
#56 0x00007ffff69d474d in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                                              
#57 0x00007ffff6970715 in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5                            
#58 0x00007ffff6204aa3 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5                                          
#59 0x00007ffff75bd626 in QQuickMouseArea::released(QQuickMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5           
#60 0x00007ffff75bef75 in QQuickMouseArea::setPressed(Qt::MouseButton, bool, Qt::MouseEventSource) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5                           
#61 0x00007ffff75c0103 in QQuickMouseArea::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5                                                   
#62 0x00007ffff7521ad8 in QQuickItem::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5                                                                         
#63 0x00007ffff794ca66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#64 0x00007ffff79560f0 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5                              
#65 0x00007ffff61d980a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#66 0x00007ffff753caed in QQuickWindowPrivate::deliverMouseEvent(QQuickPointerMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5   
#67 0x00007ffff753df71 in QQuickWindowPrivate::deliverPointerEvent(QQuickPointerEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#68 0x00007ffff753ec29 in QQuickWindowPrivate::handleMouseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#69 0x00007fffb8f00f8b in  () at /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/libqtquickcontrolsplugin.so
#70 0x00007ffff6d369ad in QWindow::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#71 0x00007ffff7540159 in QQuickWindow::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#72 0x00007fffb8f010b6 in  () at /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/libqtquickcontrolsplugin.so
#73 0x00007ffff794ca66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#74 0x00007ffff79560f0 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#75 0x00007ffff61d980a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#76 0x00007ffff6d2b7d3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#77 0x00007ffff6d2d10b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#78 0x00007ffff6d0735b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#79 0x00007fffee77232e in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#80 0x00007ffff218417d in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#81 0x00007ffff2184400 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#82 0x00007ffff21844a3 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#83 0x00007ffff6231435 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#84 0x00007ffff61d83ab in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#85 0x00007ffff61e0116 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#86 0x00005555555e18f1 in main ()
```
I hope this information is good. Please let me know if there's anything else or if there's a known work-around for this issue.

Thank you.

**Comment by ddennedy** [comment] 2022-05-02 00:20
Duplicate of #1180 and #1142

**Closed by ddennedy** 2022-05-02 00:20 UTC
Labels: duplicate
