### ISSUE TITLE
Drag & Drop import/opening errors

### ISSUE THREAD

**Issue by snakehill** [mltframework/shotcut#374] opened 2017-01-14 12:36 UTC
When dragging and dropping a file from my C:/ drive into Shotcut it loads fine, but files coming from any other drive, like D:/ (which I generally store my video files on, given I use my C:/ only for the OS and applications) or G:/ or X:/ give the following error:

`Failed to open /D:/Video.mp4`

I suppose the problem is with it automatically adding the slash in front of the file location. It's not an issue with the language setting either as it doesn't work in any language. Also using 'Open File' load the files just fine. Dragging and dropping is much faster and more convenient though.

Also, I can't find any way to disable files from autoplaying upon importing/opening them (whether via dragging and dropping or via 'Open File'). If I were to use Shotcut as a media player, I'd want videos to play by themselves, but for editing purposes it's extremely counterproductive. Not just because I have to click pause each time, but also because you can't complete mute the sound in advance (in particular when editing silently to not bother anyone, whether in real life or through a livestream).

[Windows 10 Pro; Shotcut 17.01.02]

**Comment by ochilan** [comment] 2017-01-14 15:26
There's a recent commit https://github.com/mltframework/shotcut/commit/ad26978f5b62cbb6c2d4737496cf7f073b843fcd fixing exactly this issue, I suppose it will be in the next release. Haven't tested the fix myself though as I usually work under Linux.

**Comment by ddennedy** [comment] 2017-01-14 18:43
Duplicate of #369

**Closed by ddennedy** 2017-01-14 18:43 UTC
Labels: duplicate
