### ISSUE TITLE
Application will crash randomly when attempting to do things

### ISSUE THREAD

**Issue by kierandoc** [mltframework/shotcut#1594] opened 2024-10-11 00:34 UTC
Running on Arch Linux 6.10.10, shotcut version 24.09.13 

When i try to do simple things like add size, position, rotate filters or move objects in my timeline slightly, the application will flat out crash. It can be something that simple that i've done plenty of times before on the exact same file, and it crashes. Never done this on other OSes running this Flatpak, so i'm unsure if it's an issue with my os or the application itself. I would normally have chocked it up to something like an issue with me using too much RAM, or overloading the app, but i have 32GB of RAM and i have done much more demanding things on this exact application version, with this OS, having no issue at all

**Comment by ddennedy** [comment] 2024-10-11 01:06
Are you using the flatpak?

When you say “other OSes” is that on the same machine?

**Comment by kierandoc** [comment] 2024-10-11 15:01
Yes to both. I'm using the Flatpak, and when running on other operating systems (Windows 11 and Linux Mint 21.3) It has been on the same machine.

**Comment by ddennedy** [comment] 2024-10-11 21:35
You could be affected by this crash b2da86 I just fixed. Even though the description is rather specific, the problem was in a function called frequently for many operations; however, those are mostly involving timeline changes, not necessarily matching your description. Your description sounds a little it like more general like an OpenGL compatibility issue. Ultimately, though, this bug report is not very actionable or measurable for being "random."

**Comment by ddennedy** [comment] 2024-11-19 19:38
Closing as duplicate of #1499

**Closed by ddennedy** 2024-11-19 19:38 UTC
Labels: duplicate, pending
