### ISSUE TITLE
Crop as track filter not applied during transition

### ISSUE THREAD

**Issue by SteveLedger** [mltframework/shotcut#169] opened 2015-12-23 21:52 UTC
As per title.
Versions 1510 or 1512

Windows 7 Pro 64bit / 16Gb RAM /  Radeon HD 5700 series

**Comment by ddennedy** [comment] 2015-12-23 22:03
Works for me. Provide exact steps to reproduce. Indicate if you have GPU processing on or not.
Pending means I will close this if I do not hear back within a couple weeks and still do reproduce it.

**Comment by SteveLedger** [comment] 2015-12-23 22:07
GPU processing 'off'
Steps:
Assemble clips on timeline.
Overlap clips to produce default fade transition.
Apply crop from filters tab.
Crop is applied to clips but not applied during fade transition in review window or when encoded to file.

**Comment by ddennedy** [comment] 2015-12-23 22:10
Still not able to reproduce. You have to select the clip to attach the filter - not the transition.

**Comment by SteveLedger** [comment] 2015-12-23 22:19
Not selecting transition, Dan. I am selecting the track so that all filters are applied equally to all clips and stills [jpegs].

**Comment by SteveLedger** [comment] 2015-12-23 22:19
Why close this?  It's not resolved for me.

**Comment by ddennedy** [comment] 2015-12-23 22:20
OK, I can confirm that is a bug. You did not specify it in your steps. I doubt this will ever be fixed because Crop is not intended to be used on tracks - only clips. I might make a change to disallow using it on track.

**Comment by ddennedy** [comment] 2015-12-23 22:22
"Why close?" If I cannot reproduce it, I will close it.

**Comment by SteveLedger** [comment] 2015-12-23 22:27
"Crop is not intended to be used on tracks - only clips"
I see, though in practice it's much easier and a heck of a lot faster to apply a custom crop to the track than to individual clips.

Thanks
Have a great Xmas.

**Comment by ddennedy** [comment] 2015-12-23 22:32
OK, I am curious about the use case for this. I understand the desire to have track filters in general, but I mean Crop especially when it is also not intended to be used for compositing either. The current Crop filter is more for removing rough edges and removing black borders due to aspect ratio differences. I intend to add a different kind of crop for compositing. Thanks.

**Comment by SteveLedger** [comment] 2015-12-23 22:37
I see.  I'm actually using the cropping filter to create 21:9 aspect from 16:9 footage.  
When there are dozens of clips on the track, cropping each one is a lot of mouse clicks!
I also find it very useful to apply my custom color grading presets to the track than individual clips.

Cheers

**Comment by ddennedy** [comment] 2015-12-23 22:41
OK, I see. You might find it faster to add the Crop filter to each clip before adding it to the timeline or playlist. Then each time you choose a shot to add or use Split, it will copy that filter. i agree it is not as convenient as track filter, but it beats adding it to each timeline clip after editing.
Merry Christmas!

**Comment by SteveLedger** [comment] 2015-12-23 22:43
I'll give it a try.
Thanks :)

**Closed** 2016-02-05 04:17 UTC
Labels: reproduced by dev
