### ISSUE TITLE
Shotcut, ffmpeg and Intel Quicksync on Linux

### ISSUE THREAD

**Issue by mattcollier** [mltframework/shotcut#636] opened 2018-09-25 17:31 UTC
Hello, I've found what appear to be some legit instructions for using Intel Quick Sync H.264 hardware acceleration here: https://gist.github.com/mattcollier/e3aeb092854c0d20bed0489f470d41a3

The part I'm mainly unsure about is how all these ffmpeg flags are surfaced in Shotcut.  First, there is reference to a `h264_vaapi` codec.  Is that something that will magically appear if I compile my ffmpeg as described?

WRT the other various command line flags described, do those go under the `other` tab in the export panel?

**Comment by ddennedy** [comment] 2018-09-25 18:03
Quick Sync is not available in the FFmpeg build we provide. This is not something you can simply enable with a command line option. Also, you can easily drop in a custom or system build of FFmpeg (unless you are using some distro package custom build that not provided by us). In any case, yes, other FFmpeg options can be specified in the Other tab using option=value syntax (not `-option value`), one per line. I just bought a MacBook that can support Quick Sync. So, I may get around to adding support for it to our builds soon.
Since this is not a bug and we do not track feature requests, I am closing it but feel free to reply.

**Closed by ddennedy** 2018-09-25 18:03 UTC

**Comment by ddennedy** [comment] 2018-09-25 18:05
If you want to compile FFmpeg yourself, give it a shot. We are using v4.0, and are build options are here:
https://github.com/mltframework/shotcut/blob/master/scripts/build-shotcut.sh#L600
You might be able to drop replacement libs into the Shotcut.app/lib dir.

**Comment by ddennedy** [comment] 2018-09-25 19:47
Take a look at this Encoding section:
https://trac.ffmpeg.org/wiki/Hardware/VAAPI#Encoding

MLT does not yet upload frames to the hardware surfaces. For some APIs this is not needed (NVENC). There is no way to tell MLT to use the hwupload to do that either. It needs to be coded in. Unfortunately, a simple rebuild of ffmpeg is not going to work.

**Comment by mattcollier** [comment] 2018-09-25 21:04
@ddennedy thanks for saving me the trouble of falling into that pit!  I'm not event sure what MLT is.

Would some intermediate format be a viable option?  What is the current state of DNxHD or Cineform exports from shotcut.  If I can get it out of Shotcut inexpensively, I could then render using hardware accelerated ffmpeg on the command line?
