### ISSUE TITLE
MULTICAMERA in ShotCut

### ISSUE THREAD

**Issue by isomiluizdasilva** [mltframework/shotcut#1465] opened 2023-08-16 23:41 UTC
Initially, I would like to congratulate you for the initiative and for the new resources implemented in the Shotcut application and I would like to know if Shotcut would have some kind of resource, like EDIT IN MULTICAMERA or some other way that allows me to see the videos in different timelines, such as example V1 and V2 simultaneously, so that you can check here the possibility of creating some mechanisms that enable and/or facilitate editing in the MULTICCAMERA format, based on what I researched, I could not find the resource in Shotcut (desktop version)
![ideia_shotcut](https://github.com/mltframework/shotcut/assets/61293748/a320a5ec-c907-4cb5-ad29-15496199e93a)

The idea would be to create something that adds two buttons, one above each image and this way, when the button is clicked, the function will add a cut at that point and if the selected video was on the line below, a cut would then be added to the video above and then from that point on, until the other button was clicked, the video above would have opacity 0, so the video below would be displayed and if it was the video above, then the cut would be added and then the video above would have opacity 100.

**Comment by bmatherly** [comment] 2023-08-17 01:41
The feature you are looking for does not exist today. It does appear on the [roadmap ](https://shotcut.org/roadmap/) as "multi-camera editing features". But there is no timeline for that.

Closing this issue because we only use this place to track confirmed bugs. Not questions or suggestions. Feel free to take your topic to the [Shotcut Forum](https://forum.shotcut.org/) where you can find other users and developers to discuss feature ideas.

For example, this related topic came up some years ago:
https://forum.shotcut.org/t/multicamera-edit-two-angles-with-help-of-size-and-position-filter/11758

**Closed by bmatherly** 2023-08-17 01:41 UTC
