### ISSUE TITLE
Dragging text window updates wrong textboxes

### ISSUE THREAD

**Issue by suBOTai3** [mltframework/shotcut#324] opened 2016-10-17 12:35 UTC
Hi guys.

Using Win 10 64bit.
Insert new video on a track
Insert new filter > Text
Dragging any of the window corners updates the wrong fields.. .see the image

Thanks for your great efforts
![wrong fields](https://cloud.githubusercontent.com/assets/5020751/19437727/eba5a292-9476-11e6-9582-e7b35c8fdff6.png)

**Comment by ddennedy** [comment] 2016-10-18 06:37
It is working as intended for me. "Position" reflects the origin, which is the top left corner. If you adjust the top right corner, it may change the second Position box (Y) and both size boxes depending on the adjustment you make. Maybe you expect origin to be the bottom left corner or the center? If you still think it is a problem, explain more or make a screencast video.

**Comment by driewiel** [comment] 2016-10-19 12:22
My bad. I did type it out wrong. 

The correct statement would be: It is not that the incorrect **textbox** is being updated, but rather that the **values** are incorrect. You can see from the screenshot that the value of 57600 is impossible.

 I can't seem to upload a video file, so I posted this link http://sendvid.com/7ve4wtu9

**Comment by ddennedy** [comment] 2016-10-19 17:58
sendvid.com is a very offensive service! I am going to have to do the web a favor and remove the link from your post. Sorry

I see the problem, but I do not experience it. I do not know why it is a problem for you. This will have to wait until someone experiencing the problem offers a fix, or until more people with the problem are able to provide more information that can help understand the cause.

**Comment by driewiel** [comment] 2016-10-19 19:49
Hey no problem. I went to watch the video afterwards and found the same
offensive problem. I will see if I can document it better with screenshots
for someone for later
Thanks for looking at this

**Comment by der-mondbaer** [comment] 2016-12-20 11:50
I experience a similar problem on OS X 10.9.5

For me, the problem only shows up after I save and reopen a document. Even though I don't know the exact syntax for the geometry property in the XML save file, I would assume the save file itself is fine as the values in there seem okay. E.g. a small textbox has the values `37.60%/49.44%:20.78%x11.67` for `geometry`.

When I open a document, the text in a textbox sometimes won't show up. When I then drag the textbox, it becomes visible, but the values in textfields on the left update to ridiculous values as shown in the screenshot above. In this situation I have no possibility to manually correct those wrong values as they influence each other. Nevertheless, when I save the document with those values the save file does not change.

I often get the message "A problem with your project has been detected..." when opening a project. When I compare the original file and the repaired one that gets created, the only difference i can find is that in the repaired one the comma is represented by the character "," instead of ".".
Example:
original: `<property name="geometry">37.66%/49.44%:20.73%x11.76%</property>`
repaired:`<property name="geometry">37,60%/49,44%:20,78%x11,67%</property>`

I hope that helps reproducing the problem.

**Comment by ddennedy** [comment] 2016-12-22 05:22
@der-mondbaer I fixed the incorrect decimal point checking on OS X:  "A problem with your project has been detected...."  That fix will be in the next release. However, I have not reproduced the problem with ridiculous values. From the sound of it, the filter UI is not initializing properly.

**Comment by NovA80** [comment] 2017-06-11 18:14
Shotcut version 17.06.01 on Win10 64bit.

I experience the same problem as the topic starter. If bounding rectangular of text filter is tried to be dragged, the position & size textboxes are set to some huge values and the rectangular flies out of screen. Moreover the manual setting of position & size values is also impossible, anything entered leads to resetting all fields to 0.

Note this issue is not about values saved in .mlt project file. When I load the file created on other machine (Linux one), the text filter appears correctly. But any attempt to change position & size broke it.

The problem is definitely concerned with Windows Language Settings, as described in https://github.com/mltframework/shotcut/issues/362#issuecomment-271682347 . In my case the Russian regional settings are used, where the default symbol for decimal point "," is changed to ".". When I reset regional settings to default values, the Shotcut text filter works as expected.

**Closed** 2018-02-26 23:03 UTC
Labels: pending
