### ISSUE TITLE
Application closes unexpectedly

### ISSUE THREAD

**Issue by dinhokusanagi** [mltframework/shotcut#1294] opened 2022-06-29 07:00 UTC
The problem occurs when I try to add a vide

https://user-images.githubusercontent.com/43162113/176372462-33641c42-b521-48eb-9b40-ccb29c43ab16.mp4

o

**Comment by CaelanTheCoder** [comment] 2022-07-01 16:11
I wonder if its because of you screen resolution

**Comment by dinhokusanagi** [comment] 2022-07-01 16:25
Lower the screen resolution and the same thing happened

https://user-images.githubusercontent.com/43162113/176933627-73138403-ede1-4ca8-9fba-2bec6cc85b1e.mp4

**Comment by ddennedy** [comment] 2022-07-01 16:29
Closing it as unable to reproduce and again not enough info - completely overlooked the bug template. You should use a build we provide.

**Closed by ddennedy** 2022-07-01 16:29 UTC
Labels: pending

**Comment by dinhokusanagi** [comment] 2022-07-01 16:36
This is a lack of interest on your part.
1 - I'm not a fortune teller to know what information I can provide, for that you have to say what you need.
2 - I'm using the flathub app, the flathub packaging is not done by you or you?

**Comment by ddennedy** [comment] 2022-07-01 16:47
Creating a bug shows this text that you did not read before deleting:

> This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).
> 
> If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS > 10.11.5; Shotcut 16.05.01`).

But you can also use common sense that should tell you: this program has many versions and is available for multiple operating systems not to mention there are hundreds of variations of Linux, and surely the developers verified they can open a video file so I need to provide some details. I am very busy and do not want to waste time asking for basic info that was already requested.

Yes I make the flatpak from flathub, and version 22.06.23 works for me on Ubuntu 20.04, but I have not tested drag-n-drop from the file manager recently. I will test that when I can. In the meantime, does it work if you use the menu File > Open or the Recent panel instead?

**Comment by dinhokusanagi** [comment] 2022-07-01 16:59
yes it works, i reproduced the terminal error, should something i already know. That question is closed. Thanks

**Comment by ddennedy** [comment] 2022-07-01 19:13
duplicate of #1218 and #1226
