### ISSUE TITLE
latest 24.09.13 release fails to build on 32bit (i686)

### ISSUE THREAD

**Issue by david-geiger** [mltframework/shotcut#1580] opened 2024-09-20 06:40 UTC
Hi,

On Mageia Cauldron latest 24.09.13 release fails to build on 32bit arch with the following build issue:

> /usr/bin/ld: src/CMakeFiles/shotcut.dir/dialogs/filedatedialog.cpp.o: in function `FileDateDialog::accept()':
/home/iurt/rpmbuild/BUILD/shotcut-24.09.13/src/dialogs/filedatedialog.cpp:81:(.text+0x4ce): undefined reference to `Mlt::Producer::set_creation_time(long long)'
/usr/bin/ld: src/CMakeFiles/shotcut.dir/mltcontroller.cpp.o: in function `Mlt::Controller::lockCreationTime(Mlt::Producer*) const':
/home/iurt/rpmbuild/BUILD/shotcut-24.09.13/src/mltcontroller.cpp:1040:(.text+0x35d5): undefined reference to `Mlt::Producer::set_creation_time(long long)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Attached full build log:
[build.i686.0.20240920054337.log](https://github.com/user-attachments/files/17070988/build.i686.0.20240920054337.log)

**Comment by bmatherly** [comment] 2024-09-20 12:29
Probably caused by your MLT build and related to this issue: https://github.com/mltframework/mlt/issues/1020

**Comment by chriscapisce** [comment] 2024-09-24 18:29
Thanks I will, i see now in their json.

https://formulae.brew.sh/api/cask/shotcut.json

**Comment by ddennedy** [comment] 2024-11-19 19:37
Fixed in MLT

**Closed by ddennedy** 2024-11-19 19:37 UTC
Labels: wontfix
