### ISSUE TITLE
Shotcut 22.10 Beta Crashes on Keyframes window toggle, clicking Keyframe icon in Rich Text, Apple M1

### ISSUE THREAD

**Issue by cruudesign** [mltframework/shotcut#1362] opened 2022-10-22 03:56 UTC
Dan, I have 22-10-BETA, getting 100% repeated crashes in one of my projects when trying to keyframe the text box.  Now any attempt to re-open Keyframes window crashes Shotcut.  I've repeated it over and over, restarted, and the same immediate crash is happening.  

The project is small, 5min, and I successfully added Rich Text to other clips.  Attempting to Keyframe window or toggle the icon in the Filter crashes it.  I re-opened, went to a different clip that has no filters, and attempting to reopen the Keyframes window crashes it.  Selecting a clip I'd previously used Keyframes in the Filter, then opening Keyframes crashes it.  Cmd-7 crashes it.  

New project with no clips, same.

I have quite a few successfully applied keyframes in the file.  Closing the Keyframes detached window seems like the trigger that started this problem.

Timeline opens fine, window can be moved around. Previously a problem in my old report.

Thanks for the dedication.  Clint

(aside, https://github.com/mltframework/shotcut has your website listed mid-page as your contact info still.)
Apple M1
Monterey 12.6

**Comment by ddennedy** [comment] 2022-10-22 04:50
duplicate of #1357

**Closed by ddennedy** 2022-10-22 04:50 UTC
Labels: duplicate
