### ISSUE TITLE
Assertion `!c->out.queue_len' failed.

### ISSUE THREAD

**Issue by CarlFK** [mltframework/shotcut#49] opened 2015-01-30 17:17 UTC
added a .dv and a .png to the time line. 
output.dv: DIF (DVCPRO) movie file (NTSC)
conk1.png: PNG image data, 1024 x 768, 8-bit/color RGB, non-interlaced

zoomed in on transition from .dv to png (no effect, just end/start),  hit play, when it hit the png, crash.

shotcut: ../../src/xcb_conn.c:186: write_vec: Assertion `!c->out.queue_len' failed.

re-ran, play, crash again.

Now trying to reproduce, doesn't crash.

**Comment by ddennedy** [comment] 2015-01-30 18:08
Unable to reproduce.

**Comment by CarlFK** [comment] 2015-01-30 21:09
I get that error intermittently. 
I run this:
carl@twist:~/bin$ Shotcut/Shotcut.app/shotcut ~/Videos/test1.mlt

app opens, files load, starts playing...
after a random amount of time (yep) it errors.  or not.  seems about 50/50.

tried 2 or 3 times with gdb, no crash.

**Comment by ddennedy** [comment] 2015-01-30 21:13
Next version does not autoplay multitrack and playlist .mlt files. That might affect this, but I will try to repro with this new info. Thanks

**Comment by CarlFK** [comment] 2015-01-30 21:16
I'll upload the 3 files

On Fri, Jan 30, 2015 at 3:13 PM, Dan Dennedy <notifications@github.com>
wrote:

> Next version does not autoplay multitrack and playlist .mlt files. That
> might affect this, but I will try to repro with this new info. Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mltframework/shotcut/issues/49#issuecomment-72271191>.
>



-- 
Carl K

**Comment by ddennedy** [comment] 2015-01-30 21:28
>
> I'll upload the 3 files
>
> please don't. I am not offering to give this the level of attention you
may be expecting.

**Comment by CarlFK** [comment] 2015-01-31 01:19
ok.

I just started a new project with new source files - did lots of work
(previewing scrubbing, cutting, added some video fade in/out) and as it was
playing, crash.

confirming same line:
shotcut: ../../src/xcb_conn.c:186: write_vec: Assertion `!c->out.queue_len'
failed.


On Fri, Jan 30, 2015 at 3:28 PM, Dan Dennedy <notifications@github.com>
wrote:

> >
> > I'll upload the 3 files
> >
> > please don't. I am not offering to give this the level of attention you
> may be expecting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mltframework/shotcut/issues/49#issuecomment-72273296>.
>



-- 
Carl K

**Comment by metellius** [comment] 2015-05-28 07:05
For the record, I have also had this crash a few times on 15.05.06

**Comment by ddennedy** [comment] 2015-06-13 21:39
This bug report linked below explains how the bug is related to Mesa and libxcb and fixed in libxcb v1.11 (some distro packages may have back-ported the fix to an earlier version). Lots of good links in that bug report to learn more.
https://github.com/glfw/glfw/issues/386

I use nvidia GL, which explains why I never saw this bug. Closing this as "not my bug."

**Closed by ddennedy** 2015-06-13 21:39 UTC
Labels: crash, Linux
