### ISSUE TITLE
Qt Creator: Project ERROR: Unknown module(s) in QT: webkitwidgets

### ISSUE THREAD

**Issue by uwe22** [mltframework/shotcut#249] opened 2016-05-31 09:51 UTC
Trying to build Shotcut with Qt Creator on OSX El Capitan 10.11.5

I wonder what is referenced and how can I find webkitwidgets
I installed webkit for QT5 via macports, do I need additional libraries?

Please help.
![screen shot 2016-05-31 at 18 50 20](https://cloud.githubusercontent.com/assets/11908297/15670466/96421a34-2760-11e6-9166-b4faeaaf12b5.jpg)

**Comment by metellius** [comment] 2016-05-31 11:50
Building outside build-shotcut.sh is not officially supported

**Comment by ddennedy** [comment] 2016-05-31 16:15
Shotcut requires Qt WebKit module, but that module is no longer provided with Qt 5.6 and onward. I do not know how you installed Qt, but you cannot install some things from Qt binaries and another module from MacPorts and expect them to work together. Complex software like this does not work that way. My suggestion is to download a Qt 5.5.1 SDK from Qt project and configure it in the build settings of Qt Creator.
Closing at this is not a bug.

**Closed by ddennedy** 2016-05-31 16:15 UTC

**Comment by askunix** [comment] 2019-07-25 12:49
有道理
