### ISSUE TITLE
Crash when adding a new track (Windows 10)

### ISSUE THREAD

**Issue by Alexander01998** [mltframework/shotcut#193] opened 2016-02-12 18:52 UTC
Every time I have existing tracks (video or audio) with one or more elements on them (videos, sounds or pictures), I cannot add a new track (video or audio) without causing Shotcut to crash.

Adding new tracks only works for me if all of the existing tracks are empty or no other tracks exist.

If you need any further details about this bug, feel free to ask me.

**Comment by ddennedy** [comment] 2016-02-12 18:54
Unable to reproduce using latest v16.02. What version of Shotcut are you using?

**Comment by ddennedy** [comment] 2016-02-12 19:13
Is GPU Processing enabled in Settings?
Try the different options under Settings > Display Method to see if it makes a difference.

**Comment by Alexander01998** [comment] 2016-02-13 10:58
Using v16.02 with GPU processing off.

**Comment by Alexander01998** [comment] 2016-02-13 11:00
Display Method was set to Automatic. I tried the other ones, but those didn't work for me either.

**Comment by Alexander01998** [comment] 2016-02-13 11:13
Does Shotcut save a settings file and/or debug log somewhere?

**Comment by ddennedy** [comment] 2016-02-13 17:17
This FAQ item tells about those things:
https://www.shotcut.org/bin/view/Shotcut/FrequentlyAskedQuestions#Where_are_the_log_presets_databa

The log is not very verbose and probably will not help much, but you can still provide it; it could reveal something. You could also export or take a screenshot of the registry settings.

Does this happen primarily with an existing project with which you are testing this? Or, can you provide steps from a clean start?

**Comment by Alexander01998** [comment] 2016-02-13 20:57
> The log is not very verbose and probably will not help much, but you can still provide it; it could reveal something. You could also export or take a screenshot of the registry settings.

OK, I will do that once I'm on my PC again.

> Does this happen primarily with an existing project with which you are testing this? Or, can you provide steps from a clean start?

Happened with all of my projects so far. Pretty sure I didn't change any of the settings, so it should basically be a clean start.

**Comment by datietou** [comment] 2016-02-17 03:28
I have faced similar problem too, 
1. when remove all tracks, and add track, add track, it crashed.
2.when remove all tracks, and add track, add track, then click the track header, crashed.

Not very often crash.

**Comment by Alexander01998** [comment] 2016-02-17 15:04
Right-clicking on the track header has sometimes caused crashes for me too.

**Comment by Alexander01998** [comment] 2016-02-19 14:09
OK, here's my log:
[shotcut-log.txt](https://github.com/mltframework/shotcut/files/138055/shotcut-log.txt)

**Comment by Alexander01998** [comment] 2016-03-01 19:19
Is there any way I can generate a stacktrace or something like that to help you fix this bug more quickly?

**Comment by ddennedy** [comment] 2016-03-02 06:19
@Alexander01998 You can run shotcut.exe with gdb and when it crashes enter "thread apply all bt" to generate a backtrace. However, I (or another developer) almost always must be able to reproduce it in order to confirm a particular change fixes it, and a backtrace rarely helps to show steps (and many other factors). The steps here are not exactly bad, but perhaps a screencast video can help.

**Comment by Alexander01998** [comment] 2016-03-02 15:13
OK, I will make a video when I get back on my other PC.

**Comment by Alexander01998** [comment] 2016-03-04 17:31
Getting it to crash on camera was surprisingly tough, but I did manage to capture this crash:


[crash.zip](https://github.com/mltframework/shotcut/files/159065/crash.zip)

**Comment by Alexander01998** [comment] 2016-03-12 09:33
Captured another crash. Hope this helps.

[crash.zip](https://github.com/mltframework/shotcut/files/170346/crash.zip)

**Comment by ddennedy** [comment] 2016-03-12 18:27
I reproduced the first crash.zip. It is not required to open any media. Simply add a track and continually right click on the track header and within 10 or so tries it should crash.

**Comment by ddennedy** [comment] 2016-03-12 18:29
The second crash was reported recently and should already be fixed in v16.03.

**Comment by ddennedy** [comment] 2016-03-12 18:41
A workaround is to use the Timeline toolbar's menu (hamburger) button or keyboard shortcuts.

P.S. The bug report states "I cannot add a new track," which is actually incorrect and misleading. There is usually more than one way to do something, and the details are very meaningful. Saying that opening the context menu on the track header or right-clicking on the track header is more accurate.

**Closed** 2016-03-12 20:36 UTC
Labels: crash, reproduced by dev, Windows, workaround

**Comment by Alexander01998** [comment] 2016-03-12 20:50
> The bug report states "I cannot add a new track," which is actually incorrect and misleading.

That was actually the case when I opened this issue, but for some reason I can longer reproduce that crash.

**Comment by ddennedy** [comment] 2016-03-12 21:28
> That was actually the case when I opened this issue

OK, I believe you due to that related bug (#196).

I also just fixed crash bugs in MLT mentioned by @datietou after removing all tracks and adding new ones.
