### ISSUE TITLE
Windows 64 bit - problem with encoding when resizing video

### ISSUE THREAD

**Issue by Hans-Josef** [mltframework/shotcut#115] opened 2015-09-12 14:50 UTC
Encoding a video using the 64bit version for windows works fine if the source video (i.e. the video edited) has the same resolution as the destination format.

If the destination format has a different (lower) resolution the logfile is full of errors like
[IMGUTILS @ 000000000ecff7f0] Picture size 0x360 is invalid
[swscaler @ 0000000010360d20] 1920x1080 -> 0x360 is invalid scaling dimension
and the resulting video is totally bad (video is hanging, sometimes green or black screen; audio plays OK).
Example: Source video: 1920x1080, MTS format, destination 640x360, mp4 format

The problem occurred with versions 15.07.02 (64 bit) and 15.09.10, 15.8.11 (32 bit) and older 32 bit version work fine.

I tried different codecs / output formats / resolutions / rate controls with the 64 bit version - no luck.

**Comment by ddennedy** [comment] 2015-09-12 18:21
I do not reproduce this problem, and I think it is due to your Windows region setting using a comma for the decimal separator. We have known issues with that, but no one has volunteered to help fix it so far.

**Comment by Hans-Josef** [comment] 2015-09-12 22:28
Hi Dan,

thank you for your quick reply.

I am using the "English (Australia)" windows region settings on my computer, so the decimal separator is a dot, not a comma.

Any other ideas? 
Would it be helpful if I send you the complete log file, the source video, or ... ?

Cheers,
Hans-Josef

**Comment by ddennedy** [comment] 2015-09-12 22:35
Give the Settings > Video Mode, and then the steps including details of what you do in the Encode panel.

**Comment by Hans-Josef** [comment] 2015-09-12 22:54
Settings > Video Mode: Automatic

In the encode panel:
- select a format from the stock, e.g. "D10 (dv_ntsc_wide)" or "DVD (dv_pal_wide)"
- click on the "Encode file" button, select/enter file name

**Comment by ddennedy** [comment] 2015-09-14 00:09
Fixed in MLT: https://github.com/mltframework/mlt/commit/5adccf1485307719d897f15eb5add51079618c0e

I will close on the next release, which will include this.

**Comment by Hans-Josef** [comment] 2015-09-14 02:42
Thank you for your quick help.

**Closed** 2015-11-02 00:08 UTC
Labels: reproduced-by-dev, resolved, Windows
