### ISSUE TITLE
Chinese translation does not take effect

### ISSUE THREAD

**Issue by gmg137** [mltframework/shotcut#446] opened 2017-08-16 06:56 UTC
Chinese translation does not take effect
zh_CN
![2017-08-16 14-54-59](https://user-images.githubusercontent.com/6460323/29350923-15561152-8293-11e7-9399-3fc2fe660765.png)

**Comment by ddennedy** [comment] 2017-08-23 04:04
What is your version. This was fixed in v17.06 and the latest version is 17.08, which I just tested and it works for me. I can see you are using an older version in the screenshot because they are not perfectly sorted alphabetically (Greek appears before French), which is something fixed in latest version.

Duplicate of #426

**Closed by ddennedy** 2017-08-23 04:04 UTC
