### ISSUE TITLE
Cannot open files with cyrillic in filenames

### ISSUE THREAD

**Issue by viric** [mltframework/shotcut#381] opened 2017-02-09 11:24 UTC
I have a file История.mp4 in NTFS (Shotcut 17.02 for Windows 64-bit) and I cannot open it. The application log reproduces the error message mentioning the file "D:/dir/??????????.mp4".

If I rename it to ascii, I can open it.

The message about "Could not open file История.mp4" shows up fine in the GUI, in blue, over the timeline.

**Comment by ddennedy** [comment] 2017-02-09 17:15
Duplicate of #278

**Closed by ddennedy** 2017-02-09 17:15 UTC
Labels: duplicate
