### ISSUE TITLE
Export creating inaccurate audio length

### ISSUE THREAD

**Issue by majkol** [mltframework/shotcut#451] opened 2017-09-28 09:22 UTC
Hi,

I am running Shotcut 17.09.04 on MacOS 10.12.6. When I export a file the output generated had slightly longer audio. That varies depending on the audio codec I use from what I've seen. For this test I used a video with SMPTE bars and in-vision TC with frame count. Encoded as 16:9 HD h264 Main YUV 4:2:0 25 fps Refframe 4, Audio AAC 48kHz Avg Bitrate 128kbps. Exact duration of video and audio 1 min

Here are the repro steps:
1. Load a 60 s source video into Shotcut. Add to timeline.
2. Move playhead to 00:00:05:00 and use (s) split at playhead then remove the longer right side part, leaving only first 5 seconds of the clip. The last frame shows 00:00:04:24 (frame 124).
3. Export the timeline as default h.264 Main (Audio AAC 48kHz, Avg Bitrate 256kbps) - container mp4
4. Export the timeline as default DNxHD (atsc_1080p_25) (Audio pcm_s16le 48kHz, Avg Bitrate 384kbps) - container mov

Step no 3 produces the following result when brought back at the timeline (upper is the exported one, lower the original timeline that was exported)
![image](https://user-images.githubusercontent.com/1608810/30956705-76ecf928-a438-11e7-96c2-3ecba4fa8f83.png)

Mediainfo provides duration of video component as 5s0ms, but audio at **5s 35ms**.

Step no 4produces the following:
![image](https://user-images.githubusercontent.com/1608810/30956948-0feae8c4-a439-11e7-982f-791f366f2356.png)

Mediainfo provides duration of video component as 5s0ms, but audio at **5s 152ms**.

Changing bitrate of exports to 128kbps had no effect and produced same results. 

This is what I wasn't expecting especially for PCM. Am I missing something or is this a bug? Can you identify any workarounds?

**Comment by majkol** [comment] 2017-10-03 08:26
Any ideas? Anyone?

**Comment by ddennedy** [comment] 2017-10-10 19:35
There is a good chance this is related to this MLT issue: https://github.com/mltframework/mlt/pull/262

**Comment by ddennedy** [comment] 2017-10-28 21:17
I reproduced it by simply using a SMPTE color bar generator in File > Open Other, setting an out point in the Source player, and exporting - no need to use encoded clip as source or Timeline. (Helps me narrow down potential sources of error and further implicates the avformat consumer.)

**Comment by ddennedy** [comment] 2017-10-28 21:59
I can confirm that the linked MLT pull request fixes this issue. With DNxHD, I get this from MediaInfo:
```
General
Complete name                            : I:/bug451-pcm-2.mov
Format                                   : MPEG-4
Commercial name                          : DNxHD 185
Format profile                           : QuickTime
Codec ID                                 : qt
File size                                : 110 MiB
Duration                                 : 5s 0ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 185 Mbps
Writing application                      : Lavf57.56.101

Video
ID                                       : 1
Format                                   : VC-3
Commercial name                          : DNxHD 185
Format version                           : Version 1
Codec ID                                 : AVdn
Codec ID/Info                            : Avid
Codec ID/Hint                            : DNxHD
Duration                                 : 5s 0ms
Bit rate mode                            : Constant
Bit rate                                 : 184 Mbps
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:2
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 3.540
Stream size                              : 109 MiB (99%)
Language                                 : English

Audio
ID                                       : 2
Format                                   : PCM
Format settings, Endianness              : Little
Format settings, Sign                    : Signed
Codec ID                                 : sowt
Duration                                 : 5s 0ms
Bit rate mode                            : Constant
Bit rate                                 : 1 536 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Stream size                              : 938 KiB (1%)
Language                                 : English`
```
beauty, eh?
We just need to fix a little regression in that pull request to merge it, but it should be done by next release due in about a week.

**Comment by ddennedy** [comment] 2017-10-28 23:16
This is fixed in MLT as good as it is going to get for now. AAC output shows in MediaInfo as 5s 13ms because AAC requires a multiple of 1024 samples, and we try to include all audio data instead of truncating. Doing the math shows 5s 3ms would be the ideal, and there is an extra AAC frame, which might be a side effect of the encoder. (AAC codecs have something known as "codec delay" and must be drained.)

**Closed by ddennedy** 2017-10-28 23:16 UTC
Labels: reproduced by dev, resolved

**Comment by majkol** [comment] 2017-10-29 09:33
Thanks Dan. Beauty indeed :) Much appreciated.
