### ISSUE TITLE
App crashes after trying to drag and drop a video

### ISSUE THREAD

**Issue by Baldovska** [mltframework/shotcut#1329] opened 2022-08-22 19:24 UTC
https://user-images.githubusercontent.com/99900653/186002543-8cf4353a-af9c-4af7-afb9-ca3ab47ddc22.mp4

As the title says I'm trying to add a video to the shotcut by using drag and drop but instead of adding the video to the project the app crashes. Maybe there's something wrong with the video itself? I've edited reddit videos this way but never it crashed like this.
Ubuntu 22.04, Shotcut version 22.06.23
I don't know if it helps but here is the link to the video https://www.reddit.com/r/discordVideos/comments/wutq0n/vibe/

**Comment by ddennedy** [comment] 2022-08-22 19:27
duplicate of #1218

**Closed by ddennedy** 2022-08-22 19:27 UTC
