### ISSUE TITLE
Audio volume lower after adding clip to timeline

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#325] opened 2016-10-20 00:11 UTC
When previewing an audio or video clip in the source panel, the audio volume is as I would expect it (which is especially important for audio clips which were carefully normalized beforehand in some external program). However, after adding the source clip to the timeline, the clip's audio in the project is about 5 db lower. I was able to reproduce this under Arch Linux and Windows 10 with Shotcut 16.10.

**Comment by ddennedy** [comment] 2016-10-20 00:14
This is by design due to mixing. It mixes all tracks down to a hidden silent track, and mixing is a sum process. See related issue #259

**Comment by ddennedy** [comment] 2016-10-20 00:48
Sorry, for the wontfix noise. I was thinking about re-opening and then declined. If we do not mix with a silent track, and instead mix down to some visible track and manage that with track additions and removals, then we will still have a problem. MLT can only mix between 2 tracks - not all of them together. So, the common track used for mixing more than 2 tracks will have its level reduced multiple times, which is really bad. This is why a hidden silent track is used. It can be argued that this limitation in MLT should be fixed, but I can tell you now that it isn't going to happen due to design and size of change required.

**Comment by bmatherly** [comment] 2016-10-20 01:27
Just to add to the confusion... I haven't done a lot of  testing. But try these two things:

1a) Open the count producer and observe the blip at 2 seconds is 0dBFS
1B) Drop the count clip on the timeline and observe that the same blip is now -6dBFS

2a) Open the audio tone producer and observe the tone 0dBFS
2B) Drop the tone clip on the timeline and observe that the ton is *still 0dBFS*

Why is the count affected, but not the tone?

Also, is the solution as simple as adding 6dB of gain to the output of the entire timeline? Or is there some more complicated formula required to get the output level to match the input level for any given clip?

**Comment by ddennedy** [comment] 2016-10-20 02:52
A workaround is to add a gain filter to the Timeline by selecting the top, left corner of the Timeline (a.k.a. the cornerstone). This is known in some reading material as "makeup gain."

**Comment by ochilan** [comment] 2016-10-20 08:39
Thank you very much for the quick responses. It's really a pity that this is such an issue, I thought this would be a fundamental thing to support. I'll use the workarounds in the meantime, I guess – does the quality of the audio suffer from adding the additional gain to everything? Otherwise shotcut seems to do everything I need for my purposes pretty well and it would be a pity to ditch it because of this.

**Comment by ochilan** [comment] 2016-10-31 21:54
I've been working more with shotcut in the last few days and I think it does have a lot of potential. But the audio mixing is just very broken – no matter if it's MLT or shotcut itself, this should not be wontfix. The audio mixing also depends on the order which the audio tracks have in the project. A simple repro is to create two tracks with e.g. a 440 and a 220 Hz sines, put them both into one project and listen to the result of the two possible orders. This gets a lot more pronounced with more tracks. Should I open another ticket? Something should be done regarding this.

**Comment by ddennedy** [comment] 2016-11-01 03:20
I thought of a way to try to fix this. Not yet sure if it will be in next release 16.11 but definitely next if not.

**Comment by ochilan** [comment] 2016-11-01 16:54
That sounds promising, thank you. By the way, I did some experiments with other NLEs and their approaches to audio mixing are quite different. Kdenlive or even Adobe Premiere seem to use a sum of all audio tracks, even if this results in clipping. The result of flowblade appears to be more similar to what shotcut currently does, i.e. a nonlinear increase of amplitude with increasing number of overlaid audio tracks. That said, the result of the latter is less predictable or intuitive, at least for me. Since there will never be a magic wand for every case where audio tracks need to be mixed down, maybe it would even be better to stick to a "simple" solution and ultimately let the user decide what to do in case clipping occurs (e.g. applying a limiter to the final mix, reducing gain of individual tracks or the like).

**Closed** 2016-11-19 22:14 UTC
Labels: workaround
