### ISSUE TITLE
Crackles during export again?

### ISSUE THREAD

**Issue by orex** [mltframework/shotcut#1274] opened 2022-05-27 08:47 UTC
Hello!

Thank you very much for so awesome project! I have problems in exported video: audio crackles in the beginning. I found that the similar issue was fixed in [v19.12.16](https://github.com/mltframework/shotcut/releases/tag/v19.12.16), but I did not find an neither an issue, not commit that fixed it.

My system: Ubuntu 20.04.4 LTS, shotcut 22.04.25 from snap.

An example video:
https://www.tiktok.com/@lopatadoglowy/video/7102041102404078854

Thank you in advance.

**Comment by ddennedy** [comment] 2022-05-27 20:14
duplicate of #1265

**Closed** 2022-05-27 20:14 UTC
Labels: duplicate

**Comment by orex** [comment] 2022-05-29 10:07
This is not the duplication of the issue. My "investigation" shows that it is more related to the issue https://github.com/mltframework/mlt/issues/741 and because of flac as audio codec. Changing it to WAV solve the problem.
