### ISSUE TITLE
Project with one clip only doesn't show filters at times

### ISSUE THREAD

**Issue by qubodup** [mltframework/shotcut#582] opened 2018-06-02 15:17 UTC
1. Import 1 image (works with video too)
2. Add image to timeline
3. Apply 1 filter to clip in timeline
4. Save, restart, load project
5. Click clip

Expected:
Filters tab shows filters of clip

Actual:
Filters tab is empty even if filters are visibly active in the preview monitor

Video: https://youtu.be/ZCnRfXg9dtU

**Comment by ddennedy** [comment] 2018-06-02 16:09
Duplicate of #358.

**Closed by ddennedy** 2018-06-02 16:09 UTC
Labels: duplicate
