### ISSUE TITLE
Can't see the controls in the filters

### ISSUE THREAD

**Issue by ViaFra** [mltframework/shotcut#1426] opened 2023-04-16 11:07 UTC
When using filters like "Size, Position and Rotate" and others, I don't see any controls like frames and dots. They are there, I can "feel" them with the mouse cursor, but they are not visible. This is very inconvenient. 
In the appimage version, these elements are visible. But I would prefer flatpak.
How to fix the problem?
Shotcut version 22.12.21, Linux Mint 21.1 with Cinnamon 5.6.8, kernel 5.15.0-69-generic, AMD Ryzen 3 3200G with Radeon Vega Graphics × 4, Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series]

**Comment by ddennedy** [comment] 2023-04-16 17:47
Duplicate of a few others here. It is a bug in the Qt version it uses with no way to downgrade it. Solution is to get the beta.

**Closed** 2023-04-16 17:47 UTC
Labels: duplicate
