### ISSUE TITLE
Cannot drag and drop clip from playlist to timeline

### ISSUE THREAD

**Issue by ldennedy** [mltframework/shotcut#330] opened 2016-10-21 02:32 UTC
Tested on OSX and Windows 10, along with others who have reproduced it on Windows 7. Shotcut versions I tested were all 16.10.1.

Steps to reproduce:
1) Load clip and add to playlist
2) Drag to timeline
3) Add new video track
4) Move clip to new video track
5) Drag new clip from playlist again into timeline

Expected result: You should be able to drag the clip from the playlist anywhere in the timeline
Outcome: Mouse cursor turns into a red slashed circle (a "no" symbol) and the clip cannot be placed.

The paste/append to timeline button still works, but drag and drop is an important/intuitive method that should work as well.

**Comment by ddennedy** [comment] 2016-10-21 03:48
This is a duplicate of #326.

**Closed by ddennedy** 2016-10-21 03:48 UTC
Labels: duplicate, reproduced by dev
