### ISSUE TITLE
"Encode" function doesn't work?

### ISSUE THREAD

**Issue by SeaHay** [mltframework/shotcut#199] opened 2016-03-03 19:31 UTC
Every time I try to encode a video with .mp4, no matter how I change the settings around, the video and audio are missing and all I get is a minute long of nothingness.

I am running the latest version of Shotcut with Windows 10

**Comment by ddennedy** [comment] 2016-03-03 19:57
Try running Shotcut as admin to see if this problem goes away. We have heard about a problem related to files not found during encode when not running as admin but still not able to reproduce it ourselves to fix it.

**Comment by ddennedy** [comment] 2016-03-04 04:10
Duplicate of bug #198
When that bug was reported, I created a new non-admin user on Windows 10, logged in as standard user, but did not reproduce the problem. Still searching for the cause - a way to trigger the problem.

**Comment by SeaHay** [comment] 2016-03-04 15:35
thanks! I'll try them and report back the logs if anything comes up for either

**Comment by SeaHay** [comment] 2016-03-04 15:54
running the program as admin worked

**Closed** 2016-03-08 02:31 UTC
Labels: pending

**Comment by ddennedy** [comment] 2016-03-09 05:36
Can I get you to test this new build with the proposed fix?
http://builds.us.meltytech.s3.amazonaws.com/shotcut/shotcut-win64-160308.exe

You should first reproduce the problem again. Then, install new version. Next, without running as admin, see if the new version works. Thanks

**Comment by SeaHay** [comment] 2016-03-09 11:31
sure, what do you need me to look for?

**Comment by bmatherly** [comment] 2016-03-09 12:25
@SeaHay Using the new build, try to encode a file while *not* running as admin.

**Comment by SeaHay** [comment] 2016-03-09 18:04
Extorting a .avi file with no changes to the footage (other than the encoding) with the "H.264 Main Profile" preset, with an export output of a .mp4:

After exporting, the rendered video featured audio, but still no video.


Log:
medium: [ ref=1, _mlt_properties_load=medium, __mlt_properties_load=medium ]
[libx264 @ 000000000479c760] [Eval @ 000000000b30ed80] Undefined constant or missing '(' in 'dct8x8'
[libx264 @ 000000000479c760] Unable to parse option value "dct8x8"
[libx264 @ 000000000479c760] [Eval @ 000000000b30ed80] Undefined constant or missing '(' in 'main'
[libx264 @ 000000000479c760] Unable to parse option value "main"
[aac @ 000000000f3dc7a0] [Eval @ 000000000b30ed10] Undefined constant or missing '(' in 'dct8x8'
[aac @ 000000000f3dc7a0] Unable to parse option value "dct8x8"
[libx264 @ 000000000479c760] height not divisible by 2 (448x345)
[swscaler @ 000000000f656c20] Warning: data is not aligned! This can lead to a speedloss

**Comment by SeaHay** [comment] 2016-03-09 18:04
Extorting a .avi file with no changes to the footage (other than the encoding) with the "H.264 Main Profile" preset, with an export output of a .mp4:

After exporting, the rendered video featured audio, but still no video.


Log:
medium: [ ref=1, _mlt_properties_load=medium, __mlt_properties_load=medium ]
[libx264 @ 000000000479c760] [Eval @ 000000000b30ed80] Undefined constant or missing '(' in 'dct8x8'
[libx264 @ 000000000479c760] Unable to parse option value "dct8x8"
[libx264 @ 000000000479c760] [Eval @ 000000000b30ed80] Undefined constant or missing '(' in 'main'
[libx264 @ 000000000479c760] Unable to parse option value "main"
[aac @ 000000000f3dc7a0] [Eval @ 000000000b30ed10] Undefined constant or missing '(' in 'dct8x8'
[aac @ 000000000f3dc7a0] Unable to parse option value "dct8x8"
[libx264 @ 000000000479c760] height not divisible by 2 (448x345)
[swscaler @ 000000000f656c20] Warning: data is not aligned! This can lead to a speedloss

**Comment by SeaHay** [comment] 2016-03-09 18:04
Extorting a .avi file with no changes to the footage (other than the encoding) with the "H.264 Main Profile" preset, with an export output of a .mp4:

After exporting, the rendered video featured audio, but still no video.


Log:
medium: [ ref=1, _mlt_properties_load=medium, __mlt_properties_load=medium ]
[libx264 @ 000000000479c760] [Eval @ 000000000b30ed80] Undefined constant or missing '(' in 'dct8x8'
[libx264 @ 000000000479c760] Unable to parse option value "dct8x8"
[libx264 @ 000000000479c760] [Eval @ 000000000b30ed80] Undefined constant or missing '(' in 'main'
[libx264 @ 000000000479c760] Unable to parse option value "main"
[aac @ 000000000f3dc7a0] [Eval @ 000000000b30ed10] Undefined constant or missing '(' in 'dct8x8'
[aac @ 000000000f3dc7a0] Unable to parse option value "dct8x8"
[libx264 @ 000000000479c760] height not divisible by 2 (448x345)
[swscaler @ 000000000f656c20] Warning: data is not aligned! This can lead to a speedloss

**Comment by ddennedy** [comment] 2016-03-09 18:45
@SeaHay Your latest problem is not related to the original problem. The new problem is "[libx264 @ 000000000479c760] height not divisible by 2 (448x345)". You need to fix your resolution.

It may be argued that Shotcut should enforce this, but there are literally thousands of rules for all the different formats and codecs and all of their parameters. Shotcut is not at this time trying to enforce a lot of rules, and adding that is also likely to introduce new bugs and unexpected or undesired limitations. This issue will remain closed.
