### ISSUE TITLE
Black bars around the video after publishing

### ISSUE THREAD

**Issue by Astriel07** [mltframework/shotcut#416] opened 2017-04-07 13:57 UTC
Hello :-).

I just want to mention a bug, which i read about in the shotcut forum as well - so I don't seem to be the only one with this issue. I have no idea where it comes from, but sometimes when I export a video it will have black bars around it and if you extend it to full screen it will be quite small because of the black bars. 

My current solution is to save the project, close Shotcut, restart it and after opening the project file answer yes to the question: do you want Shotcut to repair the project? When I export now everything will be fine. But this solution isn't really comfortable (especially because I want to use Shotcut in my company).

Someone in the forum said, that for him it worked to set the PC locale from German to English (I'm German too), but I actually don't want to change my locale ;). Maybe you have an idea where this bug comes from and how to solve it in a future update.

Best Regards and thx in advance,
Jan-Philipp

**Comment by ochilan** [comment] 2017-04-07 17:24
Hello Jan-Philipp,

I'm also a German user using mostly English user interfaces with partial German locale (e.g. for date and time) and I know that certain problems may arise due to this, but I haven't heard of this particular issue yet. Can you give us some more information what exactly you need to do for this issue to arise? What kind of video are you editing, what is its size, which profile are you using in shotcut, which settings for exporting are you using, are you using video filters?

Best regards
Sebastian

**Comment by Schyrsivochter** [comment] 2017-04-07 20:23
I’m also a German user and I have noticed that sometimes, projects are saved with the wrong (English) decimal point format, so in and out points are messed up when reopening the project.

**Comment by Astriel07** [comment] 2017-04-10 11:49
Dear Sebastian,

thanks for the fast reply! I'm editing .mov clips, which I just split a few times and add some cross-fades and maybe some fade-ins and fade-outs. Nothing special or fancy. Then I use the custom profile to export it into mov again, using the libx264 codec. All the other options I don't touch.

![image](https://cloud.githubusercontent.com/assets/27008398/24860253/06535722-1df4-11e7-9a28-fbb85924f386.png)

This is how the preview in Windows looks like. As you can see, the resolution is correct, but the bars are there. The original clip was just normal. The next pictures show all the settings of the export.

![image](https://cloud.githubusercontent.com/assets/27008398/24860308/46626dbc-1df4-11e7-8a02-8c39dca95886.png)
![image](https://cloud.githubusercontent.com/assets/27008398/24860320/508b20d6-1df4-11e7-8dbb-8932b439488e.png)
![image](https://cloud.githubusercontent.com/assets/27008398/24860333/5ba8c662-1df4-11e7-8723-e1ff75e964b1.png)
![image](https://cloud.githubusercontent.com/assets/27008398/24860345/68e05818-1df4-11e7-8c15-1bff38d26dc5.png)

Thank you for your help :).

Best Regards,
Jan-Philipp

**Comment by ochilan** [comment] 2017-04-12 21:47
Hello,

sorry but I still have trouble understanding the issue. The image shows a preview in Windows Explorer which obviously is square shaped and the space over and under the video is simply filled by black color. As you said, the video dimensions are shown correctly in the metadata. Does it also show like this in a video player? What exactly is different after repairing the XML and re-exporting? Can you show us the XML file(s) before and after repairing?

Best regards
Sebastian

**Comment by Astriel07** [comment] 2017-04-13 09:09
Hello Sebastian,

yes, in the player it looks exactly like in the preview and if i expand the video to fullscreen the black bars will make the video quite small.

![image](https://cloud.githubusercontent.com/assets/27008398/24998048/1f78fa12-2039-11e7-99f9-fa210cd3a9a0.png)

here you find the XML files of an example:

[Black bars.zip](https://github.com/mltframework/shotcut/files/918983/Black.bars.zip)

Thank you very much,
Jan-Philipp

**Comment by ochilan** [comment] 2017-04-13 16:20
Hello,

first off, I despise locale settings. With this out of the way, the XMLs you provided show that the original (non-repaired) file has the de_DE numeric locale setting (the value of LC_NUMERIC in the second line) but at the same time it uses dots instead of commas as the decimal separator which is weird, and which may cause the problem you're seeing when opening the file because it is inconsistent. The repaired file has de_DE locale and uses commas.

I tried to create a file with shotcut on Windows 10 that has the same problem, but I was not able to achieve this yet. I'm normally using Windows in English language, but with German numeric and date format which can be set separately in the "Region" control panel (not sure what its name is in the German Systemsteuerung but it's the control panel where you have five drop down menus for date formats and you can set additional settings like the decimal separator in an extra dialog that you get using the "Additional settings..." button at the bottom).

At any rate, shotcut always seems to use whatever I set in the Region control panel. If it is set to English (US) then en_US locale and dots will be used, when set to German it sets de_DE locale and uses commas. Even if I override the decimal separator manually in the additional settings (e.g. German locale but it should use dots), it will then use that decimal separator without problems. The only way I was able to reproduce the problem yet was to save the file using one setting, change the locale settings in Windows (and restart shotcut) and then trying to open the XML again, but then it is reasonable that the decimal separators don't match the locale given in the XML file.

Have you done any manual tweaking of the Region settings before? Can you show us screenshots of those settings in Windows maybe?

**Comment by ddennedy** [comment] 2017-04-14 15:58
The problem exhibited in the uploaded XML files as described by @ochilan can be reproduced by changing the Windows control panel Region > Additional Settings > Decimal Symbol to something inconsistent with the named Format. I was not able to reproduce the reported problem, but this region number format override is not currently supported by Shotcut (or apparently the cross-platform technologies it uses). When I tried to reproduce it by using Format = German, Decimal symbol = period; in the Shotcut Application Log I see
```
[Info   ] <Application::Application(int&, char**)> locale = QLocale(German, Latin, Germany)
...
[Debug  ] <MltXmlChecker::MltXmlChecker()> decimal point ',' 
```
As you can see, it did not read the Decimal symbol setting, which is retrieved using a third party library.
To fix it, you can try this:
1. Open the Windows Region control panel.
1. Click Additional settings...
1. Click Reset...
1. Click Yes, OK, and OK
1. Restart Shotcut if it was already running

**Comment by ddennedy** [comment] 2017-04-14 16:06
Further, MLT, was able to see the decimal point setting in order to write the XML with numbers with periods. However, the Shotcut MLT XML validation function was not. Then, MLT still sees the system decimal point setting and tries to interpret numeric strings using that even though Shotcut converted them to something consistent with the named Region. It seems the solution is for Shotcut's XML validation function to use the same approach as MLT for looking up the decimal point.

**Comment by Astriel07** [comment] 2017-04-15 16:12
Hi again,

firstly thank you very much for all your thoughts and advices concerning this topic. When you talk about XML and mlt files I cannot follow you anymore, because I'm just a normal user without any further technical knowledge ;). But I see, that there seems to be a problem with the decimal point settings in Germany. When I'm back at work after Easter I will test your workaround, but I might not have the admin rights to change such things in my computer.
@ochilan I haven't done any manual tweaking of the region settings. I will take a screenshot after the holidays.

Best Regards,
Jan-Philipp

**Comment by ddennedy** [comment] 2017-04-16 18:01
I have an attempt to fix this, and I can provide a nightly build tomorrow for you to check it.

**Comment by ddennedy** [comment] 2017-04-18 03:35
Here is the nightly build for Windows to try:
http://builds.us.meltytech.s3.amazonaws.com/shotcut/shotcut-win64-170417.zip

Unzip this somewhere and double-click shotcut.exe within the folder to run it.
If it does not work with an existing project, you might try to create a new project and then also see if the repair offer goes away upon re-opening the project.

**Comment by Astriel07** [comment] 2017-04-20 09:02
Hello Dan,
thank you very much for this build! My first try exporting a video directly worked without black bars. Strangely I cannot reproduce the black bars anymore after I opened your new build once (even if i open the old build). I have no idea how that can be possible, eventually it happened each time before. I will have my colleague try it out, who also faced the same issue. But for now thanks a lot.

Best Regards,
Jan-Philipp

**Comment by ddennedy** [comment] 2017-04-20 16:02
Thanks, I will close this now as resolved for the next release.

**Closed by ddennedy** 2017-04-20 16:02 UTC
Labels: Windows, workaround
