### ISSUE TITLE
Splitting a slowed down clip resets the speed property to 1

### ISSUE THREAD

**Issue by anzx42** [mltframework/shotcut#221] opened 2016-04-15 16:27 UTC
On Windows with GPU processing enabled, Slowing down a clip by setting the speed to 0.3 slows down the clip as it should. But then splitting that clip keeps the clip slow, but the speed value in the properties displays 1

**Comment by ddennedy** [comment] 2016-04-15 16:52
Not able to reproduce on OS X (not in front of Windows at the moment, and the choice of OS should not make a difference here). Did you re-select the clip on the timeline just to be sure? Maybe sometimes Properties does not get updated. Are you certain you did not switch to the Source player tab? Please provide steps to reproduce.

**Comment by ddennedy** [comment] 2016-05-04 04:48
I believe this is a duplicate of #231

**Closed by ddennedy** 2016-05-04 04:48 UTC
Labels: GPU, pending
