### ISSUE TITLE
Issue with not displaying editable properties of filters

### ISSUE THREAD

**Issue by popgoesme700** [mltframework/shotcut#1082] opened 2021-04-29 04:40 UTC
This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

"Arch Shotcut 21.03.21" seems to have a bug where properties of some filters do not show, not allowing you to edit them.
Top left of image displays filter of text: simple with no way to edit the text, other then its position in the preview window.
![image](https://user-images.githubusercontent.com/17504205/116503092-7a81d800-a872-11eb-994e-e8fab8689519.png)

**Comment by ddennedy** [comment] 2021-04-29 04:45
Duplicate of #1069

**Closed by ddennedy** 2021-04-29 04:45 UTC
