### ISSUE TITLE
Performing 'undo' on 'detach audio' does not restore audio to video clip.

### ISSUE THREAD

**Issue by cyan-lime** [mltframework/shotcut#871] opened 2020-05-25 07:23 UTC
When trying to undo 'detach audio', the newly created audio track is removed, but the audio is not then restored to the video track again, as expected.

Steps to reproduce:
1. Detach audio from a video clip
2. Perform 'undo'. The audio is now missing.

Noticed on Shotcut 20.04.12 (Flatpak) on Fedora Workstation 32

**Comment by ddennedy** [comment] 2020-05-25 07:30
This was already fixed for the next release due in June. Duplicate of #858

**Closed by ddennedy** 2020-05-25 07:30 UTC
