### ISSUE TITLE
Shotcut shutdowns on opening a video file

### ISSUE THREAD

**Issue by martyca65** [mltframework/shotcut#695] opened 2019-02-15 16:34 UTC
An interesting bug has developed with Shotcut running the latest 19.01.27 version. Initially, Shotcut was working on Ubuntu 18.04 LTS but now Shotcut will launch but as soon as I open any video file it shuts down almost immediately. Now here is the curious bit if I double click on the file in my recent list it will bring the file in without Shotcut crashing. Running Nvidia Quadro 620 card on an HP Z420 with an E5-1650 CPU and 32 Gb of ram. The latest version of Shotcut does not have the option of using GPU. So I don't know whether some recent update to Ubuntu has caused an issue with this.

Below is an extract of all warnings from the Shotcut log:
[Warning] [ 0x1208e30] The DeckLink drivers not installed.
[Warning] <> libpng warning: iCCP: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG
[Debug ] LeapNetworkListener::onDisconnected Disconnected from Leap Motion
[Debug ] LeapNetworkListener::onError Leap Motion WebSocket error: "Connection refused"
[Warning] <> libpng warning: iCCP: known incorrect sRGB profile
[Warning] <> libpng warning: iCCP: known incorrect sRGB profile

There is also a section of Debug talking about WILD TIMESTAMP

**Comment by ddennedy** [comment] 2019-02-15 18:21
None of these messages are actual problems or show the cause of the crash.
I too have experienced some decreased stability, and I see more crashes occurring within Qt. I think it corresponds to when I started to bundle many more libraries trying to increase the independence/portability of the "portable tar," AppImage, and snap versions. There is also the fact that the Qt we are bundling was built on Ubuntu 14.04, but with version 18.12.x started to build Shotcut on Ubuntu 16.04 for the VA-API integration. I am in the process of upgrading Qt and building both Qt and Shotcut on Ubuntu 16.04. (18.04 is not used to increase compatibility.) I will have a beta version of that soon for you to try.

**Comment by ddennedy** [comment] 2019-03-10 21:35
closing for no update and no reliable way to reproduce

**Closed by ddennedy** 2019-03-10 21:35 UTC

**Comment by martyca65** [comment] 2019-03-11 01:45
I have reproduced this problem on three different machines all running
Ubuntu 18.04 LTS.

**Comment by ddennedy** [comment] 2019-03-11 04:02
There was a beta and a new release in the past 3 weeks. It is based on a completely new build of Qt on same version of OS and compiler as MLT and Shotcut build. I did not get feedback on either of these versions. Please test on the new version 19.02.28

**Comment by martyca65** [comment] 2019-03-11 07:13
Okay will do

**Comment by martyca65** [comment] 2019-03-11 14:19
Okay checked version 19.02.28 and it seems stable now. No shutting down on
opening video files. I also had version 19.02.27 on an older machine and
that seems stable as well. Maybe the problem was on the Ubuntu end, with
Ubuntu updates fixing the problem.

Thanks for all your work.

Regards,
Martin
