### ISSUE TITLE
Cannot find file after Export

### ISSUE THREAD

**Issue by mrehanabbasi** [mltframework/shotcut#772] opened 2019-09-18 20:33 UTC
Whenever I try to export a video (using default settings or any preset), it shows the progress bar in Jobs and completes the job in 2-3 seconds which is clearly not possible. It shows the check mark as well. Also, the output file is nowhere to be found in the path which I provided.

My Job Log is as follows:

```
plugin_mgr_get_object_file_plugins: error opening shared object file 'C:\Program Files\Shotcut\lib\ladspa/AUTHORS': "C:\Program Files\Shotcut\lib\ladspa\AUTHORS": The specified module could not be found.
plugin_mgr_get_object_file_plugins: error opening shared object file 'C:\Program Files\Shotcut\lib\ladspa/COPYING': "C:\Program Files\Shotcut\lib\ladspa\COPYING": The specified module could not be found.
plugin_mgr_get_object_file_plugins: error opening shared object file 'C:\Program Files\Shotcut\lib\ladspa/readme.txt': "C:\Program Files\Shotcut\lib\ladspa\readme.txt": 
I/O warning : failed to load external entity "C:/Windows/Temp/shotcut-U14568.mlt"
[AVIOContext @ 0000000005480500] Statistics: 1785 bytes read, 0 seeks
[AVIOContext @ 0000000005480500] Statistics: 1785 bytes read, 0 seeks
Failed to load "C:/Windows/Temp/shotcut-U14568.mlt"
I/O warning : failed to load external entity "C:/Windows/Temp/shotcut-U14568.mlt"
[AVIOContext @ 0000000005480500] Statistics: 1785 bytes read, 0 seeks
[AVIOContext @ 0000000005480500] Statistics: 1785 bytes read, 0 seeks
Failed to load "C:/Windows/Temp/shotcut-U14568.mlt"
Completed successfully in 00:00:02
```

My application log is as follows:

```
...

[Info   ] <MainWindow::on_actionOpenXML_triggered> "VideoPath.mlt" 
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 0 total_channels 2 max_channels 2
[Info   ] <MLT> [filter swresample] 2(stereo) f32le 44100Hz -> 2(stereo) f32le 48000Hz
[Debug  ] <MLT> [producer avformat-novalidate] "VideoPath/Raw - Converted.mov" checking VFR: pkt.duration %I64d
[Info   ] <MLT> [consumer sdl2_audio] Audio Opened: driver=xaudio2 channels=2 frequency=48000
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat-novalidate] "VideoPath/Raw - Converted.mov" checking VFR: pkt.duration %I64d
[Debug  ] <EncodeDock::on_encodeButton_clicked> 12218859520 bytes available on "OS" 
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat-novalidate] "VideoPath/Raw - Converted.mov" checking VFR: pkt.duration %I64d
[Debug  ] <MeltJob::start> "C:/Program Files/Shotcut/qmelt.exe" ("-verbose", "-progress2", "-abort", "C:/Windows/Temp/shotcut-U14568.mlt") 
[Info   ] <AbstractJob::onFinished> job succeeeded
``` 

I am using Windows 10 1903 OS build 18362.356 (64-bit) and my Shotcut version is 19.09.14 (64-bit).

**Comment by ddennedy-gpsw** [comment] 2019-09-18 20:36
The problem is 
> failed to load external entity "C:/Windows/Temp/shotcut-U14568.mlt"

This means there is some offending character in the XML that was not escaped properly. You can upload your project file here for me to look at, fix, and make a code fix if possible. To upload here, you need to copy it to a .txt file or zip it. If you need a more confidential way to share the file let me know.

**Comment by mrehanabbasi** [comment] 2019-09-19 04:15
[Project.txt](https://github.com/mltframework/shotcut/files/3629334/Project.txt)

**Comment by ddennedy** [comment] 2019-09-19 04:24
I have not found any error in the XML. Maybe you tried to export with something in the export file name that causes the problem. When you export, a different XML with more information about the export is written. On a failed export job, right and choose View XML > Save and upload that please.

**Comment by mrehanabbasi** [comment] 2019-09-19 16:16
Here you go:

[Export.txt](https://github.com/mltframework/shotcut/files/3632249/Export.txt)

**Comment by ddennedy** [comment] 2019-09-19 17:37
Export.xml does not show an error either. It shows that you use File > Open MLT XML as Clip and then exported it. I am not sure why instead of simply File > Open. In any case, the path to the .mlt file should be full and absolute but it is not. Did you edit it to hide information? If not somehow, the .mlt file in C:/Windows/Temp cannot be found or accessed. This problem seems specific to your system. Maybe you are running something that is blocking access or immediately deleting files. I do not know what it is.
I will take this up as a bug to properly reflect this as a failure in the UI. Meanwhile, you will have to figure out why it is failing to find your temp file. When you get this error and before closing Shotcut or removing the job, try to locate and read the temp file that it reports. You can also try using just File > Open to export instead of Open MLT XML as Clip.

**Comment by mrehanabbasi** [comment] 2019-09-19 17:57
I'm getting the same error even after using it with File > Open.. I've reinstalled Shotcut and even tried the portable version but get the same error.. I even tried this after disabling my antivirus program and Windows Defender but it didn't work..

And yeah, I did change the file path..

So, what are my options now?

**Comment by ddennedy** [comment] 2019-09-19 18:42
I was mistaken about the original meaning of the error. The error is more related to file opening. What you can do is save the export job to a file named .mlt. And then at the command line (e.g. cmd.exe) run `"C:\Program Files\Shotcut\qmelt.exe" -verbose -progress2 -abort "path to your export .mlt"`

**Comment by mrehanabbasi** [comment] 2019-09-19 19:00
I restarted Shotcut as Administrator and it worked like a charm.. I guess there was an issue accessing the `C:\Windows\Temp` directory without Admin privileges..

**Comment by ddennedy** [comment] 2019-09-19 19:18
This is not normal. On my system Shotcut uses the user-specific temp folder, in my case `C:/Users/ddennedy/AppData/Local/Temp/`. I also get to here by typing `%temp%` into the explorer address bar. Something may have messed with your environment variables. 

![image](https://user-images.githubusercontent.com/1146683/65273924-1c5a1400-dad7-11e9-81af-09ca4441486e.png)

TEMP should be `%localappdata%\Temp`


`Windows\Temp` is not for users: https://answers.microsoft.com/en-us/windows/forum/all/temp-folder-keeps-losing-permissions/486075fb-90e1-468d-9995-847c1c21c076

**Comment by ddennedy** [comment] 2019-09-22 01:24
Reopening to improve error handling (including a check for usable TEMP)

**Closed** 2019-11-24 02:53 UTC
