### ISSUE TITLE
New Shotcut-Versions: Speedy v20.11.28 - Slow v21.01.16 - Unusable slow v21.01.29

### ISSUE THREAD

**Issue by pauweh** [mltframework/shotcut#1038] opened 2021-02-12 08:11 UTC
Using these Shotcut-Versions with Windows 10 from portable zip file with a 20 minutes 4K-mlt-script is a pleasure to work with in v20.11.28. Proxy preview is fast and easy. But after update to 21.01.29 it is horrible slow and unusable. It takes minutes and minutes to just load. Later on just opening a menu like "Edit" or "View" takes a second or two. Tried version 21.1.16, too. It is slow and lagy and proxy preview is stop and go. My hope was GPU GTX1060 with 6GB would help but to enable the GPU for proxy-computing or export does not improve speed at work, of course. 16GB RAM main memory are not fully used. There are always some GBytes free.

**Comment by ddennedy** [comment] 2021-02-12 08:15
Someone else on the forum reported the same thing:
https://forum.shotcut.org/t/is-anyone-seeing-a-performance-regression-in-21-01-29/24990/2

But we do not know why. None of the developers have experienced the problem, and things recommended to try so far have not worked. Very weird.

**Comment by ddennedy** [comment] 2021-02-14 03:57
From the forum post

>Tried opening the same mlt-file at the same time in both versions, using taskmanager to switch between the versions of Shotcut.

There is a known performance problem running multiple instances of Shotcut at the same time.

**Comment by Victoralm** [comment] 2021-02-26 13:00
Same problem here. With the same GPU, by the way.

**Comment by nuket** [comment] 2021-03-15 12:22
A few thoughts:

1. Would it be possible to use Process Monitor to see what's happening under the hood as shotcut.exe is running?
2. Exclude the Shotcut folder from Windows Defender's realtime antivirus scanning?
3. Disable Windows Defender's realtime antivirus altogether while editing?

Number 3 is a huge boost when compiling software, not sure how much of an impact it would have here with a totally different usage pattern.

For my own system, the latest versions seem to work better than earlier versions. But I haven't done any extensive benchmarks. No regressions, though.

**Comment by pauweh** [comment] 2021-03-15 18:03
ProcessExplorer tells me while renbdering an mp4 that CPU is running with melt.exe at nearly 100% using all 6 cores. When trying to use GPU for rendering with hevc_nvenc etc. CPU goes down to 30-50% or less. But GPU is never more than 3%!. So rendering is now faster at all.
When re-rendering a mp4 with FFmpeg commands directly without Shotcut GPU is nearly 100% rendering more than 100 fps. Rendering some minutes of video takes not longer than viewing same video or is even faster. Thats 30-50 times faster then Shotcut can do same tasks. Shotcut needs hours to render some minutes of mp4. 

I dont think that Defender is a problem since I dont see this process taking CPU time when Shotcut is slow. Isnt Defender scanning input and output from/to files most of its time?
Writing MBytes into one mp4 file takes 10 hours with ShotCut so input/output scanning ist the problem I guess.

Shotcut has a problem with using his CPU time and is not able to use GPU in an efficient way. FFmpeg is able to use GPU with 100% when rendering the same mp4 with same parameters 4K, 30fps etc. Shotcut never uses more than 3% GPU. Windows TaskManager is able to show these differences.
So I am guessing the FFmpeg calls of ShotCut are missing some parameters enforcing more and direct GPU usage. 
I did try to add some FFmpeg parameters into the "Other" tab of "Export File". But the Rendering-Jobs log-files tells me thats not working. Shotcut does not pass my settings to its FFmpeg calls.

**Comment by nuket** [comment] 2021-03-15 19:35
Hmm. Yeah, looks like melt.exe isn't using the GPUs at all. Surprising that there aren't some hints or error messages in the rendering log about what's not working quite right.

> Isnt Defender scanning input and output from/to files most of its CPU time?

Yes, it intercepts file operations. Shouldn't be an issue on big multimedia files, more an issue when it's a lot of small files.

What are the ffmpeg command lines that you see? Which one works? Which one doesn't?

**Comment by ddennedy** [comment] 2021-03-15 19:47
You should retest on v20.02.27.  For the related post link I provided above, the problem was solved in that version.

**Comment by pauweh** [comment] 2021-03-18 17:41
Did some testing and log-viewing with v21.02.27. CPU goes down with HW-encode. But GPU is still only 1 - 3% video-encoding.
A 4k.mp4 (30fps, ~5:50 min = 10559 frames) exported with HW-enabled by Shotcut takes more than one hour, achiving ~3 fps
(see Export-Settings.jpg and v21.2.27-GPU-use.jpg) By the way: HW-enabled DaVinci is not faster, same 3 fps.

The 4k.mp4 10559 frames, encoded it with this FFmpeg command:
"ffmpeg -vsync 0 -hwaccel cuvid -hwaccel_output_format cuda  -i 4k.mp4 -c:a copy -c:v hevc_nvenc  -gpu all 4k-hevc_nvenc.mp4"
FFmpeg result after less than 2 minutes: frame=10559 fps=102 speed=3.39x (see FFmpeg-GPU-use.jpg)
FFmpegs GPU usages for Video-Encoding goes up to 100%. Keep in mind: GPU Video-Encoder is not GPU usage.
See appended charts from taskmanager (able to show video-encoder usage) and process-explorer (only showing GPU over all).

The Shotcut export-logs say "missing hwaccel parameters. skipping hardware initialization"
and [hevc_nvenc @ xxx] Using global_quality with nvenc is deprecated. Use qp instead"

So the FFmpeg option -hwaccel seems to enable GPUs video-encoding.
Tried to set hwaccel=cuvid and hwaccel_output_format=cuda in the Export-Other-tab,
but this is not passed to the export-jobs FFmpeg.


[Export-hevc_nvenc.log](https://github.com/mltframework/shotcut/files/6166193/Export-hevc_nvenc.log)
[Export-hevc_nvenc-hwaccel.log](https://github.com/mltframework/shotcut/files/6166194/Export-hevc_nvenc-hwaccel.log)
[Export-libx265.log](https://github.com/mltframework/shotcut/files/6166195/Export-libx265.log)
![Export-Settings](https://user-images.githubusercontent.com/23434241/111671679-7a290280-8819-11eb-965a-f9f69a17f7f2.jpg)
![FFmpeg-GPU-use](https://user-images.githubusercontent.com/23434241/111671681-7ac19900-8819-11eb-883d-60a32f504673.jpg)
![v21 2 27-GPU-use](https://user-images.githubusercontent.com/23434241/111671687-7b5a2f80-8819-11eb-9754-e8cc234887e8.jpg)

**Comment by ddennedy** [comment] 2021-03-18 18:45
This bug report is now invalid because you are changing the target and comparing apples with oranges. First you were now mainly focused on some slowness to launch and UI responsiveness. Then, you changed to focus on transcoding. Shotcut does not support hardware decoding. See the [FAQ](https://shotcut.org/FAQ/) to learn more. Your ffmpeg command line uses hardware for everything - even keeping the video in the GPU memory and not transferring over the bus. Of course that is going to be several magnitudes faster. OK, fine, now try to edit your video including with filters using the ffmpeg command line. You can to some degree, but it will be very painful and very limiting on filters to keep it on the GPU. And then it will not be a cross-platform solution either. You are now comparing an all hardware-accelerated transcode with a multitrack non-linear video editor. Comparisons are not accepted as bugs, and we only accept as bugs specific, actionable, hard defects - not general improves, feature requests, or general discussion.

**Closed by ddennedy** 2021-03-18 18:45 UTC
Labels: pending
