### ISSUE TITLE
Shotcut 18.06.01: Segmentation fault

### ISSUE THREAD

**Issue by eszlari** [mltframework/shotcut#579] opened 2018-06-02 05:19 UTC
When I drag'n'drop a video file to the timeline, I get a segfault:
```
[...]
[New Thread 0x7ffef17fa700 (LWP 80)]
[New Thread 0x7ffef0ff9700 (LWP 81)]
[New Thread 0x7ffef07f8700 (LWP 82)]
[Debug  ] <MLT> [producer avformat] "/home/peter/Videos/the-predator-trailer-1_h720p.mov" checking VFR: pkt.duration 1001
[h264 @ 0x7fff2415fb40] Reinit context to 1280x544, pix_fmt: yuv420p

Thread 44 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffa77fe700 (LWP 53)]
0x0000000000000020 in ?? ()
(gdb) bt
#0  0x0000000000000020 in  ()
#1  0x00007ffff2d2a07d in QMetaObject::invokeMethod(QObject*, char const*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) (obj=
    0x4f750c0, member=<optimized out>, type=Qt::QueuedConnection, ret=..., val0=..., val1=..., val2=..., val3=..., val4=..., val5=..., val6=..., val7=..., val8=..., val9=...) at kernel/qmetaobject.cpp:1474
#2  0x00000000004d94e8 in QMetaObject::invokeMethod(QObject*, char const*, Qt::ConnectionType, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) (obj=0x4f750c0, member=0x6373b3 "onFrameDecoded", type=Qt::QueuedConnection, val0=..., val1=..., val2=..., val3=..., val4=..., val5=..., val6=..., val7=..., val8=..., val9=...)
    at /usr/include/QtCore/qobjectdefs.h:451
#3  0x00000000004edd37 in DecodeTask::run() (this=0x5060890) at /run/build/shotcut/src/widgets/avformatproducerwidget.cpp:77
#4  0x00007ffff2b41e82 in QThreadPoolThread::run() (this=0x5061360) at thread/qthreadpool.cpp:99
#5  0x00007ffff2b4708a in QThreadPrivate::start(void*) (arg=0x5061360) at thread/qthread_unix.cpp:368
#6  0x0000003131007444 in start_thread (arg=0x7fffa77fe700) at /usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:456
#7  0x00000031308e827f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
```
MLT version: git (ee1b9cbdd311a24dc724215f15dc0116725dee00)

The backtrace is from a flatpak build, but I can reproduce this with the official portable zip.

One thing I noticed: on a system with a previously installed shotcut, the segfault did not happen at first. Only after deleting `~./config/Meltytech/Shotcut.conf` it would also crash.

**Comment by ddennedy** [comment] 2018-06-02 07:09
> Only after deleting ~./config/Meltytech/Shotcut.conf it would also crash.

This was key for me to reproduce as well.

**Comment by ddennedy** [comment] 2018-06-02 07:17
Regression caused by 92dadc5f8.

**Comment by ddennedy** [comment] 2018-06-02 07:51
Fixed by reverting that change in a135d38d. Will tag a 18.06.02 version soon and new builds.

**Comment by eszlari** [comment] 2018-06-02 14:34
I have included the patch in the shotcut build on flathub: https://flathub.org/apps/details/org.shotcut.Shotcut

**Comment by qubodup** [comment] 2018-06-03 08:41
18.06.02 is nice and stable again for me https://shotcut.org/download/

**Comment by ddennedy** [comment] 2018-06-03 17:07
Thank you both for letting me know very quickly so I can limit the exposure of that flaw.

**Closed by ddennedy** 2018-06-03 17:07 UTC
Labels: reproduced by dev
