### ISSUE TITLE
Stabilize filter forrgotten

### ISSUE THREAD

**Issue by wziard** [mltframework/shotcut#218] opened 2016-04-09 08:46 UTC
Shotcut v 16.04.01

When I add the stabilize filter to a clip in the timeline and press analyze, it looks good. But as soon as the clip in the timeline loses focus, the filter is 'forgotten'. When I select it again the filter is not in the list anymore

**Comment by ddennedy** [comment] 2016-04-09 17:56
Unable to reproduce. You are doing something wrong, but I do not know what. Pay attention, in particular, to what is selected and which tab is current in the player. I suspect you are attaching the filter to the clip that is in the Source player of the tab and not the timeline clip. If you really think there is a problem, provide the steps to reproduce it - something better than you current description, obviously. Or, make a screencast of it.

**Comment by wziard** [comment] 2016-04-10 07:38
On 04/09/2016 07:56 PM, Dan Dennedy wrote:
> Unable to reproduce. You are doing something wrong, but I do not know what.
Way to go, blame the user :-)

> Pay attention, in
> particular, to what is selected and which tab is current in the player. I suspect you are attaching
> the filter to the clip that is in the Source player of the tab and not the timeline clip. If you
> really think there is a problem, provide the steps to reproduce it - something better than you
> current description, obviously. Or, make a screencast of it.
>
I'm pretty sure
I'll first create exact steps. If you then still do not believe me I'll create a screencast :-)

If i'm doing something wrong it is because the user interface is confusing.


Awesome app by the way.

I briefly considered donating for a forum membership, but 5 a month is a bit steep for me.

regards
--
martijn

**Comment by wziard** [comment] 2016-05-03 14:11
Sorry, forgot to write down the results of my research (real life interfering).

First I'll tell you my workflow.
-first I add a ton of videos from a folder to the sources list.
-then I add all of them to the timeline.
- then I select them one after another (in the timeline) to add the necessary filters.

This is what happens:

If you want to add a filter to a clip in the timeline, you need to single click the clip. Doubleclicking the clip silently switches the focus to the clip in source list (which is not at all obvious from the gui).

However, single-clicking a clip in the timeline does not show the clip in the player, because it does not change the time-position so as the user you are encouraged to double-click the clip (in the timeline) to be able to see the clip, thus switching the focus to the source list.

Proposed fixes (one of these would suffice to fix the confusion):

- When single clicking a clip in the timeline, jump the play position to that time , thus showing the clicked location in the player.
- When doubleclicking a clip, do select it in the source list (so you can find it) but do not change the focus from the timeline to the source list, so that if you then add a filter it is added to the timeline (which is where you clicked, so that's what you'd expect).
-Remember filters added to the source list and apply them before any filters added in the timeline.

If these are both impossible or very hard, at least make it more obvious where the focus lies as the current system can be very confusing.

success with your awesome app.

**Comment by ddennedy** [comment] 2016-05-03 14:31
Seeking upon select is not performed by design (it used to do that and was changed in response to a bug report that I agreed with). The difference between single click and double click is by design. There is no "source list" and Playlist is not required to use the Timeline. When using the Playlist, there is no one-to-one correspondence between something in the Playlist and something in the Timeline. They both contain possibly differing sub-clips of some source asset. Double-click - like most things in desktop - is a shortcut for Open, and opening an item on the Timeline opens a copy in the Source player for you to use to create another shot. Maybe that is the biggest gotcha in all of this. Focus on the timeline is extremely obvious - the clip's shading is inverted AND there is a red outline. How is that not obvious?

**Comment by ddennedy** [comment] 2016-05-03 14:49
I will remove double-click from the Timeline since a lot people struggle with the distinction between single and double. That will require a more deliberate action for something less seldom used - arguably more advanced. I will also relabel the timeline clip context menu from "Open As Clip" to "Open Copy" or similar.

**Comment by wziard** [comment] 2016-05-04 08:17
> there is no source  list
Ok, maybe I used the wrong name. I mean the list of source videos obviously, Playlist/ sourle list whatever.

But I can understand attaching filters to that list would be a problem programmatically if you did not design it with that in mind.

>Focus on the timeline is extremely obvious - the clip's shading is inverted AND there is a red outline. How is that not obvious?
If I doubleclick an item in the timeline. It still looks like it has focus (red outline, inverted shading). But any filters added are lost, because it's not actually the clip in the timeline which has focus anymore.

Now that I look at it, it's not really the Playlist that has focus either. I'm a bit confused as to the usecase of opening a copy in the player. Why would you want that? (I don't mean this as a rethorical question I really don't understand.)

What it looks like to an unsuspecting user is this: single click- select clip, double click -  select clip and seek. 

> Double-click - like most things in desktop - is a shortcut for Open.
In any other video editor I used doubleclicking on a timeline clip opened the properties of that clip in the timeline. 

I really like the workflow 'dump all clips in timeline, then drag them and add filters'. Shotcut is the only app I have found which comfortably allows this workflow. Having an easy way to select a clip in the timeline and open that clip in the player it would be very useful IMHO.



The focus on the timeline is maybe quite obvious, but if you doubleclick on a clip, the focus on the

**Comment by wziard** [comment] 2016-05-04 08:22
Just plainly removing doubleclick would be an "improvement" I guess. It would at least clear up the confusion.

I understand using doubleclick for select+seek(*) seems not logical to you, after all you designed it the way it currently is. And from a code perspective (I'm a programmer myself) it is probably the logical thing to do. But try to once use Shotcut as if you did not know how it worked internally. I think you'd expect that to happen as well.


(*) In most other apps it's not actually 'select+seek' but it opens the properties of that specific clip as it is  used in the timeline, with the in and out point marked on the player window and the filters applied.

**Comment by ddennedy** [comment] 2016-05-04 17:06
> If I doubleclick an item in the timeline. It still looks like it has focus (red outline, inverted shading).

Properties and Filters generally show and affect what is selected, but "selection" actually also depends upon which tab is selected on the player. The item selected on the Timeline only matters when the player tab is also Program. If the player tab is Source, then Properties and Filters shows/affects what is loaded in the source player. I once experimented with adding a red outline around the player when the Source tab is selected (and simultaneously removing the selection outline in Timeline), but that was too visually distracting. I will make an experiment to give the scrub/trim bar a red outline instead.

>  I'm a bit confused as to the usecase of opening a copy in the player. Why would you want that?

Why do people copy things to the clipboard? Think of the source player as a clipboard-with-viewer. Some examples: trim out another shot from the same source file to add to the timeline or playlist, modify the copy and overwrite the original, add duplicates of the a shot to timeline (e.g. repeating an image), export/transcode just that clip without closing or restarting the app.

> (double-click) opens it in the player with the in and out point marked and the filters applied.

What happens when you trim? It automatically affects the timeline? What if you try to extend where there is another clip in the way? Does it overwrite/ripple or limit your range? I do not like the unintended destruction or superficial/confusing limitations this might cause. With the current design, you can choose to open a copy in the player, re-trim it, and then insert or overwrite on the timeline just like you would with a new clip. Trimming something on the timeline but outside the timeline feels wrong to me - too disconnected. Either trim something beforehand in the source player, trim something directly on the timeline, or trim a copy in the source player that you will use to replace the timeline item.

With that said, it is a bad idea in UIs in general to have very different behaviors for single click and double-click on an object, which is the situation today. How many times have you watched people double-click when only single-click was needed? However, changing double-click in Shotcut's timline to select+seek is both useful and not dangerously confusing.

**Closed** 2016-05-05 05:43 UTC
