### ISSUE TITLE
Subsequent "Export Frame" actions open file dialog multiple times

### ISSUE THREAD

**Issue by Gizemquea** [mltframework/shotcut#1053] opened 2021-03-11 14:23 UTC
Shotcut 21.02.27 Windows 10 64bit - also broken in recent versions although I remember that still working at least in mid 2020

Steps to reproduce:
1.) Open an arbitrary project
2.) Set playhead to an arbitrary frame
3.) Ctrl+Shift+E
4.) Enter file name and save
5.) Repeat at step 3

The new file will be saved alright, **but the file dialog opens again afterwards** - cancel works as expected. The number of times the file dialog pops up depends on the number of subsequent "Export Frame" actions.

**Comment by ddennedy** [comment] 2021-03-11 16:20
Duplicate of #1051

**Closed by ddennedy** 2021-03-11 16:20 UTC
Labels: duplicate
