### ISSUE TITLE
filters missing in 16.04 with Linuxmint 17.3

### ISSUE THREAD

**Issue by NanniManfrin** [mltframework/shotcut#219] opened 2016-04-09 19:54 UTC
generally this new version of shotcut is more stable and less crashy. but the filters menu is missing. i'm running a 64-bit asus K52N with linuxmint 17.3. is there anything i can do to get the filters back? thanks a million!

**Comment by ddennedy** [comment] 2016-04-09 20:04
Nothing changed in this area from the previous version, and it works fine on many machines including mine. Sorry, and I do not expect this to go anywhere, but I will leave it open for a while to see if someone else has a problem. Maybe you want to remove your settings because it might related to your window panels arrangement.

**Comment by NanniManfrin** [comment] 2016-04-10 10:34
OK thanks for such a quick response! i did check everything i could do with my current layout and the filters "plus" button just wasn't there. i did like you said and refreshed the standard layout and that fixed it. thanks again

**Comment by ddennedy** [comment] 2016-04-10 20:43
Thanks for the update. I am closing this because it is not clear how to reproduce it, and there is a good chance it is not something in our code but rather a library or driver.

**Closed by ddennedy** 2016-04-10 20:43 UTC
