### ISSUE TITLE
When source clip changes shotcut sometimes shows clip as black

### ISSUE THREAD

**Issue by OpusMcN** [mltframework/shotcut#235] opened 2016-05-01 00:03 UTC
When the source video of a playlist item is changed outside shotcut (but to same video format/duration, i.e. re-rendered from other software) sometimes shotcut will show that video as white (with correct soundtrack) when viewed as a clip and black (again with correct soundtrack) when viewed on the timeline.     For me, I'm rerendering panoramic videos in an external program.   The video codec/resolution of the playlist item shows as blank and 0x0 resolution.

The problem can appear to be corrected by displaying properties of the clip and hitting reset, this will populate the correct codec/resolution (changing from blank codec and 0x0 resolution) and the clip will display correctly.  However this doesn't "stick" and the properties will be reset to empty when changing to another clip (or timeline) and back again.

To fix it you need to remove the clip from the time line and playlist, re-add it to the playlist and re-insert into the timeline.

**Comment by ddennedy** [comment] 2016-05-01 00:25
I do not know what "re-rendered from other software" exactly entails, which makes it uneasy to reproduce and debug. Therefore, do not expect this bug to get much action. Look at the MLT XML. There is some important information about the clips stored in there such as length, audio_index, and video_index (stream index within container) but not much else. Obviously, you cannot change the index values between re-rendering. The length is not as sensitive. Based on that, what do you think is wrong?

> The problem can be corrected by displaying properties of the clip and hitting reset, this will populate the correct codec/resolution (changing from blank codec and 0x0 resolution).

That part is a duplicate of #231.

**Comment by OpusMcN** [comment] 2016-05-01 00:42
Hi Dan,
Arrg...  The stream indices are getting changed as I re-render.. Good call.   I'm using AutoPano Video to take a bunch of video files and render a single panoramic video from those, then editing the multiple panoramic videos in shotcut.    AutoPano Video seems to be the swapping the indices of the audio and video streams at random every time it renders, so the ones that change don't get loaded correctly.

So not a Shotcut bug, sorry to hassle you with this.  Thanks!

**Closed** 2016-05-01 00:42 UTC
