### ISSUE TITLE
Error stabilizing the video int the version 19.06

### ISSUE THREAD

**Issue by Gilraiser** [mltframework/shotcut#754] opened 2019-07-06 23:04 UTC
Operating System: Archlinux 64amd

Software Version: Shotcut 19.06

When exporting a project with the stabilization filter, the video shows small points and white lines. Attached some screenshots. This has been happening since version 19.02.
![vlcsnap-00003](https://user-images.githubusercontent.com/45057390/60761871-8fdf9f80-a017-11e9-87f1-75973effcd4c.png)
![vlcsnap-00002](https://user-images.githubusercontent.com/45057390/60761872-8fdf9f80-a017-11e9-92d6-be1d0371dcf1.png)

**Comment by Gilraiser** [comment] 2019-07-06 23:06
Thank you very much.

**Comment by ddennedy** [comment] 2019-07-06 23:18
Are you using a build provided by us through shotcut.org/github/fosshub?

**Comment by Gilraiser** [comment] 2019-07-06 23:26
yes ddennedy, downloaded from the official web site.

**Comment by ddennedy** [comment] 2019-07-06 23:27
I am not reproducing it using our builds on Linux, but it might depend on many factors. For example:

- in the source clip properties, does color range = full?
- are you exporting from Source (clip only) or putting in timeline?
- what export settings do you change?
- are you using hardware encoder?

We have not changed anything directly related to Stabilize filter in a long while, and the upstream library has only minor changes in the past year:
https://github.com/georgmartius/vid.stab/commits/master

**Comment by Gilraiser** [comment] 2019-07-06 23:34
Exporto desde la línea de tiempo. El único filtro que coloco al video es el de estabilización. No estoy usando codificación por hardware. En los ajustes de exportación coloco la opción "VBR basado en calidad" al 100%. En rango de color se exportó con difusión limitada (mpeg).

**Comment by Gilraiser** [comment] 2019-07-06 23:35
Tanto la versión de appimage, portable para linux y la que está en los canales oficiales de software del sistema operativo Archlinux sucede el mismo problema. Espero sea de ayuda.

**Comment by ddennedy** [comment] 2019-07-06 23:35
Translation: 
> Exported from the timeline. The only filter that placed the video is stabilizing. I'm not using hardware encoding. In the export settings I put the "quality-based VBR" option to 100%. In color range it was exported with limited diffusion (mpeg).

Are you using multiple video tracks? If so, is the video with stabilization on the bottom video track?

**Comment by ddennedy** [comment] 2019-07-06 23:37
Upload your project file, please. Rename the .mlt to .txt and attach it to a reply.

**Comment by Gilraiser** [comment] 2019-07-06 23:37
Yes, exactly.

**Comment by Gilraiser** [comment] 2019-07-06 23:38
Ok, thank you very much ddennedy.

**Comment by Gilraiser** [comment] 2019-07-06 23:39
This is the project file: 
[Forcha-Project.txt](https://github.com/mltframework/shotcut/files/3365122/Forcha-Project.txt)

**Comment by ddennedy** [comment] 2019-07-07 00:48
I see in your project that you changed the **Modo de fusión** (Blend mode in English) of track V5 to "Sobreexponer" ("Dodge" in English). Did you intend to do that? Does the problem go away if you change it to "Encima" ("Over" in English)?

I have not reproduced a problem with the Stabilize filter, but dodge blending can cause this effect because it easily creates highlights (a side effect of its design). For my testing, I only see white spots from dodge blending in the areas where there is video on V5 and not in the blank spots of that track. Please test after changing V5 > Propiedades > Modo de fusión = Encima. If the problem still exists, can you reproduce it with a new, simple project that has only Stabilize on a single clip?

**Comment by Gilraiser** [comment] 2019-07-07 01:04
Maybe that's it, I'll try. Change the mixing method to achieve an effect but only in a few parts. Thank you. I will try and let you know if the problem persists.

**Comment by Gilraiser** [comment] 2019-07-07 22:53
Good afternoon, cordial greeting. using only one track in the timeline with the stabilization filter the same error occurs with version 19.06. This error occurs when the "Limited diffusion (MPEG)" color range is selected in the properties. When "Complete" is chosen, this does not happen. I attached the file where I did the test.
[stab.txt](https://github.com/mltframework/shotcut/files/3366183/stab.txt)

**Comment by Gilraiser** [comment] 2019-07-07 22:54
I hope it's useful

**Comment by ddennedy** [comment] 2019-07-07 23:06
Can you please send the output for Properties > menu > More Info.. . for VID_20190511_120002.mp4 ?
If the file is really full range and you override it to limited, then you are introducing a problem. The range property should not be used to adjust levels; it is an over-ride for improperly signaled or undetected range attribute of files.

**Comment by Gilraiser** [comment] 2019-07-07 23:12
Hi, thanks for answering. This is the output:

# ffprobe output


[streams.stream.0]
index=0
codec_name=h264
codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
profile=Constrained Baseline
codec_type=video
codec_time_base=832157/39780000
codec_tag_string=avc1
codec_tag=0x31637661
width=1280
height=720
coded_width=1280
coded_height=720
has_b_frames=0
sample_aspect_ratio=1:1
display_aspect_ratio=16:9
pix_fmt=yuv420p
level=31
color_range=unknown
color_space=unknown
color_transfer=unknown
color_primaries=unknown
chroma_location=left
field_order=unknown
timecode=N/A
refs=1
is_avc=true
nal_length_size=4
id=N/A
r_frame_rate=287/12
avg_frame_rate=19890000/832157
time_base=1/90000
start_pts=0
start_time=0:00:00.000000
duration_ts=1664314
duration=0:00:18.492378
bit_rate=6.871423 Mbit/s
max_bit_rate=N/A
bits_per_raw_sample=8
nb_frames=442
nb_read_frames=N/A
nb_read_packets=N/A

[streams.stream.0.disposition]
default=1
dub=0
original=0
comment=0
lyrics=0
karaoke=0
forced=0
hearing_impaired=0
visual_impaired=0
clean_effects=0
attached_pic=0
timed_thumbnails=0

[streams.stream.0.tags]
creation_time=2019-05-11T17:00:55.000000Z
language=eng
handler_name=VideoHandle

[streams.stream.1]
index=1
codec_name=aac
codec_long_name=AAC (Advanced Audio Coding)
profile=LC
codec_type=audio
codec_time_base=1/48000
codec_tag_string=mp4a
codec_tag=0x6134706d
sample_fmt=fltp
sample_rate=48 KHz
channels=2
channel_layout=stereo
bits_per_sample=0
id=N/A
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/48000
start_pts=0
start_time=0:00:00.000000
duration_ts=894478
duration=0:00:18.634958
bit_rate=127.990000 Kbit/s
max_bit_rate=12.200000 Kbit/s
bits_per_raw_sample=N/A
nb_frames=873
nb_read_frames=N/A
nb_read_packets=N/A

[streams.stream.1.disposition]
default=1
dub=0
original=0
comment=0
lyrics=0
karaoke=0
forced=0
hearing_impaired=0
visual_impaired=0
clean_effects=0
attached_pic=0
timed_thumbnails=0

[streams.stream.1.tags]
creation_time=2019-05-11T17:00:55.000000Z
language=eng
handler_name=SoundHandle

[format]
filename=/mnt/Win7/CREATOR-X/FORCHAPORUBEM/VID_20190511_120035.mp4
nb_streams=2
nb_programs=0
format_name=mov,mp4,m4a,3gp,3g2,mj2
format_long_name=QuickTime / MOV
start_time=0:00:00.000000
duration=0:00:18.624000
size=15.438842 Mibyte
bit_rate=6.953951 Mbit/s
probe_score=100

[format.tags]
major_brand=mp42
minor_version=0
compatible_brands=isommp42
creation_time=2019-05-11T17:00:55.000000Z
Completed successfully in 00:00:00

**Comment by Gilraiser** [comment] 2019-07-07 23:17
I'm sorry, I did the trial with another file. Here is the output with the file VID_20190511_120002.mp4:
# ffprobe output


[streams.stream.0]
index=0
codec_name=h264
codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
profile=Constrained Baseline
codec_type=video
codec_time_base=112433/3360000
codec_tag_string=avc1
codec_tag=0x31637661
width=1280
height=720
coded_width=1280
coded_height=720
has_b_frames=0
sample_aspect_ratio=1:1
display_aspect_ratio=16:9
pix_fmt=yuv420p
level=31
color_range=unknown
color_space=unknown
color_transfer=unknown
color_primaries=unknown
chroma_location=left
field_order=unknown
timecode=N/A
refs=1
is_avc=true
nal_length_size=4
id=N/A
r_frame_rate=179/12
avg_frame_rate=1680000/112433
time_base=1/90000
start_pts=0
start_time=0:00:00.000000
duration_ts=337299
duration=0:00:03.747767
bit_rate=7.201970 Mbit/s
max_bit_rate=N/A
bits_per_raw_sample=8
nb_frames=56
nb_read_frames=N/A
nb_read_packets=N/A

[streams.stream.0.disposition]
default=1
dub=0
original=0
comment=0
lyrics=0
karaoke=0
forced=0
hearing_impaired=0
visual_impaired=0
clean_effects=0
attached_pic=0
timed_thumbnails=0

[streams.stream.0.tags]
creation_time=2019-05-11T17:00:07.000000Z
language=eng
handler_name=VideoHandle

[streams.stream.1]
index=1
codec_name=aac
codec_long_name=AAC (Advanced Audio Coding)
profile=LC
codec_type=audio
codec_time_base=1/48000
codec_tag_string=mp4a
codec_tag=0x6134706d
sample_fmt=fltp
sample_rate=48 KHz
channels=2
channel_layout=stereo
bits_per_sample=0
id=N/A
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/48000
start_pts=0
start_time=0:00:00.000000
duration_ts=187607
duration=0:00:03.908479
bit_rate=125.908000 Kbit/s
max_bit_rate=12.200000 Kbit/s
bits_per_raw_sample=N/A
nb_frames=180
nb_read_frames=N/A
nb_read_packets=N/A

[streams.stream.1.disposition]
default=1
dub=0
original=0
comment=0
lyrics=0
karaoke=0
forced=0
hearing_impaired=0
visual_impaired=0
clean_effects=0
attached_pic=0
timed_thumbnails=0

[streams.stream.1.tags]
creation_time=2019-05-11T17:00:07.000000Z
language=eng
handler_name=SoundHandle

[format]
filename=/mnt/Win7/CREATOR-X/FORCHAPORUBEM/VID_20190511_120002.mp4
nb_streams=2
nb_programs=0
format_name=mov,mp4,m4a,3gp,3g2,mj2
format_long_name=QuickTime / MOV
start_time=0:00:00.000000
duration=0:00:03.840000
size=3.278353 Mibyte
bit_rate=7.161670 Mbit/s
probe_score=100

[format.tags]
major_brand=mp42
minor_version=0
compatible_brands=isommp42
creation_time=2019-05-11T17:00:07.000000Z
Completed successfully in 00:00:00

**Comment by ddennedy** [comment] 2019-07-07 23:52
> pix_fmt=yuv420p
> color_range=unknown

There could also be a problem if the file is really full (complete) range but not signaled as such. It is typical for H.264 full range to have pix_fmt yuv**j**420p (notice the 'j' in there). You can see this in the Video Waveform scope as parts of the waveform exceed the 100 line. I have such a file, but I did not reproduce the problem. Does the clip look full range in the scope? You can also use the histogram scope and look at minimum and maximum for the luma over several frames.

**Comment by Gilraiser** [comment] 2019-07-10 20:26
Hello, sorry for the delay in answering. This is the histogram and the video wave. The luma levels do not seem to vary.
![captura](https://user-images.githubusercontent.com/45057390/61002410-1ac9de00-a327-11e9-8e4a-4ab23439e380.png)

**Comment by ddennedy** [comment] 2019-07-11 18:00
This clip is obviously full range.

**Comment by ddennedy** [comment] 2019-07-11 21:39
Even though you can fix this by correcting the range, I want to try to reproduce it. But I have not been able to with my clips. Can you please upload VID_20190511_120002.mp4 to [this discreet location](https://shotcut.org/notes/support-upload/)?

**Comment by Gilraiser** [comment] 2019-07-12 15:00
Ok, the file has been uploaded Thank you very much for developing this software, it is a good program and advanced a lot in a short time.

**Comment by ddennedy** [comment] 2019-07-13 16:44
I got the clip, and I could not reproduce the problem on macOS. I do not have access to my Linux workstation today, and I will test it again in a couple of days. However, this is all the same code, and I do not expect anything different. How are you viewing the export result? I looked at in Shotcut, Quicktime Player, and VLC.

**Comment by ddennedy** [comment] 2019-07-15 22:29
I tested this again on Linux (Ubuntu 18.04) using the portable archive version 19.06.15, and I still do not reproduce it. I used your video file, your project file, and regenerated the stab.stab file. I even used a numeric locale that uses a comma for the decimal point to get closer to your setup. I viewed the export result in both Shotcut and VLC. I still wonder how you are playing it to make your screenshots above. I have little choice but to close this as unable to reproduce and because the problem goes away when color range is changed to full and the clip is clearly full range.

**Comment by Gilraiser** [comment] 2019-07-17 04:49
Hi. I tried the export result in SMplayer, Mplayer, Mpv player and in VLC. The same error appears in all of these players. Screenshots I made with the VLC. When I return to open the file that I export in Shotcut, it is also seen with this same error of lines and white points. I hope to be helpful. Thank you very much for this excellent software.

**Comment by ddennedy** [comment] 2019-07-22 21:00
I was reviewing something else in the vid.stab library when I came across this bug fix that is directly related to this issue: https://github.com/georgmartius/vid.stab/commit/7008479ed6e8bd129825d580b0416c987179b9c0

Shotcut builds are using the head of git master for this library; so anything after v18.05 of Shotcut will include it. However, this fix was made **after** the latest vid.stab release; so, it is very likely that the library in a distribution package does not have it. Shotcut bundles its own build of this library in the builds we provide, but this can be circumvented on Linux by not using the launcher script in the portable archive and instead directly running bin/shotcut. I think the only way to circumvent it with the AppImage is by extracting it and running the shotcut binary. Otherwise, I think only a LD_PRELOAD would be a way to circumvent, or if an environment variable is set to redirect MLT to load modules from somewhere other than the app bundle.

Here is another commit around the same issue: https://github.com/georgmartius/vid.stab/commit/eeb9b81f8e55d7a573e31b4208d2330d0862daa2

**Comment by Gilraiser** [comment] 2019-07-25 15:19
Great, the important thing is that the origin of the problem is identified. I think the stabilization filter is widely used, since people tend to generate many videos from their mobile phone by holding it with their hands. Thank you.

**Comment by Gilraiser** [comment] 2019-07-25 15:21
Great, the important thing is that the origin of the problem is identified. I think the stabilization filter is widely used, since people tend to generate many videos from their mobile phone by holding it with their hands. Thank you Ddennedy.

**Closed** 2019-07-26 02:44 UTC
Labels: pending
