### ISSUE TITLE
Crash when resizing a block

### ISSUE THREAD

**Issue by regs01** [mltframework/shotcut#191] opened 2016-02-08 17:35 UTC
Getting crash every time i try to resized a cut block. 16.02. Tried both Intel and Nvidia. Software is green. Also often crash when trying to select a track. Windows 8.1.

**Comment by ddennedy** [comment] 2016-02-08 20:32
I am not able to reproduce this problem. I will leave this open for a while in case we figure out what is going on, but will close it after a few weeks if not.

**Comment by ddennedy** [comment] 2016-02-08 21:20
A few questions that can help, focusing only on the timeline clip trimming:
1. Is ripple mode on? There is a toggle button on the timeline toolbar with circles that governs this.
2. Does it prevent or reduce crashing if audio waveforms are disabled in the timeline menu?
3. Does it prevent or reduce crashing if video thumbnails are disabled in the timeline menu?

**Comment by Alexander01998** [comment] 2016-03-01 19:02
I am experiencing the same problem and I can answer the questions that you asked:
1. Ripple mode is off (I don't even know what that does), but the button to enable it is there.
2. It's hard to tell. It might have reduced the crash a bit, but it definitely still occurs.
3. Same result as 2.

**Comment by ddennedy** [comment] 2016-03-13 00:47
Expired without enough information.

**Closed by ddennedy** 2016-03-13 00:47 UTC
Labels: crash, pending, Windows

**Comment by regs01** [comment] 2016-04-01 13:54
That was Win 8.1 notebook that just used once. But getting no crashes on Win 10 PC.

**Comment by ddennedy** [comment] 2016-04-01 16:47
This was recently fixed in duplicate report #214. A new version 16.04 containing this fix is due within 24 hours!
