### ISSUE TITLE
External monitor bug

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#954] opened 2020-11-13 09:36 UTC
Shotcut version 20.10.31

When you trying to move back video window in main window of Shotcut GUI redraw completely dies. Although hints of elements are shown. Only restart of Shotcut can help.

[Shotcut external monitor bug](https://youtu.be/wnlxmfUrwVs)

**Comment by ddennedy** [comment] 2020-11-13 20:11
duplicate of #757

**Closed by ddennedy** 2020-11-13 20:11 UTC
