### ISSUE TITLE
Drag and dropping files crashes the program 

### ISSUE THREAD

**Issue by MaccaAlbarn** [mltframework/shotcut#1396] opened 2023-01-06 01:37 UTC
First of all, thanks to the shotcut team for making a very powerful video editing software!

now, i have a problem with this program, every time i drag a file, either a video or an image to the timeline, the app crashes, i'm currently running a Wayland/Sway, i tried running shotcut on dwm (and gnome on xorg) and everything worked just fine, it's a problem with either wayland, wlroots or something?

`OS : Nobara 37, fully updated` 
`Shotcut Version : 22.12.21`

**Comment by ddennedy** [comment] 2023-01-06 01:43
This is a frequently reported duplicate of #1218. You should search before posting. It appears to be a Qt problem, and we are working on a major upgrade to Qt 6, but we do not if it fixes it because no developer has reproduced it.

**Closed by ddennedy** 2023-01-06 01:43 UTC
