### ISSUE TITLE
Text gets dropped on some frames intermittently.

### ISSUE THREAD

**Issue by bmatherly** [mltframework/shotcut#686] opened 2018-12-30 22:14 UTC
Original Report:
https://forum.shotcut.org/t/text-flickering-to-left-after-export/8910

@ddennedy I might need your help with this one. I can only reproduce this problem on Windows using the released package. Also, I only reproduce the problem on export. I do not see the problem in the preview window nor in Linux under any circumstances. I think there might be an intermittent race condition.

To reproduce:
1) Set video mode to 1080p30 (I do not know if this is necessary, but it is what I do)
2) Open a clip
3) Add the text filter (the default settings put a timecode on the bottom of the image)
4) Export using default settings
5) Open the exported file and watch.
The text will intermittently flicker. If you step by frames in Shotcut, you can see that every few seconds a video frame will not have the text at all.

I downloaded the 18.12.23 Windows SDK. When I run shotcut from QT creator I am not able to reproduce the flickering on export.

I added a debug message here:
https://github.com/mltframework/mlt/blob/master/src/modules/qt/filter_qtext.cpp#L289
But as I mentioned, I never see the problem in the preview window. I haven't taken the time to figure out how to compile qmelt. But as I mentioned, the problem does not occur when I run from QT.

Can you try to reproduce the problem on some of your systems? Hopefully, between the two of us, we can find an environment that reproduces the problem more reliably.

**Comment by ddennedy** [comment] 2019-01-02 00:35
So far I have not reproduced it. I do not think you need to re-compile qmelt. You can easily try to build MLT from the SDK using the same flags (minus --enable-debug) as the release build. I run `tail -2 config.log` and then re-run configure by converting the paths to my locations (C:\Projects\Shotcut). Then, you can run make distclean, followed by reconfigure, make -j all, make install. If you can reproduce with the SDK shotcut.exe after that then you can tinker with placement of mlt_service_lock()/mlt_service_unlock() calls placed in qtext to see if the problem goes away. I will continue to try to reproduce it off-and-on. (I also tried on macOS with no reproduction.)

**Comment by ddennedy** [comment] 2019-01-02 23:44
I reproduced the text alignment bug here, and it is probably the same race condition:
https://forum.shotcut.org/t/text-alignment-after-rendering/8963/

A big problem is that qtext is inspecting filter properties inside its get_image routine while the dynamictext filter is setting them in its process routine. There is a technique to create a unique properties object and push that on the image stack that I will lookup and try to employ.

**Comment by ddennedy** [comment] 2019-01-03 00:57
I think this is fixed in https://github.com/mltframework/mlt/commit/0e2044f61cb8bb67e8452fd0fb324938c19b027d
At least what I could reproduce with horizontal alignment was fixed. You can test a release build tomorrow for the text dropouts.

**Comment by bmatherly** [comment] 2019-01-03 02:51
I see what you did there. I think there could still be a microscopic probability of a race condition if the thread context changes after the function returns but before the pointer is dereferenced. I will try it tomorrow and report back.

If we still need more protection, I think we could put a lock around everything except for drawPath since that is where all the heavy lifting takes place.
https://github.com/mltframework/mlt/blob/master/src/modules/qt/filter_qtext.cpp#L225

**Comment by ddennedy** [comment] 2019-01-03 02:56
I already put a big lock around the majority of the body of qtext get_image, but it did not work. Some lock in there may need to be combined with a lock on the text filter inside dynamictext's process.

**Comment by ddennedy** [comment] 2019-01-03 22:57
I was not able to get service locks to work, but I did get mlt_frame_unique_properties() to work. Please review the following branch:
https://github.com/mltframework/mlt/commit/2183778b2a296fd2ae2f7642da87161736cb07af

I removed the encoding property because the MLT convention is that all strings are UTF-8 and should be converted to that before setting or converted from that after getting.

**Comment by bmatherly** [comment] 2019-01-04 02:05
How did I never know about mlt_frame_unique_properties()? This is the superior solution. There are probably many other services that would benefit from using this technique. In fact, we should almost require it and forbid services from accessing properties directly from their image/audio callbacks.

**Comment by bmatherly** [comment] 2019-01-04 02:16
I will test tomorrow after the nightly build. But I feel confident this will resolve the problem.

**Comment by ddennedy** [comment] 2019-01-04 02:51
I tested it by reverting the previous commit where I can easily reproduce it.

As for applying this to other filters, yes it is a good way to remove locks. I think I should add a mlt_frame_get_unique_properties().

**Comment by bmatherly** [comment] 2019-01-04 02:57
> I think I should add a mlt_frame_get_unique_properties().

I agree. I assume that would return NULL if the properties do not exist.

**Closed** 2019-01-04 23:50 UTC

**Comment by ddennedy** [comment] 2019-01-05 21:47
64-bit Windows build is fixed now if you want to test this.

**Comment by bmatherly** [comment] 2019-01-06 02:18
Confirmed. No more problems.
