### ISSUE TITLE
ShotCut (binary 32 bit) Segmentation Fault on ArchLinux.

### ISSUE THREAD

**Issue by firew4lker** [mltframework/shotcut#59] opened 2015-04-05 07:01 UTC
As the title says. From GDB:

Program received signal SIGSEGV, Segmentation fault.
0xb4031d14 in QOpenGLContext::shareGroup() const () from /opt/shotcut/lib/libQt5Gui.so.5

Same with 150303 and 150401 versions.

My system:

glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Sandybridge Mobile x86/MMX/SSE2
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.5.2
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.5.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 10.5.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

GPU: Intel HD3000 (i915).

00:02.0 VGA compatible controller [0300]: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller [8086:0116] (rev 09) (prog-if 00 [VGA controller])
        Subsystem: Dell Device [1028:051b]
        Flags: bus master, fast devsel, latency 0, IRQ 24
        Memory at f0000000 (64-bit, non-prefetchable) [size=4M]
        Memory at e0000000 (64-bit, prefetchable) [size=256M]
        I/O ports at 3000 [size=64]
        Expansion ROM at <unassigned> [disabled]
        Capabilities: <access denied>
        Kernel driver in use: i915
        Kernel modules: i915

Any hints?

**Comment by firew4lker** [comment] 2015-04-05 15:11
Launch script:
#!/bin/sh
# Set up environment
# Run this instead of trying to run bin/shotcut. It runs shotcut with the correct environment.
CURRENT_DIR=$(readlink -f "$0")
INSTALL_DIR=$(dirname "$CURRENT_DIR")
export LD_LIBRARY_PATH="$INSTALL_DIR/lib":"$INSTALL_DIR/lib/frei0r-1":$LD_LIBRARY_PATH
export MLT_REPOSITORY="$INSTALL_DIR/lib/mlt"
export MLT_DATA="$INSTALL_DIR/share/mlt"
export MLT_PROFILES_PATH="$INSTALL_DIR/share/mlt/profiles"
export FREI0R_PATH="$INSTALL_DIR/lib/frei0r-1"
export MLT_MOVIT_PATH="$INSTALL_DIR/share/movit"
export QT_PLUGIN_PATH="$INSTALL_DIR/lib/qt5"
export QML2_IMPORT_PATH="$INSTALL_DIR/lib/qml"
"$INSTALL_DIR/bin/shotcut" "$@"


GDB backtrace:
#0  0xb4031d14 in QOpenGLContext::shareGroup() const () from /opt/shotcut/lib/libQt5Gui.so.5
#1  0xb428fefe in ?? () from /opt/shotcut/lib/libQt5Gui.so.5
#2  0xb429003a in QOpenGLFunctions::initializeOpenGLFunctions() () from /opt/shotcut/lib/libQt5Gui.so.5
#3  0xb743de0c in QSGRenderer::QSGRenderer(QSGRenderContext*) () from /opt/shotcut/lib/libQt5Quick.so.5
#4  0xb742824f in QSGBatchRenderer::Renderer::Renderer(QSGRenderContext*) () from /opt/shotcut/lib/libQt5Quick.so.5
#5  0xb744f954 in QSGRenderContext::createRenderer() () from /opt/shotcut/lib/libQt5Quick.so.5
#6  0xb7495921 in QQuickWindowPrivate::syncSceneGraph() () from /opt/shotcut/lib/libQt5Quick.so.5
#7  0xb746cbd6 in ?? () from /opt/shotcut/lib/libQt5Quick.so.5
#8  0xb746d58d in ?? () from /opt/shotcut/lib/libQt5Quick.so.5
#9  0xb749027c in QQuickWindow::exposeEvent(QExposeEvent*) () from /opt/shotcut/lib/libQt5Quick.so.5
#10 0xb40017cc in QWindow::event(QEvent*) () from /opt/shotcut/lib/libQt5Gui.so.5
#11 0xb749b53c in QQuickWindow::event(QEvent*) () from /opt/shotcut/lib/libQt5Quick.so.5
#12 0xb46c4bf4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/shotcut/lib/libQt5Widgets.so.5
#13 0xb46c89a0 in QApplication::notify(QObject*, QEvent*) () from /opt/shotcut/lib/libQt5Widgets.so.5
#14 0xb3cf087e in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/shotcut/lib/libQt5Core.so.5
#15 0xb3ff2a6b in QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) () from /opt/shotcut/lib/libQt5Gui.so.5
#16 0xb3ffc2b0 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /opt/shotcut/lib/libQt5Gui.so.5
#17 0xb3fdfdf6 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/shotcut/lib/libQt5Gui.so.5
#18 0xb146a331 in ?? () from /opt/shotcut/lib/qt5/platforms/libqxcb.so
#19 0xb773c704 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#20 0xb773ca29 in ?? () from /usr/lib/libglib-2.0.so.0
#21 0xb773caf6 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#22 0xb3d47a98 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/shotcut/lib/libQt5Core.so.5
#23 0xb146a586 in ?? () from /opt/shotcut/lib/qt5/platforms/libqxcb.so
#24 0xb3cf0cd5 in QCoreApplication::processEvents(QFlags<QEventLoop::ProcessEventsFlag>, int) () from /opt/shotcut/lib/libQt5Core.so.5
#25 0xb489b923 in QSplashScreen::finish(QWidget*) () from /opt/shotcut/lib/libQt5Widgets.so.5
#26 0x0807f51c in ?? ()
#27 0xb36ac64e in __libc_start_main () from /usr/lib/libc.so.6
#28 0x0807fab1 in ?? ()

**Comment by metellius** [comment] 2015-04-05 15:32
I had this exact crash/backtrace when I tried to compile and run shotcut against my system qt libraries (5.3.x) instead of the included 5.2.0 ones.

**Comment by firew4lker** [comment] 2015-04-05 15:49
As I can see shotcut use the Qt libs it came with. Not the ones in my system. Maybe an Intel OpenGL driver compatibility issue?

**Comment by ddennedy** [comment] 2015-04-05 15:50
This is somewhat a duplicate of #54 - some OpenGL compatibility bug.

**Comment by firew4lker** [comment] 2015-04-05 15:55
So, for the moment it works only with nvidia cards? Is something that can be "easily" addressed?

**Comment by ddennedy** [comment] 2015-04-05 16:17
It works with more than nvidia. I can successfully use it in a virtual machine as well as with AMD open source driver, but I do not have a bunch of machines in lab with a testing staff, and Shotcut does not collect usage stats on its users. There are several thousand Linux downloads per month, and quite likely the successful users are not all on nvidia. If there was an easy fix, it would be done, obviously. A patch is welcome. We are working on a change to allow us to upgrade to a newer version of Qt in the near future, and I hope that helps.

**Comment by firew4lker** [comment] 2015-04-05 16:21
Is there anything /i can do to help you with debuging?

**Comment by firew4lker** [comment] 2015-05-03 08:01
150502 seems to work ok now.  Now I can try Shotcut!

**Comment by ddennedy** [comment] 2015-05-03 15:55
Thank you for returning to this. I think commit eff1bb6e585494df86dd487e14e3cd90d6040741 fixed it for you.

**Closed by ddennedy** 2015-05-03 15:55 UTC
Labels: crash, duplicate, Linux
