### ISSUE TITLE
Exporting over existing playlist file warns but erases anyway

### ISSUE THREAD

**Issue by veganaize** [mltframework/shotcut#903] opened 2020-08-25 23:18 UTC
```
Shotcut v20.07.11
Windows 8.1 (x86-64)
```

When **_exporting_** a project, if an existing file is selected, which is in the **_playlist_**, then a warning dialog is produced:

> You cannot write to a file that is in your project.
> Try again with a different folder or file name.

The problem is that **the related file is immediately deleted** by Shotcut, anyway -- even though it's part of the project.

The expected behavior is that, when attempting to export over an existing file, Shotcut should **_not_** delete the file if it's part of the project.
![export_file](https://user-images.githubusercontent.com/7102064/91237083-84a17480-e6ee-11ea-8cb7-d47f0c3fd1c2.png)

**Comment by ddennedy** [comment] 2020-08-25 23:27
I can confirm this bug exists in that version due to how it was checking to see if the chosen file location was writable. This has already been fixed in a91757f for the next version due in September. Thanks

**Closed by ddennedy** 2020-08-25 23:27 UTC
