### ISSUE TITLE
Audio and video get out of sync after cut-editing a movie, version 16.01 - Ubuntu 14.04

### ISSUE THREAD

**Issue by HeliosLHD** [mltframework/shotcut#177] opened 2016-01-08 22:00 UTC
I've seen some mentions to this in other bug reports, but figured I'd add my $0.02 as well.  I've been using Shotcut for about a year or so casually to edit home movie recordings and convert my library to digital, and I noticed the problem when I start playback later in the movie...

The input source is a digital transport stream (.ts) encoded with a Hauppage Colossus with source coming in the component input, ffmpeg -i below:
Input #0, mpegts, from 'last crusade.ts':
  Duration: 03:00:02.61, start: 12.424533, bitrate: 9563 kb/s
  Program 1 
    Stream #0:0[0x1011]: Video: h264 (High) (HDMV / 0x564D4448), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 59.94 fps, 59.94 tbr, 90k tbn, 119.88 tbc
    Stream #0:1[0x1100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 190 kb/s

As I go through the movie and cut out commercials, it seems at each clip point there are a few frames lost (or blank frames inserted) and the video starts to lag behind the audio.  The effect is cumulative, such that by the end of the movie the video and audio are out of sync by 1000ms or more.  The audio sync is apparent on mpv and VLC in Linux, and VLC and Movie Player in Windows.

When I encode the edited file, I use the H.264 baseline profile, drop the framerate to 29.97 and leave the other settings default.

ffmpeg -i of the output file gives:
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Indiana Jones - Last Crusade_new2.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.36.100
  Duration: 02:00:32.21, start: 0.021333, bitrate: 3424 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709/unknown/bt709), 1280x720 [SAR 1:1 DAR 16:9], 3161 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s (default)
    Metadata:
      handler_name    : SoundHandler

The only thing I've noticed is that using the snap feature in the timeline, when it snaps it usually lists a non-zero positive number ranging from +00:00:08 to +00:00:20 depending on the splice point.
![screenshot from 2016-01-08 16 50 41](https://cloud.githubusercontent.com/assets/13319992/12210625/4a9fdf74-b629-11e5-8b19-8c066253892b.png)

Thanks again to the devs working this project, I think SHOTCUT is by far the most useful and full featured video editor for amateurs like me!

**Comment by ddennedy** [comment] 2016-01-08 22:19
I know you said "version 16.01," but you also said you have been using this a while, and there was a change between 15.12 and 16.01 that could have improved this. However, you might only see the improvement on projects created with v16.01. The bubble help that appears while moving clips has no bearing on this; it is shows a time change relative to the starting point of the drag and is not always accurate. H.264 with B-frames in a TS file is problematic for seeking. I will try to test this with some similar files, but I wonder how long it takes to notice. I certainly do not have 3 hours of this format. Maybe I can encode something from an A/V sync test clip on a loop.

**Comment by ddennedy** [comment] 2016-01-08 22:59
This MLT bug is quite likely related: https://github.com/mltframework/mlt/issues/69

**Comment by HeliosLHD** [comment] 2016-01-08 23:56
I've been working with versions since 15.02, I downloaded 16.01 this morning to test it again before I posted anything.  Funny thing is, I vaguely remember that somewhere around 15.07 this issue disappeared for a couple versions.

The picture I posted was created in 15.12 and reopened in 16.01, which I tried to re-encode this morning to see if it was better.  I didn't try to create a new project in 16.01 from scratch....  If you think there might be a change I can recreate the project in 16.01 and see if it is better.

As far as the bubble help...   It's weird because no matter how many time I grab and re-snap it to the end of the last clip, it still gives me the same frame offset.

**Comment by m9115m** [comment] 2016-01-14 17:40
Having the same issue in the current Windows version.

Here are the Steps to Reproduce:
1.) Start with an H.264 clip ~90 min in length.
2.) Cut off the head and tail of the clip (removing ~20 min from each end)
3.) Encode your now 45-50min clip back to H.264.

Check out the sync at min 40+....
Yikes the sync is out by 40 frames or more...

If you look at min 2, the sync is right on, but by min 40 it's way out.

Looks like the code is dropping audio frames.




When I Encode back

**Comment by ddennedy** [comment] 2016-01-14 19:04
@m9115m I just tested your steps, but I did not reproduce it. I am using a 90 min. movie source that was encoded using ffmpeg. I tested using both the timeline and not. Your problem might be related to the source. What created it? Is it variable frame rate (not supported)? Consider to post the output of mediainfo or `ffprobe -show_format -show_streams` against that file.

**Comment by m9115m** [comment] 2016-01-15 02:05
Here's my ffmpeg output:

  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomavc1M4V mp42
    creation_time   : 2016-01-10 09:25:23
  Duration: 01:35:00.63, start: 0.000000, bitrate: 392 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 512x288,
291 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2016-01-10 09:25:23
      handler_name    : Procaster Video
      encoder         : L
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, flt
p, 96 kb/s (default)
    Metadata:
      creation_time   : 2016-01-10 09:25:23
      handler_name    : Procaster Audio
[STREAM]
index=0
codec_name=h264
codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
profile=Main
codec_type=video
codec_time_base=1001/60000
codec_tag_string=avc1
codec_tag=0x31637661
width=512
height=288
coded_width=512
coded_height=288
has_b_frames=0
sample_aspect_ratio=0:1
display_aspect_ratio=0:1
pix_fmt=yuv420p
level=32
color_range=N/A
color_space=unknown
color_transfer=unknown
color_primaries=unknown
chroma_location=left
timecode=N/A
refs=1
is_avc=true
nal_length_size=4
id=N/A
r_frame_rate=30000/1001
avg_frame_rate=30000/1001
time_base=1/30000
start_pts=0
start_time=0.000000
duration_ts=171018848
duration=5700.628267
bit_rate=291638
max_bit_rate=N/A
bits_per_raw_sample=8
nb_frames=170848
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
TAG:creation_time=2016-01-10 09:25:23
TAG:language=eng
TAG:handler_name=Procaster Video
TAG:encoder=L
[/STREAM]
[STREAM]
index=1
codec_name=aac
codec_long_name=AAC (Advanced Audio Coding)
profile=LC
codec_type=audio
codec_time_base=1/44100
codec_tag_string=mp4a
codec_tag=0x6134706d
sample_fmt=fltp
sample_rate=44100
channels=2
channel_layout=stereo
bits_per_sample=0
id=N/A
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/44100
start_pts=0
start_time=0.000000
duration_ts=251398294
duration=5700.641587
bit_rate=96005
max_bit_rate=96000
bits_per_raw_sample=N/A
nb_frames=245520
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
TAG:creation_time=2016-01-10 09:25:23
TAG:language=eng
TAG:handler_name=Procaster Audio
[/STREAM]
[FORMAT]
filename=C:\Users\CCW-User\Videos\1-10-16 Pastor Tim 1 Corinthians 1 1-9-2016011
0-092523_446.mp4
nb_streams=2
nb_programs=0
format_name=mov,mp4,m4a,3gp,3g2,mj2
format_long_name=QuickTime / MOV
start_time=0.000000
duration=5700.628267
size=279570155
bit_rate=392335
probe_score=100
TAG:major_brand=isom
TAG:minor_version=512
TAG:compatible_brands=isomavc1M4V mp42
TAG:creation_time=2016-01-10 09:25:23
[/FORMAT]

**Comment by m9115m** [comment] 2016-01-16 21:50
I tried tweaking my encoding settings to be exactly what's in the above ffprobe output, but the audio sync still drifts in Windows.  Now it's off about 15 frames for a 45 min clip.

My guess is you're testing with small clips where the loss of sync is not noticeable.  Try going back to the steps in my previous post and checking the sync very closely after 45 min.  The audio for a 45 min clip should be about 15 frame ahead of the video.

In any case, let me know what you find.  I really like the features of this editor, but if it can't render long clips without losing sync, I can't use it.

I've tried the test above on avidmux and sync is dead on, without tweaking the encoding.  But, I hate the lack of JLK support on avidmux

**Comment by ddennedy** [comment] 2016-01-16 22:13
@m9115m  No, I was testing with 90 - 120 min. H.264 MP4 movies with dialog and judging the lip sync. The problem might be related to files created by Procaster and perhaps something special in them that throws something off somewhere. For example, maybe there is not a consistent number of audio samples over time - something called [unlocked audio](http://www.adamwilt.com/DV-FAQ-tech.html#LockedAudio). That can be a real pain, and we do not do anything to address it. I noticed your file is 44.1 KHz audio. So, I also tested 48 KHz -> 44.1 KHz and 44.1 KHz -> 48 KHz with no problem. 

Does the problem occur if you do NOT set an in point? Does the problem occur if you set Encode > Audio > Sample rate to 44100? If you use Avidemux to **transcode** (not copy) and then use that in Shotcut, make the ~20 min. in point, and encode; does it reproduce the problem?

**Comment by ddennedy** [comment] 2016-01-16 22:35
Ultimately, folks, you need to realize that I have been working on A/V sync within MLT, the engine for Shotcut, since it was started in 2004. Any product has problems with some inputs and will continue to as long as audio and video are being used together. Take into consideration the number of standards, formats, and tools there are in existence. It is effectively an intractable problem and the bane of existence for all multimedia engineers ad infinitum. I do not have the desire or obligation to chase every little problem report in this area to its ultimate conclusion. Sometimes, it must wait until I or another developer faces the problem their self and deals with it.

**Comment by bmatherly** [comment] 2016-01-16 23:07
Dan is right about AV sync being a never ending saga.

@m9115m I am willing to have a look at it if you make your file available to me. Upload it to Google drive or dropbox and send me a link at code@brianmatherly.com

**Comment by ddennedy** [comment] 2016-01-17 01:14
I have reproduced the problem reported by @HeliosLHD and I believe it is due to that linked MLT bug. created a 3 hour H.264 TS file from a Tektronix A/V sync test as uncompressed AVI. Then, I did as reported placing about 10 longs shots cut from the source onto a timeline making it about 90 minutes long, encoded that and checked the result. The result was ahead by about 21 frames.

**Comment by ddennedy** [comment] 2016-01-18 08:52
Just a note to report that I found the source of this bug and am working on a fix. In theory it could be the source of @m9115m's problem as well. The problem is related to 29.97 fps, and perhaps when I tried to reproduce @m9115m's problem I was using a 23.976 fps since I was working a long movie file at film rate.

**Comment by ddennedy** [comment] 2016-01-18 09:00
P.S. A workaround given the use cases described here is to use the playlist and not the timeline. If the timeline has not been used, then encode will use the playlist. (And if the neither playlist or timeline is defined, then it uses what appears in Source player.) You cannot simply remove tracks from an existing project as Shotcut still has an empty timeline. It only works with projects where timeline has never been used. The reason this workaround works is because the bug is in the audio mixer, which is used by timeline.

**Comment by HeliosLHD** [comment] 2016-01-18 11:39
Dan, thanks for continuing to look into this.  If there's any testing you want me to try or additional info, let me know.

**Comment by ddennedy** [comment] 2016-01-22 16:52
Fixed in MLT for next release: https://github.com/mltframework/mlt/commit/b264065634f0536bd302eeae6e61a4df3e60ba0d

**Closed by ddennedy** 2016-01-22 16:52 UTC
Labels: reproduced by dev, resolved
