### ISSUE TITLE
Shotcut crashes when using the text filter in GPU rendering mode

### ISSUE THREAD

**Issue by arthurrump** [mltframework/shotcut#130] opened 2015-10-20 17:49 UTC
When changing the text displayed by the text filter, Shotcut crashes with the standard Windows "shotcut.exe stopped working" (translated from Dutch) error, sometimes in company with a Microsoft Visual C++ Runtime Library error: "Runtime Error! Program: C:\Program Files (x86)\Shotcut\shotcut.exe This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information." The error only occurs when using GPU rendering, by the way. I'm running Shotcut 15.10.06 on Windows 10 (build 10240), sporting an Intel Core i5-3210M CPU and a NVIDIA GeForce GT 645M GPU, might you be interested.

**Comment by ddennedy** [comment] 2015-10-20 17:51
OK, but please remember that GPU is clearly marked experimental for a reason.

**Comment by arthurrump** [comment] 2015-10-20 17:57
I understand, but I thought you might interested though.

**Comment by ddennedy** [comment] 2015-10-21 02:02
I was able to reproduce this on Windows 10 and Linux - not yet tested OS X, but probably fails there too. It was intermittent, and I could more easily trigger it by resizing/repositioning the text. And, other times the text does not render, but interestingly the background color may.

**Comment by ddennedy** [comment] 2015-10-21 03:22
Another data point: the problem is reproducible on v15.08 as well, the version before Qt and Movit upgrades that could have affected this. Also, tested on v14.12 where it crashes as well. Both of those tests were on Linux.

**Comment by ddennedy** [comment] 2015-10-21 05:11
I might have been fixed with this recent MLT commit mlt/mltframework@3797206319324e34b4211d7212b4089efa5c12dd as I am not reproducing it in my working copy against MLT master. I will have to test a nightly build on Windows as well.

**Comment by tchncs** [comment] 2017-10-31 16:19
Uhm...anything new on this? o.O

**Comment by ddennedy** [comment] 2017-10-31 17:43
As of v17.10, the Text filter is disabled and marked as incompatible with GPU processing. There's your new for you unless you have a patch to contribute.

**Comment by ddennedy** [comment] 2018-11-05 07:02
Closing because GPU Effects is unsupported without a patch/pull request. Next version 18.11 makes this more obvious.

**Closed by ddennedy** 2018-11-05 07:02 UTC
Labels: GPU, crash, reproduced by dev
