### ISSUE TITLE
Crop filter unexpected behavior and its "Center" property appears to be broken

### ISSUE THREAD

**Issue by qubodup** [mltframework/shotcut#738] opened 2019-05-07 20:23 UTC
19.04.30

As far as I understand, Crop does not what it should do. It centers the crop against user's will.

What it does:
![image](https://user-images.githubusercontent.com/18312/57330485-7785fe00-7116-11e9-9a1b-f5d64b3dcb21.png)

What it should do according to my thinking and my experience with other video editors:
![image](https://user-images.githubusercontent.com/18312/57330509-8bc9fb00-7116-11e9-961d-bec764710843.png)
(used s&p to 'mockup')

Using "Center" disables the filter's influence completely, it seems:
![image](https://user-images.githubusercontent.com/18312/57330549-a603d900-7116-11e9-9154-b08d7111c93c.png)

This issue has been around for years (perhaps in some other form). Windows 64bit

**Comment by ddennedy** [comment] 2019-05-07 20:31
It works correctly for the way it was designed/intended: to remove edges from the source before the automatic scaling. Center works as intended as well: center-cropping is when aspect ratio of source is different than project, it crops to fill the screen. What you are asking for is a different kind of cropping filter, which can be seen is like padding. Thus, I am closing this as working as intended even if not what you expect. I do plan to add another type of crop that is like what you want. Lastly, there is the other type of cropping people want where it changes the output resolution and aspect ratio, but I am not sure if that will ever come.

**Closed by ddennedy** 2019-05-07 20:31 UTC

**Comment by ddennedy** [comment] 2019-05-28 00:30
For the next version 19.06 I:
* added a new **Crop: Rectangle** filter
* renamed the old one **Crop: Source**
* renamed Circular Frame to **Crop: Circle** (one can now change the color's alpha)
