### ISSUE TITLE
Since release 160301 debian audio waves are shown shortened in video track at times

### ISSUE THREAD

**Issue by mucmike** [mltframework/shotcut#217] opened 2016-04-06 22:15 UTC
Hello together, since release 160301 debian in the video track in the time line some video clips are shown with shortened audio wave forms at times. It doesn't occur with all video files. But it always occurs with the same video files. As I'm working with mp4 files only, my bug report is only about mp4 files. Find one short file example in the attachment to reproduce the bug for yourself. Release 160201 shows the audio waves correctly. Later releases show the audio waves shortened to the first third of the clip length and the remaining two thirds are shown as silence. But the player plays the audio correctly during the whole duration of the clip. It doesn't look like the waves where truncated. It looks more than the time line for the audio is scaled higher than the time line of the video, but just for displaying, not for the player. If I copy the files with avidemux and use them with shotcut after that, wave forms are shown correctly. So this issue it seems to be related to the files. That's my workaround now. But this workaround has not been necessary until release 160201.

[example shortened wave forms.zip](https://github.com/mltframework/shotcut/files/207432/example.shortened.wave.forms.zip)

**Comment by ddennedy** [comment] 2016-04-08 02:36
I have not reproduce this, but there have been some changes to fix bugs related to waveforms. I think your cached audio levels data is now incorrect. Right-click the clip on the timeline and choose Rebuild Audio Waveform to see if the problem goes away.

**Comment by mucmike** [comment] 2016-04-08 17:15
Hello Dan,

Rebuild Audio Waveform fixed the problem. I never recognized this right 
click option.
Thank you very much for your helpful response!!!

Mike

Am 08.04.2016 um 04:36 schrieb Dan Dennedy:

**Comment by ddennedy** [comment] 2016-04-08 19:08
I am going to close this because we do not have a way to validate audio levels data without actually regenerating it, we do not save the shotcut version along with the audio levels data, and I do not want to simply discard everyone's cached data when they upgrade to a newer version.

**Closed by ddennedy** 2016-04-08 19:08 UTC

**Comment by mucmike** [comment] 2016-04-10 16:43
Hello Dan,

closing is OK. There is a suitable solution with regenerating the audio 
lavels data. It's just a click and one can continue with shotcut. So it 
doesn't make sense to spend more efforts to it.

Thank's for you were looking after it :-)

Mike

Am 08.04.2016 um 21:08 schrieb Dan Dennedy:
