### ISSUE TITLE
Sluggishness and very high memory usage for no reason

### ISSUE THREAD

**Issue by liquid600pgm** [mltframework/shotcut#869] opened 2020-05-18 14:44 UTC
For some reason, when editing a relatively large project, the app seems to just eat up my RAM and work really slow. This applies to everything: playback, moving the playhead, opening tabs in the UI, literally *any action you can imagine* seems to eat up more and more memory for no reason. When it does that, it also seems to get stuck in a busy loop (?) because the CPU usage rises up to 100% on 4 cores.
This effect grows as time goes on, at first the editor uses a bit of memory, but with time it starts using more and more memory and becomes very slow to use.

- OS: Artix Linux 5.4.34-1-lts
- Shotcut: ARCH-20.04.12

**Comment by ddennedy** [comment] 2020-05-18 16:24
We only officially support our builds, not distribution builds. I do not reproduce this, unclear what to do to reproduce it. Seems like something gets stuck in an infinite loop.

**Comment by liquid600pgm** [comment] 2020-05-18 17:42
Well I'm not sure if it's a distro build, I can try with an official one and report back on whether it runs better or not. I'm unsure how to reproduce it either, it *just happens* when I work on a relatively large project (with lots of individual clips).

**Comment by ddennedy** [comment] 2020-05-18 17:56
Maybe you are running low on memory, and it starts swapping RAM to hard drive. Shotcut does not today monitor free memory to prevent further activity until memory is freed. Also, video editing is heavy in general, Shotcut does leak a little, and there might be corner cases that cause huge leakage. Battling leaks is a continual process, but not so trackable or actionable without specifics. IOW, we cannot fix a bug like fix all the bugs, or Shotcut should never crash, or Shotcut uses too much memory, or Shotcut is not fast enough. Of course, all of those are goals, but any of those would never be resolvable.

**Comment by liquid600pgm** [comment] 2020-05-18 18:07
I just went ahead and confirmed that the official AppImage also leaks memory. I'm certainly *not* running low on RAM, when I launch Shotcut I had about 2 GiB (out of 16) filled but as I started playing back the video it started rising faster and faster. The video was also starting to stutter more and more as more memory was allocated.
While I do agree that video editing is a heavyweight task, I didn't experience such high memory usage in other editors, like Blender or Kdenlive (all with similar sized projects). I'm not here to just complain, I'm just noticing a weird anomaly that seems to be occuring in this specific project of mine. I'd love to narrow it down even more, but I'm unsure where to start.

**Comment by ddennedy** [comment] 2020-05-18 18:30
You can upload your project file, and I can see if I can reproduce it when I substitute with my own media.

**Comment by ddennedy** [comment] 2020-11-12 22:58
There was a change in both MLT and Shotcut to hold less resources in cache for the next version 20.11. I think that will address the issue. It is normal that "as I started playing back the video it started rising faster and faster" but after N videos, it should level off. That is due to caching. The engine (shared by Kdenlive) must cache audio/video objects while it is compositing video tracks and mixing audio, and these video objects also cache entire images in memory for repeated access. For the next version, the caching is reduced and less aggressive. Since I am fairly confident that was the issue and considering the build is unsupported, I am closing it.

**Closed by ddennedy** 2020-11-12 22:58 UTC
Labels: Linux, pending

**Comment by liquid600pgm** [comment] 2020-11-13 16:26
Alright, I'll check out the new release when it comes out. Thanks for the heads up.
