### ISSUE TITLE
Cant drag and drop clip from playlist to timeline

### ISSUE THREAD

**Issue by VladimirLevadnij** [mltframework/shotcut#1445] opened 2023-05-24 15:11 UTC
Hello. Now for the first time I've encountered the problem [discussed here](https://github.com/mltframework/shotcut/issues/326), I can't move a clip from the playlist to the timeline with the mouse.

Closing the program and reopening does not help me. Not being able to drag a clip into the timeline with the mouse is a constant problem.

This problem arose, I assume, after updating to Shotcut 05.23.14

Perhaps the new version has an option to allow / block dragging a clip to the timeline and I should enable this option correctly?

Other ways to add a clip to the timeline work. But dragging with the mouse is much more convenient for me. Can you suggest what can I do?

I have Ubuntu 23.04.

**Comment by ddennedy** [comment] 2023-05-24 15:44
Maybe duplicate of #1441
Basically this is out of our control and a bug between Qt and your desktop environment.

**Comment by luzpaz** [comment] 2024-02-05 16:00
@VladimirLevadnij can you still reproduce on latest stable ?

**Comment by VladimirLevadnij** [comment] 2024-02-05 17:33
> @VladimirLevadnij can you still reproduce on latest stable ?

Hello @luzpaz. No, this bug was fixed in previous versions. Now on Shotcut version 01/24/28 I don’t get this error.

**Closed** 2024-02-05 17:34 UTC
