### ISSUE TITLE
Reopening and saving file makes tiny adjustments to clip timings

### ISSUE THREAD

**Issue by paulbatum** [mltframework/shotcut#162] opened 2015-12-16 03:04 UTC
I have noticed while working on a project that slowly but surely, my video is getting out of sync with my audio and the timings on my clips are changing. It was hard to detect at first because the effect is very slight, but by using diff tools I was able to determine that there is a bug in shotcut. Simply the act of opening a file and resaving can cause the clip timings to be shortened by ~30 milliseconds.

Steps to reproduce:
1. Take the linked hunger.mlt file and adjust the referenced file to some long video file you have available
2. Open the file in shotcut, then without making any changes, save the file under a new name.
3. Use a diff tool on the two files, you should see slight track timing changes. You should have something similar to the linked hunger2.mlt file.

https://dl.dropboxusercontent.com/u/3646793/hunger.mlt
https://dl.dropboxusercontent.com/u/3646793/hunger2.mlt
(I tried to attach these files to an issue in a zip but github didnt like it for some reason)

I have not been able to find a good workaround for this. I am somewhat stuck as I am no longer sure if I can complete my project in shotcut without having to go and manually fix all my clip timings regularly.

Version info:
Shotcut version 15.12.03
Windows 10 x64

**Comment by metellius** [comment] 2015-12-16 06:03
I was able to reproduce the diff between mlt's on linux as well

**Comment by ddennedy** [comment] 2015-12-16 16:43
I found the bug in MLT due to some missing rounding. I expect to have that fixed today, and I can give you a new build of Shotcut tomorrow that includes the fix.

**Comment by ddennedy** [comment] 2015-12-16 20:35
Fixed in git commit https://github.com/mltframework/mlt/commit/6b518f5bf99bcd091398386311c75abf043bbea3
I will add a link for nightly build tomorrow morning.

**Comment by ddennedy** [comment] 2015-12-17 17:19
@paulbatum please test this
http://builds.us.meltytech.s3.amazonaws.com/shotcut/shotcut-win64-151217.exe

**Comment by paulbatum** [comment] 2015-12-17 18:15
Awesome, I'll try it tonight!

**Comment by paulbatum** [comment] 2015-12-19 01:53
I can confirm that this has fixed the issue I reported, but I think this build still has a significant bug - simply opening hunger.mlt and then doing File->Close causes a crash..

**Comment by ddennedy** [comment] 2015-12-19 01:59
It has a lot of bugs, but not a lot people wanting to fix them. Closing this as resolved.

**Closed by ddennedy** 2015-12-19 01:59 UTC
Labels: reproduced by dev, resolved

**Comment by paulbatum** [comment] 2015-12-19 02:10
I spoke too soon. I am having other major issues with this build. When I drag clips around on my main project, they jump to totally different locations to where I specified. I am trying to create a decent repro, but suffice to say I don't think this build is usable (I agree close bug is not a big deal).

**Comment by paulbatum** [comment] 2015-12-19 02:16
Having problems reproducing. I will file a new issue if I find a repro.
