### ISSUE TITLE
Resizing text filter immediately crashes program

### ISSUE THREAD

**Issue by anzx42** [mltframework/shotcut#220] opened 2016-04-14 20:48 UTC
On Windows with CPU or GPU processing, If a text filter is resized the program crashes immediately.

**Comment by ddennedy** [comment] 2016-04-14 20:51
Which filter exactly? I have not seen this on CPU mode BTW - might be specific to your system configuration.

**Comment by anzx42** [comment] 2016-04-14 20:56
The "Text" filter with the text https://my.mixtape.moe/zkkrbh.PNG. When I resize diagonally from the top right corner the program crashes.

**Comment by ddennedy** [comment] 2016-04-15 03:10
GPU mode is a duplicate of #130. I have not been able to reproduce it on CPU mode. It might depend on other factors.
Is this repeatable?
Briefly describe the source to which you are applying the filter.
Does it only happen for an item in an existing project? Does it happen if you start Shotcut fresh, open a clip, and before adding it to Playlist or Timeline, add the filter and resize it?

**Comment by anzx42** [comment] 2016-04-15 16:22
Turns out the project is running GPU mode. When I open Shotcut in CPU mode and try to open my project it resets to GPU mode. This is a dupe

**Closed** 2016-04-15 16:45 UTC
Labels: pending
