### ISSUE TITLE
JACK audio connectivity problems

### ISSUE THREAD

**Issue by unfa** [mltframework/shotcut#463] opened 2017-11-14 16:49 UTC
1. MLT seems to create unpredictably names JACK clients, and sometimes when changing settings (like external video monitor) - the JACK client name changes.

2. I have to manually connect Shotcuts's JACK ports to system output, because they seem to be connected to Shotcut's own input ports instead:

![image](https://user-images.githubusercontent.com/491704/32792461-b21a39b6-c963-11e7-8e54-b2a157e9a504.png)

3. These two combined make it necessary to manually reconnect Shotcut to JACK system output from time to time, because automating that isn't going to be easy, because each time MLT creates a JACK client - it's giving it a different name.

So I'd like to ask for two things:

1. Make Shotcut create JACK client with a fixed name (unless there are two or more instances running):
`shotcut shotcut-01 shotcut-02` etc. This is what Ardour does and I think it works well.

2. Make Shotcut automatically connect to JACK system output ports when the audio backend starts, and reconnect if the backend is restarted to take that off the back of the user.

Thank you :)

**Comment by ddennedy** [comment] 2017-11-14 18:18
Duplicate of #361 and I am just going to remove support for JACK since I cannot get it right and it's just a nuisance at this point.

**Closed by ddennedy** 2017-11-14 18:18 UTC
