### ISSUE TITLE
UI Glitch: Timeline stopped accepting video or images.

### ISSUE THREAD

**Issue by lnx64** [mltframework/shotcut#326] opened 2016-10-20 17:45 UTC
I'm not entirely sure what happened.  I was making a rather simple and small video, then all of a sudden, the timeline wouldn't accept anything, the mouse cursor simply showed a no symbol as if I was dragging something not media related.  I made a video of the issue, as nothing seemed to make sense.  The only solution was to save the MLT, and re-launch Shotcut.

Perhaps I hit a key, maybe you can tell me something I'm missing on the screen that I accidentally toggled to prevent drag and drop from working?

https://www.youtube.com/watch?v=dgFg-_h1a7c

Ubuntu 16.04.01 64-bit.  Shotcut 16.10.01.

**Comment by ddennedy** [comment] 2016-10-21 03:49
See duplicate #330 for more steps to reproduce.

**Comment by ddennedy** [comment] 2016-10-21 06:54
@metellius Can you help with this one? It is an interesting Qt puzzler. :-) I can see events going into TimelineDock::dragEnterEvent(), and I can even disable acceptDrops in the timelinedock.ui file to ignore that because timeline.qml:DropArea.onEntered() is firing as well under normal conditions. However, following the repro steps, dragEnterEvent() is not working to accept the drag event, and qml:DropArea.onEntered() is no longer entered to try to accept it. Strange and disconcerting.

**Comment by metellius** [comment] 2016-10-21 10:10
It might be related to the cause of the hover-exit glitches I investigated for the qml playlist way back... I'll have a look as soon as I have time.

**Comment by lnx64** [comment] 2016-12-02 02:43
This issue is happening again on 16.11.02, can we re-open this?  I video taped it happening, and the only fix was to save the MLT and re-open Shotcut again.

**Comment by ddennedy** [comment] 2016-12-02 03:14
Is it repeatable with steps?

**Comment by lnx64** [comment] 2016-12-02 03:31
I honestly don't even know what I did.  Once you get in the zone trying to edit something, you don't always remember what you did..  I will try, but this is the first time I came across this lockup of the time line.

Is there a debugging mode in shotcut that logs every action that is done, just in case I ever run across it again?

I mean I have to start over anyway, shotcut just crashed in general on me, window closed, no errors, gotta restart from the point the MLT was last saved, so I guess I'll see if I run across it again.

**Comment by lnx64** [comment] 2016-12-02 03:38
I imported one giant video clip, moved it to the time line, broke it up into sections by the S key, then realized I forgot an intro and moved all the clips to the right, one by one, starting from the right.  After that, the left most clip lost it's thumbnail and became a darker shade box on the timeline, and from there clips couldn't be dragged in.  Saving the MLT and relaunching worked, but the thumbnail was still missing on the left most clip.  Then shortly after, Shotcut completely crashed without error (the post above).  When I relaunched shotcut it offered to open the auto save, and it did, and my project exported without trouble, AND the left most clip had a thumbnail again.

GPU acceleration is off btw.

That's all I can remember, so something may be missing in the middle.  But something triggered it.

**Comment by ddennedy** [comment] 2016-12-02 04:31
I understand, but to be honest I got lucky coming up with the fix for this. Something is going wrong in the GUI toolkit (Qt), and I came up with what is, more or less, a workaround. It would not surprise me if there is a way to push it into a state where the drag events are no longer working. There might be another place where I need to apply the workaround if we figure out the cause.

**Comment by lnx64** [comment] 2016-12-02 04:59
I'll keep my eyes peeled and if it happens again, I'll see if I can remember anything further as to what's causing it.

**Comment by rtpHarry** [comment] 2017-09-01 12:01
This just happened to me today with the latest version fresh installed for the first time, 17.08, 64-bit Windows installer (64-bit Windows 7+), on Windows 10.

Restarting Shotcut was the workaround to get me going again.

**Comment by mortepcandvr** [comment] 2017-09-04 06:23
Red Strikethrough circle icon on drag n drop from playlist/bin to timeline track has been happening to me repeatedly in v17.08.01, 
Typical cause is, after numerous successful drag n drops of clips from playlist/bin into a track on timeline, to play through that timeline, click pause, then attempt to drag n drop more clips from playlist to timeline, however this does not ALWAYS result in drag+drop failure, just after a while - possibly from history/change buffer full?

Workaround is to save .mlt and restart Shotcut.
Closing File and reopening without restart of Shotcut does not fix/workaround.

I do have some clips on the timeline which lost their thumbnails, but they export the desired video frame range correctly.

**Comment by insitewebdesign** [comment] 2017-09-09 17:38
while a project is open, click file new, and it screws up the time line so nothing can be added but there are several other ways.

**Comment by dioptre** [comment] 2018-04-13 20:28
Still happening for me too. Current version 18.3.6

**Comment by iamsohailjaffry** [comment] 2018-05-15 19:50
**SOLVED**

1. Select the file so it appears on the Preview area. 
![image](https://user-images.githubusercontent.com/30363903/40079929-e3c34cb8-58a2-11e8-88eb-fd609bdc4f27.png)
2. Click on Append to the current track.

**Comment by ddennedy** [comment] 2018-06-12 18:37
This bug is about drag-n-drop, but there are many other ways to add clips to the timeline using [keyboard shortcuts](https://www.shotcut.org/howtos/keyboard-shortcuts/) and timeline toolbar buttons that are not affected by this bug. Look for words like Paste, Append, Insert, and Overwrite.

**Closed** 2018-09-14 23:29 UTC
Labels: workaround

**Comment by lnx64** [comment] 2019-01-14 21:10
See this is why I switched to Davinci Resolve.

Basically you have a workaround and would rather close my 2 year old bug without truly fixing the issue.

**Comment by ddennedy** [comment] 2019-01-14 23:16
There have been multiple fixes for this and not just workarounds. See the "closed this in ____" lines in this Issue. I hear it may still happen sometimes, but I do not know how to reproduce it. Meanwhile, the workarounds are not only useful information but also a better editing workflow than drag-n-drop. When another sequence of steps is found then we can reopen it.

**Comment by piiskop** [comment] 2021-03-11 19:05
Has anybody reported this thingy to _Qt_ then? Because five years later, the bug still comes around.
