### ISSUE TITLE
Audio "pop" right after transition

### ISSUE THREAD

**Issue by ltGuillaume** [mltframework/shotcut#314] opened 2016-09-27 13:10 UTC
A transition (cross-fade audio, cut video) that's been adjusted afterwards via dragging begin/end point in the timeline pretty much always ends up with a disturbing audio pop right after the transition. The only solution is to remove the transition and recreate it (readjusting it does not do the trick). Seems like the transition may become independent of the clip behind it, so that they don't connect seamlessly anymore.

Windows 10 b10586; Shotcut 16.09.01

**Comment by lnx64** [comment] 2016-09-27 19:41
Let me try doing that by how you mention.  I usually clip at the playhead and remove the rest.

**Comment by lnx64** [comment] 2016-09-27 19:44
I can confirm it here, there is a little pop in the transition when the video is adjusted by dragging the end point.

**Comment by ltGuillaume** [comment] 2016-10-01 02:34
Thanks for reproducing and confirming the issue :)

**Comment by lnx64** [comment] 2016-10-02 21:06
I just made a video where these pops are visible.  In the slowed down section I split it multiple times at the playhead so the text ^ cursor can move as I haven't figured out how to make text actually move any other way.  Each split has a pop, even though nothing was added or removed from that clip itself.  It just pops.  Those pops are not supposed to be there, and Final Cut doesn't add these pops when I do the same thing (except there I really don't have to break it like that because it CAN move text, but simply snipping at the slowed down clip doesn't cause audible pops period).

**Comment by ddennedy** [comment] 2016-10-02 21:23
The original bug report says "A transition (cross-fade audio, cut video) that's been adjusted afterwards via dragging begin/end point in the timeline." However, it appears @lnx64 does not use the same steps to reproduce - only a somewhat vague reference to splitting a slowed down section.

> Those pops are not supposed to be there

no shit

> Final Cut doesn't add these pops... it CAN move text... doesn't cause audible pops period

Thank you for rubbing it in my face. Is that intended to be motivational? Because, it's not. Now, I just think you're a jerk.

**Comment by lnx64** [comment] 2016-10-02 21:32
A jerk?  Now that was not the intention at all, and I've been more than helpful for you with as much detailed bug reports as possible.  I was stating it doesn't add the pops to show it isn't something with the video file or anything like that, even though I don't have to split clips like that on a different program.

Don't be unprofessional please.

**Comment by ltGuillaume** [comment] 2016-10-02 21:35
Could still be that @lnx64's issue has got the same root cause. Is splitting (which pretty much happens between clips and a transition between clips) always frame accurate? It seems like some kind of unforeseen shift. I'd like to see the .mlt file of this, @lnx64.

**Comment by lnx64** [comment] 2016-10-02 21:41
Sure thing @ltGuillaume .  Here you go.  And yes, I feel it can be related which was my point.  Totally not trying to be a jerk in any way.  I would think splitting is frame accurate.  Video wise it seems to be fine no jumps or anything like that, but the audio does always have a pop, like the waveforms aren't.

[project.txt](https://github.com/mltframework/shotcut/files/505261/project.txt)

**Comment by ddennedy** [comment] 2016-10-02 22:12
Wow, now I am accused of being unprofessional for telling you how I did like the way you phrased things. That's OK because I largely think "unprofessional" is a lame claim anyways. You are correct that you have been helpful in other bug reports, and I appreciate that.; sorry I did not recognize you at first. Also, your explanation of the Final Cut comparison is sensible even if it did not come across that way the first time. Now, I realize you are volunteering to help (many others just want for more for free), but do not try to suggest you have put anywhere close to the amount of time into Shotcut that I have. I am sorry to have to point that out to you, but I sometimes wonder if people understand and appreciate the time and effort, and if this is any indication, now I know.

**Comment by lnx64** [comment] 2016-10-02 22:30
Well, calling someone a jerk is unprofessional, and it is..  If I called a co-worker a jerk in a non playful manner, I'd have been disciplined for unprofessional behavior.  Sorry you see it as comparing to others, the point is, we have put time into it, a little common courtesy is what we'd expect for that time we put into it.  I was the one you called a jerk, so yes I am going to remind you that I have taken time out of my day to report these things, and will take offense to it.

I worked for Apple, developing OS X 10.7 to 10.9, I was on their team, bug reporting, and developing some of the features of which I can't speak for (NDA), but I do actually understand what goes into it.  That's why I take my time to bug report, and compare to other programs to verify it's not the source video having a messed up audio codec.  In fact, if I reported anything to the iTunes team, they would ask me, if file A is messing up and file B is not, does file A play correctly on other applications like QuickTime directly, or VLC?  If it works on VLC but not QuickTime, problem is QT (since iTunes uses it), and may require the ticket to be forwarded.  Etc..  I know the chain, and how we patiently have to determine where the cause lies, all of that.

Now with that said, may we please get back on topic and help work out the issue OP has posted?  Popping in audio is no go, and I feel my popping issue is in essence, related.  Splitting a clip at the playhead still counts as a transition as it would appear (from between the now two clips, which used to be one clip), since the pop is identical to what OP stated.

**Comment by lnx64** [comment] 2016-10-02 22:42
I made a video showing that a video added to the timeline, as is, plays fine.  But splitting with S or (at the playhead), adds pops.  I do believe this is related to how it's handling a transition between them.

https://www.youtube.com/watch?v=5LO-xaRKckI

Not only are the pops identical to those that OP has determined by their method, even those we are making a transition differently, it is a transition still.  The pops heard in the timeline, are present in the exported file as my other YouTube video showed.

**Comment by ddennedy** [comment] 2016-10-02 22:46
Next time, I will try to better reflect how something made me I feel instead of name-calling.

This problem is probably due to this MLT bug: https://github.com/mltframework/mlt/issues/69

**Comment by lnx64** [comment] 2016-10-02 22:49
Do you think that perhaps a 1-2 frame audio fade can be made automatic in the background unless one is manually specified?  It could reduce overhead on the person editing it in my opinion.

**Comment by ltGuillaume** [comment] 2016-10-03 16:17
Ah ok understood. hope this bug will be fixed soon, as its manifestation seems quite random (sometimes it's audible, sometimes it's not), which leads to confusion.

**Comment by ddennedy** [comment] 2016-10-31 05:59
I believe I improved this in MLT commit https://github.com/mltframework/mlt/commit/0dbd50abe9f23cef5ea51f92b7506fdd08cf33f0
I still get a little crackle, but better than before. We will get feedback from the people in this ticket before deciding whether to close it.

**Closed** 2016-11-06 22:10 UTC
Labels: pending, resolved

**Comment by brotherchris** [comment] 2017-07-01 01:18
I have this same issue, it pops on every transition. Anyone find a fix?

**Comment by pupperpowell** [comment] 2018-01-04 22:44
I added a clone of the audio, except without any breaks, and muted the original, spliced audio track.

No pops.

**Comment by bag-man** [comment] 2018-03-16 22:12
This issue is still present for me.

**Comment by tecaspt** [comment] 2022-12-27 00:16
Issue is still present on versions 22.06.23 and 22.12.21. Just updated to see if it fixed the situation, but that was not the case. Does anyone know of any version that works correctly, and that could fix my video?

**Comment by bmatherly** [comment] 2022-12-27 00:32
This issue is too old. If you have a bug and some steps to reproduce it, please create a new issue.
