### ISSUE TITLE
Video playback broken in versions 21.05.01 and 21.05.18 when playlist is "large"

### ISSUE THREAD

**Issue by Gizemquea** [mltframework/shotcut#1114] opened 2021-05-31 07:33 UTC
I'm using shotcut on Windows 10 64bit, machine is a Ryzen 7 3700X, NVIDIA 1030GT with 32 GB RAM - everything works fine in 21.03.21 (on identical machine, even if installing versions back and forth) but breaks beyond that particular version. 

The clips I use are nothing special in any way (GoPro Hero 7 or DJI Osmo Action footage) and playback is just fine in any application I ever tried - including shotcut up to 21.03.21. The following happens regardless of whether I am "upgrading" an existing project or starting a new project from scratch in that particular version of shotcut.

I ALWAYS have at least more than hundred (sometimes even more than thousand) clips in my playlist - the problem doesn't seem to EVER occur if there are just a few clips in the playlist!

Starting from 21.05.01:
1. Double click in playlist does not start playback anymore (gets me the first frame of that clip instead (REALLY annoying! )- this happens regardless of playlist size)
2. If the playlist is "large" then hitting play will start playback SOMETIMES
3. IF it starts it is extremely sluggish and stutters massively for seconds until eventually recovering - SOMETIMES it will work to pause playback and hit play once again
4. If it doesn't start (or recover), playback remains unresponsive. It will NEVER again work for this (or any other) clip.
5. Once it is in the above state: you can still successfully save your project, but trying to play another clip or getting any other form of video preview (e.g. by setting a new playhead position in the timeline) makes shotcut "not responding"
6. It is NOT a resource problem, the machine is neither under load nor even above 50% on any limiting resources (RAM, disk space etc)
7. The problem occurs so frequently that I never got past playing 3 clips in a row with large playlists and shocut versions 21.05.01 and above ...

I tried every setting I could think of, including all display methods, external vs. internal monitors, display of audio waveforms etc. - no luck. It really just seems to depend on playlist size. 

The above has NEVER happened to me with 21.03.21 (same machine, regardless of any setting I tried) and I am in fact using 21.03.21 now to continue work on the very same projects that I can't complete with 21.05.18.

**Comment by bmatherly** [comment] 2021-06-05 13:59
> I ALWAYS have at least more than hundred (sometimes even more than thousand) clips in my playlist - the problem doesn't seem to EVER occur if there are just a few clips in the playlist!

Does the problem occur if you add the same clip many times? I'm trying to figure out how I can easily recreate this problem. I do not have GoPro  7 clips and I do not have hundreds of clips. Could you try to do some experiments to make a simpler failure case? For example, use a single file and add it 10 times, 25 time, and 100 times? Exactly where does it break? Or do all the files have to be unique?

> Double click in playlist does not start playback anymore (gets me the first frame of that clip instead (REALLY annoying! )- this happens regardless of playlist size)

This is fixed for the next release via https://github.com/mltframework/shotcut/commit/c37ab2462b0a722ad56047cc11ceff8238cb01c7

**Comment by Gizemquea** [comment] 2021-06-07 07:37
It really doesn't matter whether this is GoPro 7 footage (tests conducted with 21.05.18), you also don't actually have to hit play explicitly to get into the "not responding" state.

Possible response time of the storage device (and indirectly also bitrate of the footage) does seem to make quite a difference. If files reside on a USB-Harddrive, things break fairly easily, with as little as 3 Items in the playlist (identical files).

DJI Osmo action footage actually seems to make the problem occur more frequently (higher bitrate), as does 4k footage.

If files reside on my internal SSD, it takes a few dozen items in the playlist to break things reliably (~30) - I didn't manage to pull this off with just ~15 instances of the same file.

The most reliable way to break things is to put just a few video clips on an external USB drive  (or just a single file multiple times) into your playlist and randomly double click the items FAST, (at lest 2 Items per second) - this will get shotcut "not responding" within a few seconds.

**Comment by ddennedy** [comment] 2021-06-07 18:31
I believe I experienced this yesterday on Linux when I was working with a few fairly large files off of a file server.

**Comment by ddennedy** [comment] 2021-06-07 21:22
I found this is a regression in ebcdde261. When I revert it I am unable to reproduce the bug reported in its commit message.

**Comment by Gizemquea** [comment] 2021-06-08 06:17
Great to hear that you were able to reproduce this. It basically makes any version past 21.03.21 completely useless for me.

**Comment by ddennedy** [comment] 2021-06-09 00:53
Reverting ebcdde261e2c144acc751bf519f67664643da8f4 also fixes https://forum.shotcut.org/t/images-videos-sending-the-timeline-back-to-the-start/28148

**Comment by ddennedy** [comment] 2021-06-13 18:35
Fixed in dee4ef3c. I went ahead and reverted because I want to do some testing with a Windows nightly build prior to release candidate I want to make by the 15th.

**Closed by ddennedy** 2021-06-13 18:35 UTC
Labels: reproduced by dev
