### ISSUE TITLE
Image is exported as white block, randomly.

### ISSUE THREAD

**Issue by catscarlet** [mltframework/shotcut#1384] opened 2022-12-10 14:41 UTC
This keeps happening randomly and I have no idea what causes this.

Some images are good, somes not.
Sometimes png, somethimes jpg.
Sometimes this image, sometimes that image.(no mlt file editing, just export)
Very Random.

Changing image's filename/filepath may work, or make it worse.

Only after exported, it can be check whether it's good or not. While during shotcut editing, the images are always showed correctly

![screenshot_on_b85m_by_flameshot_at_2022-12-10_22-17-48](https://user-images.githubusercontent.com/10594035/206860737-54226855-71a8-4b65-a838-ab0691ed4ff5.png)

![screenshot_on_b85m_by_flameshot_at_2022-12-10_22-18-08](https://user-images.githubusercontent.com/10594035/206860743-9edee098-07b1-41ed-b73d-5e6b7290206a.png)

ffmpeg version:4.2.7-0ubuntu0.1
shotcut version: shotcut-linux-x86_64-221125.AppImage, and shotcut-linux-x86_64-221025.AppImage
OS: Linux Mint 20.3 (based on Ubuntu 20.04)

Also I think this issue is relate to: #1213 #1206

Is there any debug infomation I can get when exporting, in AppImage version? Or maybe I need to use the Linux portable tar?

**Comment by ddennedy** [comment] 2022-12-11 21:23
This was reported a few times in the forum and never reproduced by a developer including using the same reported distribution running in a virtual machine. I retested this AppImage on a relatively new setup using Pop!_OS 22.04, and I did not reproduce it by making a slideshow from 36 JPEGs.
I doubt using the portable tar will make a difference as it is the same build, but likely the Flatpak will because it is completely different.

**Comment by ddennedy** [comment] 2022-12-11 21:47
This forum comment  claims that the problem arises when the JPEG has an ICC profile:
https://forum.shotcut.org/t/shotcut-22-10-25-on-ubuntu-22-04-is-not-exporting-jpg-images/36340/8?u=shotcut

**Comment by ddennedy** [comment] 2022-12-11 21:53
I reproduced it from the JPEG with ICC profile provided. The export log shows

> [mlt_producer 0x55673a3b34f0] /home/ddennedy/Downloads/testinfo/ 1885 The Hen Egg5.jpg
    QImage retry: 1 - File not found
[mlt_producer 0x55673a3b34f0] /home/ddennedy/Downloads/testinfo/ 1885 The Hen Egg5.jpg
    QImage fail: 1 - File not found

**Comment by catscarlet** [comment] 2022-12-12 02:41
> 

Thanks for your efforts.
I would also mention that the image filename in my project also contains Chinese Words and some sort of symbol words like brackets, but not space, nor non-breaking space.

![screenshot_on_b85m_by_flameshot_at_2022-12-12_10-31-05](https://user-images.githubusercontent.com/10594035/206949067-737fdf57-c151-4dc0-a178-71209a551922.png)

The files which have issues are also jpg/jpeg files in this time.

I also tried shotcut-linux-x86_64-221125.txz, and got same problem as the appImage version.

**Comment by catscarlet** [comment] 2022-12-12 03:28
I just convert these jpeg files to png files with the same name but with png, and the problem is gone.

![vlcsnap-2022-12-12-11h27m28s632](https://user-images.githubusercontent.com/10594035/206954381-0affbf7b-be4c-4126-859d-27f2c3163e91.png)

Also tried to export jpeg with color management disabled by gimp, but this one didn't work. May be I missed something?

**Comment by ddennedy** [comment] 2022-12-12 03:47
portable tar, appimage, and snap are all the same build. Flatpak is a completely different build and works for me in the example from the forum thread. I guess it is some problem in the Qt version we built  the portable and appimage, possibly related to libicu.

**Comment by ddennedy** [comment] 2023-01-12 20:43
We started migration to Qt 6 for the next version, and my test case to reproduce it is working in my test build of that branch. So, this should be fixed for next release on Qt 6.

**Comment by catscarlet** [comment] 2023-02-25 10:53
Weird.

One of my other project is using all png files but one image also turns into white block.

![screenshot_on_b85m_by_flameshot_at_2023-02-25_18-52-22](https://user-images.githubusercontent.com/10594035/221353004-25519632-6b58-4080-b26a-332a1b07c1bb.png)

Well. Still waiting for the next release on Qt 6.

**Comment by ddennedy** [comment] 2023-02-25 19:03
There will be an alpha version of that very soon. You can get it sooner here
https://github.com/mltframework/shotcut/actions/runs/4269048303

**Comment by catscarlet** [comment] 2023-02-26 08:25
> 

Checked with my old projects which have png/jpeg issues.

**The new alpha version works fine. Good**



*Also it seems the alpha version can't change theme. There is no options in Setting.*

**Comment by catscarlet** [comment] 2023-02-26 08:26
> There will be an alpha version of that very soon. You can get it sooner here https://github.com/mltframework/shotcut/actions/runs/4269048303

Checked with my old projects which have png/jpeg issues.

**The new alpha version works fine. Good**

*Also it seems the alpha version can't change theme. There is no options in Setting.*

**Closed** 2023-05-04 03:04 UTC
Labels: Linux, Qt 6
