### ISSUE TITLE
Opening project with one timeline item makes filter use require workaround

### ISSUE THREAD

**Issue by qubodup** [mltframework/shotcut#520] opened 2018-03-13 20:52 UTC
1. Create project
2. Drag media (e.g. image) to source monitor
3. Drag media to timeline
4. Save project
5. Close shotcut
6. Open shotcut
7. Load project
8. Go to filter tab

EXPECTED:
9. Clip is selected in timeline, so it should be possible to add filters

RESULT:
9. Clip has red frame of selection indication but is not registered as selected. Requires clicking around top left corner of the clip in timeline for selection to be established so filters can be added.

NOTES:
This is easier to workaround when multiple clips are in the timeline (simply click another clip to restore normal behavior). Assuming a first-time user might be testing with one clip only, this bug might be very confusing to them.

Win10  Shotcut  18.03.06

Video: https://youtu.be/uy_IyqVBqag

**Comment by ddennedy** [comment] 2018-06-06 23:42
Duplicate of #358

**Closed by ddennedy** 2018-06-06 23:42 UTC
Labels: duplicate, reproduced by dev, workaround
