### ISSUE TITLE
Segmentation Fault when adding a video track to the timeline

### ISSUE THREAD

**Issue by madjestic** [mltframework/shotcut#172] opened 2016-01-02 13:07 UTC
Steps to reproduce:
1) Start Shotcut.
2) Enable the timeline view in the view menu.
3) Put the mouse cursor to the timeline view, RMB and select "Add a Video Track"

Result: Segmentation fault
Expected Result: should not seg.fault.

http://lpaste.net/148288 (terminal output)
http://lpaste.net/148289 (system info)

Cheers,
Vlad

**Comment by ddennedy** [comment] 2016-01-02 17:51
This is a duplicate of #149, which was already fixed. New version due later today.

**Closed by ddennedy** 2016-01-02 17:51 UTC
Labels: duplicate

**Comment by madjestic** [comment] 2016-01-17 17:52
I've updated the system, got latest shotcut and ffmpeg 2.8.5:
$ shotcut -v
[Info   ] <Application::Application(int&, char**)> Starting Shotcut version 16.01.17 
[Info   ] <Application::Application(int&, char**)> Linux version 
[Info   ] <Application::Application(int&, char**)> number of logical cores = 4 
[Info   ] <Application::Application(int&, char**)> locale = QLocale(English, Latin, UnitedStates) 
[Info   ] <Application::Application(int&, char**)> install dir = "/usr/bin" 
[Debug  ] <> language "en_US"
[Debug  ] <> deinterlacer "onefield"
[Debug  ] <> external monitor ""
[Debug  ] <> GPU processing false
[Debug  ] <> interpolation "nearest"
[Debug  ] <> video mode ""
[Debug  ] <> realtime true
Shotcut 16.01.17

I still experience the issue: Segmentation Fault when adding a video track in the Timeline.

**Comment by ddennedy** [comment] 2016-01-17 18:20
Only builds provided by me through shotcut.org or this github project are supported by the developers of this project (of which I am the lead and made that policy decision). More than likely the build you are using does not follow the strict requirements dictated by scripts/build-shotcut.sh. You can report the problem to whoever created your build.

**Comment by madjestic** [comment] 2016-01-27 22:38
Still segfaulting when pressing Ctrl+y in the main window, or inserting a video-track in the timeline:

Shotcut version 16.01.17

media-libs/mlt-9999  
dev-qt/qtcore-5.5.1 
dev-qt/qtgui-5.5.1
dev-qt/qtx11extras-5.5.1
dev-qt/qtsql-5.5.1
dev-qt/qtwebkit-5.5.1-r1
dev-qt/qtquickcontrols-5.5.1-r1
dev-qt/qtnetwork-5.5.1
dev-qt/qtxml-5.5.1
dev-qt/qtopengl-5.5.1
dev-qt/qtwidgets-5.5.1-r1
dev-qt/qtconcurrent-5.5.1
dev-qt/qtmultimedia-5.5.1-r2
dev-qt/qtprintsupport-5.5.1
dev-qt/qtwebsockets-5.5.1-r1
media-video/ffmpeg-2.8.5
media-libs/x264-0.0.20151011
media-libs/libvpx-1.4.0
media-sound/lame-3.99.5-r1
media-plugins/frei0r-plugins-1.3
media-libs/ladspa-sdk-1.13-r2
dev-vcs/git-2.4.10
