### ISSUE TITLE
Defects after loading saved project: crashes, missing features

### ISSUE THREAD

**Issue by littleraskol** [mltframework/shotcut#295] opened 2016-08-13 23:37 UTC
On loading a saved project, the following issues occur:
1. Any tracks marked as composite are no longer composite. This results in, for example, any fade-in or fade-out transparency effects being lost and unable to be restored.
2. Attempting to add a new video track will crash Shotcut. 

I am able to reproduce this by doing the following:
1. Open Shotcut.
2. Add video footage.
3. Create second video track.
4. Place an image on second video track.
5. Add fade in or out filter to cut of image with the transparency option set.
6. Save project.
7. Exit Shotcut.
8. Load project.
9. Note that the composite "button" is no longer highlighted nor can be set on any video track and all transparency in the fade in/out is lost.
10. Attempt to add new video track, at which point it crashes.

Note that the crashing, at least, is independent of any other step besides saving and loading the project. Every single time I load a saved project, if I try to add a video track, Shotcut crashes.

Using 16.8.12. 

I can provide other info as needed. I am really hoping there is some workaround because I lost several hours of work due to this.

**Comment by ddennedy** [comment] 2016-08-13 23:40
Duplicate of https://github.com/mltframework/shotcut/issues/293

**Closed by ddennedy** 2016-08-13 23:40 UTC

**Comment by ddennedy** [comment] 2016-08-13 23:42
From the duplicate bug I just fixed today: The workaround is to first start Shotcut and then use the recent view or File > Open to open the project.
