### ISSUE TITLE
Will not launch in Win10

### ISSUE THREAD

**Issue by brianwall99** [mltframework/shotcut#190] opened 2016-02-02 11:35 UTC
Faulting application name: shotcut.exe, version: 0.0.0.0, time stamp: 0x56af77a3
Faulting module name: msvcrt.dll, version: 7.0.14251.1000, time stamp: 0x56a546c6
Exception code: 0xc0000005
Fault offset: 0x0000000000073ccc
Faulting process ID: 0x18ec
Faulting application start time: 0x01d15d4869343f66
Faulting application path: C:\Program Files\Shotcut\shotcut.exe
Faulting module path: C:\WINDOWS\system32\msvcrt.dll
Report ID: f0e26834-b86b-44c9-906a-6f1f7bd45a62
Faulting package full name: 
Faulting package-relative application ID: 

I used to have it working well on another Win10

Now on insider 1425.rs1.160124.1059

**Comment by ddennedy** [comment] 2016-02-02 16:24
Works for me. Try removing the registry entries at HKEY_CURRENT_USER\Software\Meltytech\Shotcut
Closing this because I do not reproduce it and I cannot fix it.

**Closed by ddennedy** 2016-02-02 16:24 UTC

**Comment by maloner** [comment] 2017-03-05 20:37
I have the same issue - tried installing from scratch on another win10 machine x64 and got exact same issue:

It crashes when I try to open certain mlt files:

Fault bucket 120710578371, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: shotcut.exe
P2: 0.0.0.0
P3: 58b83c11
P4: msvcrt.dll
P5: 7.0.14393.0
P6: 57899b47
P7: c00000fd
P8: 000000000004f2c2
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFDBB.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_shotcut.exe_e6d1a4547717971b62b6f11d535151d14e308579_cb799db7_29f514bd

Analysis symbol: 
Rechecking for solution: 0
Report Id: fd23bebb-8727-4144-abc2-9a2db00fec2b
Report Status: 0
Hashed bucket: 8f22058a70d52d94506be79e92a04820

here is an example mlt that causes the issue: 
[goal_and_risk.zip](https://github.com/mltframework/shotcut/files/819726/goal_and_risk.zip)

**Comment by maloner** [comment] 2017-03-05 20:40
Here is the App Crash Report.wer
[Report.zip](https://github.com/mltframework/shotcut/files/819727/Report.zip)

**Comment by maloner** [comment] 2017-03-05 20:40
And the application log error message:

Faulting application name: shotcut.exe, version: 0.0.0.0, time stamp: 0x58b83c11
Faulting module name: msvcrt.dll, version: 7.0.14393.0, time stamp: 0x57899b47
Exception code: 0xc00000fd
Fault offset: 0x000000000004f2c2
Faulting process id: 0x36c4
Faulting application start time: 0x01d295ef6d0be2b8
Faulting application path: C:\Program Files\Shotcut\shotcut.exe
Faulting module path: C:\WINDOWS\System32\msvcrt.dll
Report Id: fd23bebb-8727-4144-abc2-9a2db00fec2b
Faulting package full name: 
Faulting package-relative application ID:
