### ISSUE TITLE
GPU accelerated encoding fails when using Wayland.

### ISSUE THREAD

**Issue by AbrarSL** [mltframework/shotcut#997] opened 2020-12-30 12:03 UTC
PC Specs,
Core i3 4150
RX 460 2GB
8GB DDR3

Manjaro Linux 20.2 with GNOME.
Shotcut Version ARCH-20.11.14 (Installed via Package Manager)

Output of vainfo.
[vainfo_output.txt](https://github.com/mltframework/shotcut/files/5754126/vainfo_output.txt)

Error log under Wayland.
[shotcut_wayland.txt](https://github.com/mltframework/shotcut/files/5754124/shotcut_wayland.txt)

Log under X11 (Successfully encodes video)
[shotcut_x11.txt](https://github.com/mltframework/shotcut/files/5754129/shotcut_x11.txt)

**Comment by bmatherly** [comment] 2021-01-09 22:45
It is difficult to provide support for packages that we did not create. Can you please download the linux package from here and see if it works better for you?

https://shotcut.org/download/

**Comment by ripper81** [comment] 2021-06-29 16:17
VAAPI seems completely broken on Ubuntu 21.04 in Wayland. This is not directly related to shotcut. I have tested VAAPI on Wayland with KDE Plasma 5.22 and with the Wayland reference compositor Weston. Launching vainfo gives me the following output on two different systems:

heiko@PC-Heiko:~$ vainfo
wl_drm@6: error 0: authenticate failed
VA error: wayland: Wayland roundtrip error: Protocol error (errno 71)
libva info: VA-API version 1.10.0
libva error: vaGetDriverNameByIndex() failed with invalid VADisplay, driver_name = (null)
vaInitialize failed with error code 3 (invalid VADisplay),exit
heiko@PC-Heiko:~$ 

So VAAPI does not work with Wayland in general. I have filed a bug report about the problem here:

https://bugs.launchpad.net/ubuntu/+source/libva/+bug/1931765

**Comment by sudopluto** [comment] 2021-07-07 02:22
having this issue on fedora 34, latest shotcut flatpak, with the vaapi flatpak's installed. going to peek a look

**Comment by ripper81** [comment] 2021-07-07 03:34
> having this issue on fedora 34, latest shotcut flatpak, with the vaapi flatpak's installed. going to peek a look

Here on Kubuntu 21.04 the problem is caused by the MESA driver version used on my system. VAAPI on Wayland works with the MESA 20.0 packages from the official ubunturepos for Ubuntu 21.04.

I use a ppa on my system instead to get the latest stable MESA release 21.1.  Adding this ppa and upgrading the packages leads to VAAPI beeing broken on Wayland. I have tested it on both of my linuxsystems one with an Intel iGPU and one with an AMD Radeon GPU. As soon as i revert to the older MESA build from the ubunturepos VAAPI starts to work again.

It seems that valib is causing this issue when MESA 21.1 is used in combination with wayland.
I installed a newer version of valib and the wayland roundtip error was gone. However unfortunately doing this broke VAAPI on both (X11 and Wayland ). While the roundtip error on Wayland went away all encoding/decoding  entrypoints for VAAPI where gone when excuting vainfo. Even reverting to the old libva did not revert this new problem.

**Comment by abishekmuthian** [comment] 2021-08-23 14:51
Confirming that issue persists in Gnome 40.3.0 using intel_vaapi on intel HD Graphics 620.

**Comment by ripper81** [comment] 2021-08-23 16:37
On my end the problem was solved downgrading to Linux Kernel 5.12. I used 5.13 before which broke VAAPI on Wayland.

**Comment by abishekmuthian** [comment] 2021-08-31 05:36
> On my end the problem was solved downgrading to Linux Kernel 5.12. I used 5.13 before which broke VAAPI on Wayland.

Thanks for the suggestion,  Issue seems to be related with MLT  on Wayland because even Kdenlive has trouble with VAAPI on Wayland.

Unfortunately I'm not comfortable with downgrading kernel for this issue, OpenShot's GPU rendering for both preview and encoding seems to be working fine and I intend to use that temporarily while we investigate the core problem behind this issue.

**Comment by ripper81** [comment] 2021-08-31 07:58
> > On my end the problem was solved downgrading to Linux Kernel 5.12. I used 5.13 before which broke VAAPI on Wayland.
> 
> Thanks for the suggestion, Issue seems to be related with MLT on Wayland because even Kdenlive has trouble with VAAPI on Wayland.
> 
> Unfortunately I'm not comfortable with downgrading kernel for this issue, OpenShot's GPU rendering for both preview and encoding seems to be working fine and I intend to use that temporarily while we investigate the core problem behind this issue.

What happens if you execute vainfo in a terminal? Does it show any entrypoints for decoding or encoding?

**Comment by abishekmuthian** [comment] 2021-09-06 06:09
I have no issues with intel_vaapi as such, I can use HW acceleration through it in all other places where it's applicable (for both encoding and decoding); I have confirmed it through intel_gpu_top  and even in Shotcut it was working fine with KDE/X.Org.

**Comment by abishekmuthian** [comment] 2021-09-17 05:12
Did not get to test MLT directly yet but this is the error after failed HW accelerated encoding using h264_vaapi codec,

Arch Linux 5.14.3 | Upstream GNOME(40.4.0)/Wayland
intel Kabylake Mesa Intel® HD Graphics 620 (KBL GT2)


```
plugin_mgr_get_object_file_plugins: error opening shared object file '/app/extensions/Plugins/ladspa/rdf/tap-plugins.rdf': /app/extensions/Plugins/ladspa/rdf/tap-plugins.rdf: invalid ELF header
plugin_mgr_get_object_file_plugins: error opening shared object file '/app/extensions/Plugins/ladspa/rdf/tap_reverb.rdf': /app/extensions/Plugins/ladspa/rdf/tap_reverb.rdf: invalid ELF header
plugin_mgr_get_object_file_plugins: error opening shared object file '/app/lib/ladspa/ladspa-rubberband.cat': /app/lib/ladspa/ladspa-rubberband.cat: invalid ELF header
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
Gtk-Message: 10:30:29.757: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:30:29.757: Failed to load module "canberra-gtk-module"
[AVHWDeviceContext @ 0x7f83c820d0c0] Opened VA display via X11 display :99.0.
[AVHWDeviceContext @ 0x7f83c820d0c0] libva: VA-API version 1.8.0
[AVHWDeviceContext @ 0x7f83c820d0c0] libva: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[AVHWDeviceContext @ 0x7f83c820d0c0] Failed to initialise VAAPI connection: -1 (unknown libva error).
Failed to create VAAPI device.
[consumer avformat] Failed to initialize VA-API: -5
[h264_vaapi @ 0x7f83c8201dc0] A hardware frames reference is required to associate the encoding device.
Failed with exit code 11
Failed with exit code 11
```

vainfo

```
vainfo: VA-API version: 1.12 (libva 2.12.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.3.2 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
```

Results are same irrespective of whether shotcut was installed from git, flatpack, snap or AppImage.

**Comment by sudopluto** [comment] 2022-01-27 04:54
should be fixed on master, debaf54c6fa7a3c081a0a918812de8dbcdb7fda6

**Comment by abishekmuthian** [comment] 2022-01-27 05:07
Thank you @sudopluto, it would be part of next release?

**Comment by sudopluto** [comment] 2022-01-27 13:00
thank dan for getting it in so quick. it should be on the next release, i would use the flatpak version since some 3rd party packagers disable wayland. in the mean time, you can use the patched version here: https://github.com/flathub/org.shotcut.Shotcut/pull/50#issuecomment-1022843218

**Comment by abishekmuthian** [comment] 2022-01-27 13:22
Thanks @ddennedy . Would give it a whirl soon and report.

**Closed** 2022-01-27 15:53 UTC
