### ISSUE TITLE
recovered autosave leaves autosave path 

### ISSUE THREAD

**Issue by CarlFK** [mltframework/shotcut#233] opened 2016-04-29 04:14 UTC
filename t1a.mlt, , crash, restart, "restore autosave?", yes, [1] save, exit.
start SC, open file, svg title image says INVALID.
close, vim t1a.mlt, see this:
`<property name="resource">/home/carl/.local/share/Meltytech/Shotcut/autosave/theharpist_title.svg</property>`

[1] I am not sure if the svg was shown at this point.  

happy to poke around and try to provide more details if needed.

**Comment by ddennedy** [comment] 2016-04-29 04:20
It appears that auto saved XML files are not resolving relative paths correctly. That is going to be tricky as there is not anything saved in the auto saved file to help with that currently. I think I need to tell auto save not to use relative paths...

**Comment by CarlFK** [comment] 2016-04-29 04:27
If it helps, the svg and mlt were both in the same dir.

On Thu, Apr 28, 2016 at 11:20 PM, Dan Dennedy <notifications@github.com>
wrote:

> It appears that auto saved XML files are not resolving relative paths
> correctly. That is going to be tricky as there is not anything saved in the
> auto saved file to help with that currently. I think I need to tell auto
> save not to use relative paths...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mltframework/shotcut/issues/233#issuecomment-215623303>
>



-- 
Carl K

**Comment by ddennedy** [comment] 2016-04-29 05:15
On second thought, since the asset (SVG) does not reside in the same folder as the auto-saved XML, it will not save with a relative path. I was not able to reproduce the problem using a video or SVG file. So, I am not sure what the problem is. Somehow, the auto-saved XML got tricked into using relative paths when it should not.

**Closed** 2016-04-29 05:23 UTC

**Comment by ddennedy** [comment] 2016-04-29 05:26
In any case, this is very similar to an issue many people reported when encoding which saves XML to a temp file in $TMP, and the resolution for that was to force using full paths. I never reproduced that problem either, but the solution thus far appears to be to force usage of absolute paths in the temp file. I applied the same solution here. However, when you save a recovered XML, it will convert back to relative paths for assets in the same folder or a sub-folder.
