### ISSUE TITLE
Shotcut 18.06.01 crashes when dragging video to timeline

### ISSUE THREAD

**Issue by qubodup** [mltframework/shotcut#580] opened 2018-06-02 08:09 UTC
Dragging a certain video to the source view and then from there to the timeline crashes Shotcut.

File: http://www.mediafire.com/file/2r8pb2xmfqxwq32/161212_Cut_069_Vietnam_1080p96fps.mp4/file

Demo: https://youtu.be/TpgZjJxiaWk

Happens in 18.06.01. Does not happen in 18.05.08.

Command line output:

```
[Debug  ] <TimelineDock::dragEnterEvent> true
[Debug  ] <Timeline::OverwriteCommand::redo> trackIndex 0 position -1
[Warning] <> QQmlExpression: Expression file:///C:/Software/shotcut-win64-180601/Shotcut/share/shotcut/qml/timeline/TrackHead.qml:104:27 depends on non-NOTIFYable properties:
[Warning] <>     TimelineDock::floating
[h264 @ 000000001ca17e00] Reinit context to 1920x1088, pix_fmt: yuv420p
[h264 @ 000000001e64e840] Reinit context to 1920x1088, pix_fmt: yuv420p
[h264 @ 000000001674fb80] Reinit context to 1920x1088, pix_fmt: yuv420p
[h264 @ 000000001ca17940] Reinit context to 1920x1088, pix_fmt: yuv420p
[h264 @ 000000001ca1d000] Reinit context to 1920x1088, pix_fmt: yuv420p
[h264 @ 000000001ca194c0] Reinit context to 1920x1088, pix_fmt: yuv420p
[h264 @ 000000001ca1e240] Reinit context to 1920x1088, pix_fmt: yuv420p
[h264 @ 000000001c7bcb80] Reinit context to 1920x1088, pix_fmt: yuv420p
[h264 @ 000000001c7bddc0] Reinit context to 1920x1088, pix_fmt: yuv420p
[Debug  ] <TimelineDock::setSelection> Changing selection to (0)  trackIndex -1 isMultitrack false
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <AudioLevelsTask::tempProducer> generating audio levels for E:/VidIn/StockNoAttribution/161212_Cut_069_Vietnam_1080p96fps.mp4
[h264 @ 000000001c7b9980] Reinit context to 1920x1088, pix_fmt: yuv420p
[Debug  ] <MLT> [mlt_producer avformat-novalidate] "E:/VidIn/StockNoAttribution/161212_Cut_069_Vietnam_1080p96fps.mp4" checking VFR: pkt.duration %I64d
Segmentation fault
```

**Comment by ddennedy** [comment] 2018-06-02 14:18
Duplicate of #579. A version 18.06.02 is going up today.

**Closed by ddennedy** 2018-06-02 14:18 UTC
Labels: duplicate
