### ISSUE TITLE
Upgrade to Shotcut version 16.06.08: two clicks needed on a menu link to display a sub-menu

### ISSUE THREAD

**Issue by chrisave** [mltframework/shotcut#261] opened 2016-06-15 13:20 UTC
After having upgraded to the latest Shotcut version, it appears now that a first-level menu label often has to be clicked twice in order to see its sub-menu displayed.
It's the same within the html editor.
The second click can be made several seconds after the first one.

Shotcut version 16.06.08
Linux Mint 17.3 Rosa 64-bit (with Mate)

**Comment by ddennedy** [comment] 2016-06-15 14:44
Duplicate of #238 
Nothing changed in this version over version 16.05 that would have causes this. I think it affects some Linux users, perhaps only some times since you are reporting it as a new problem.

**Comment by ddennedy** [comment] 2016-06-15 15:17
Closing as not-my-bug. It is a bug in the version of Qt we are using, and no, it cannot be simply upgraded at this time.

**Closed by ddennedy** 2016-06-15 15:17 UTC
Labels: duplicate
