### ISSUE TITLE
Crash when importing images on Windows with JACK enabled

### ISSUE THREAD

**Issue by svejdam** [mltframework/shotcut#167] opened 2015-12-20 19:05 UTC
Hi,
im running windows 7 Ultimate on my Lenovo G510 with dual graphics (Intel HD + Radeon HD 8750M). Whenever I try to import images (no matter if jpeg, png and drag-n-drop or import method) Shotcut crashes. I tried to force discrete graphics to run Shotcut, I tried to switch on/off GPU processing, choosing different display methods with no effect. Help please.

I greatly appreciate your work on this cool project :)

**Comment by ddennedy** [comment] 2015-12-21 01:34
It works for me. Is this problem limited to image files, or does it also affect video and audio files? Leave GPU processing off, and try each option under Settings > Display Method.

**Comment by svejdam** [comment] 2015-12-21 07:05
Thank for your response.
It also works for me on other computers running win7 but on my laptop keeps crashing no matter if GPU processing is enabled and no matter on display method. Video importing works with no problem, just image files does this. I guess it will be somehow connected with that dual graphics.
I have the latest version of Shotcut and Windows 7 updated.

**Comment by ddennedy** [comment] 2015-12-23 21:57
Shotcut on Windows tries to force the use of a discrete NVIDIA or AMD GPU.
You should also test using File > Open and not just drag-n-drop. Thanks

"Pending" status means I might close this after a couple months if no one else is reporting it, no dev can reproduce it, or no one contributes the fix.

**Comment by svejdam** [comment] 2015-12-26 20:16
Hey,
I discovered that the problem was caused by feature Use jack Audio which I checked when trying something. When I ucheck this feature image importing works fine :)

So glad I can keep on discovering this cool app :)

Thanks for your responses!

**Comment by ddennedy** [comment] 2016-01-07 16:58
On my Windows 7 system without JACK installed, simply trying to open anything crashes.

**Comment by ddennedy** [comment] 2016-01-23 21:37
This is crashing on _getopt_internal() inside of jack_client_open() inside of MLT. This is the very first call to Jack, and it's result indicates success or failure. At the command line `melt noise: -attach jackrack -consumer null` returns `unknown option character ?` further supporting something fishy and wrong going on inside of Jack. I tried some different arguments to the jack_client_open() call with no success. This might be an issue with the version of Jack we are using.
In the meantime, one should only use this Shotcut setting if you actually have Jack installed and running. However, someone not knowing what this option is and just fiddling with all of the knobs may end up putting Shotcut into an usable state. I am going to remove this option on Windows.

**Closed** 2016-01-23 21:56 UTC
Labels: crash, reproduced by dev, Windows
