### ISSUE TITLE
Shotcut Crashes When Changing Speed in Properties

### ISSUE THREAD

**Issue by forkytheorc** [mltframework/shotcut#403] opened 2017-03-27 13:16 UTC
Shotcut crashes when changing the speed in properties. 

Replicate;
 - Get multiple cuts from one file, change the speed of one of the cuts. (in my case i had two cuts of the same time, one in normal speed then one i tried to change to 0.5x)
- Slow the speed of one of the cuts.
- Move playhead to the slowed cut. 
- Shotcut Crashes.

**Comment by ddennedy** [comment] 2017-03-28 02:26
Works for me. Specify your version of Shotcut and OS.

**Comment by bluehippo45** [comment] 2017-03-28 05:38
This is happening to me too. Im editing a gaming video and i want it to slow down whenever i die for a more dramatic but comedic effect. So i cut the clip two times, i select it, change the speed and then it crashes. I'm running 17.03 version of shotcut and i have Windows 10 Home 64 Bit. Hopefully this problem gets resolved as it seems to be the biggest issue here

**Comment by forkytheorc** [comment] 2017-03-28 07:57
I am also using 17.03.02 64bit version and Windows 10 Home 64bit. I am also trying to edit gaming videos from NVIDIA Shadow Play. It has worked fine in the past.

**Comment by ddennedy** [comment] 2017-03-29 03:25
Does the file you are trying to use have variable frame rate? That is not supported, but we do not yet have a way to detect that and prevent using it. You can use the program MediaInfo to find out. Can you share one of your smaller files that exhibits the problem? If so, it will not be shared, and you can upload it to https://shotcut.org/notes/support-upload/.

**Comment by tin2tin** [comment] 2017-03-30 07:58
[I think I found an explanation on how MediaInfo determines if a file is VFR or not: https://sourceforge.net/p/mediainfo/discussion/297610/thread/b2a2708d/ ]

**Comment by ReachesHigh** [comment] 2017-04-22 20:04
I have this issue as well, I have Windows 10 Version 10.0.14393 Build 14393. Shotcut version 17.04. I also used shadowplay to record, so I wonder if something with that causes the problem. For me, I can decrease the video speed but once I get to 0.50 speed if on a cut out portion of the video it crashed. If I try to slow down the whole video it crashes around 0.30.

**Comment by forkytheorc** [comment] 2017-04-23 04:11
Shadowplay encodes as variable bitrate. So as above; Shotcut does not support variable bit rate (in fact most video editing software doesn't). 

I instead use Handbrake to get the snippets out I want and re-encode to constant bitrate (lossless) then edit, stitch, slowmo, funny music, whatever in shotcut and output a file for youtube.

**Comment by Schyrsivochter** [comment] 2017-04-23 10:01
Variable _frame_ rate, not bitrate. There’s a huge difference.

**Comment by forkytheorc** [comment] 2017-04-24 03:51
Yes, my bad, I updated my comment.

**Comment by Steini-** [comment] 2019-01-08 22:50
Hi, i'm running Shotcut (18.12.23) on Ubuntu 16.04 LTS and it crashes on a regular basis if i try to speed down a videofile. I tried it via video -> properties and then playing with the speed numbers. I could not circumvent this and this is quite a fresh installation. I think it would be nice if this bug could be fixed soon, maybe this affects more people then just the few ones who're following this bug report

**Comment by ddennedy** [comment] 2019-01-08 23:54
@Steini- Is your video variable frame rate? Shotcut tries to detect it and shows "(variable)" next to the frame rate in Properties, but it is a simple heuristic and not foolproof detection. Using MediaInfo to check it as well is helpful. This is still open because developers have not reproduced it.

**Comment by Steini-** [comment] 2019-01-09 00:43
@ddennedy i looked it up: i had three videos in my media list. Everyone had a different frame rate, so maybe shotcut stumpled upon the thing, when i tried to reduce the speed to 0.9
Maybe it was not clear for shotcut 0.9 from what media file, because they all had a different frame rate, so 0.9 with three different values lead to three different target values.
But a variable frame rate was not displayed, they all had distinct values, ex. 29.97

**Comment by ddennedy** [comment] 2019-01-09 02:17
Shotcut can only change the speed of a single clip at-a-time, whichever one is selected if the player is in Project mode or the clip loaded in Source if the player is in Source mode. Can you explain which mode you are in or show a screenshot of the Properties panel just prior to changing the speed?

**Comment by Steini-** [comment] 2019-01-09 12:54
@ddennedy as i tried to reproduce the faulty behavour of shotcut, i was not able to do so. But i had these issues yesterday multiple times. I will try on and if i'm successful i'll try to give a better error description on that issue.

**Comment by ddennedy** [comment] 2019-05-06 22:01
Fixed in daf880428bae327e97b504e1eabf1347b1c5b907

**Closed by ddennedy** 2019-05-06 22:01 UTC

**Comment by ddennedy** [comment] 2019-12-14 06:57
There was another fix for this in https://github.com/mltframework/mlt/commit/dbcf710043bb6f33ff815d049e781689516c7e6b that will be included in the project-provided builds for the release version 19.12.

**Comment by ddennedy** [comment] 2020-09-09 23:43
There was another fix for this in https://github.com/mltframework/mlt/pull/606
