### ISSUE TITLE
Image sequence not working

### ISSUE THREAD

**Issue by frspp** [mltframework/shotcut#1035] opened 2021-02-10 16:10 UTC
Hi!

I cannot get any life out of image sequence.

- Create new project
- Click open file
- Choose first image (.jpg for me), open
- Go to properties
- Check "image sequence"
- It loads a for few seconds "Reloading image sequence"
- Then what? Nothing happens. Pressing play does nothing. Dragging to timeline does not import anything.

The folder where first file is chosen contains 384 .jpg at 2,3MB each. 

Shotcut 21.01.29
macos 11.2
Arm M1 mac

**Comment by ddennedy** [comment] 2021-02-10 17:19
How are the files named?

**Comment by Gizemquea** [comment] 2021-02-10 19:04
Sorry to post in a another issue, but I might still have something to contribute: This seems to be the same behavior as #1030 - except that the reporter here does not mention trying to save the project after dragging to timeline and opening it in a new instance of shotcut to get things working.

The exact naming of the files does not seem to matter, I observed the behavior with different prefixes and a differnt number of digits in the file names, in my most recent example this was something like G0020001.JPG - G00201732.JPG - but I was never able to get this working by any other means than saving and then closing the unresponsive application.

**Comment by ddennedy** [comment] 2021-02-10 21:51
Unable to reproduce. I used M1 Mac mini with macOS 11.2 running Shotcut 21.01.29. I created the image sequence using Shotcut by Open video > Export > stills/JPEG preset > Export File. This created a sequence of 991 1920x1080 JPEG files. Then, I followed your steps using Video mode = Automatic in the New Project view. That creates a project at 1920x1080 25 fps.

**Comment by ddennedy** [comment] 2021-02-11 02:11
I am confident this is the same as #1030, which I reproduced as well on macOS. So, closing this as duplicate and please track the other.

**Closed by ddennedy** 2021-02-11 02:11 UTC
Labels: pending

**Comment by frspp** [comment] 2021-02-11 13:34
> How are the files named?

sula 20210210 1049 G0035746.JPG
sula 20210210 1050 G0035747.JPG
...

IMO just take all the files in the folder, do not care about the names. Or at least have option to just take all the files, not trying to recognize from name.

**Comment by frspp** [comment] 2021-02-11 13:50
Here is screen capture https://youtu.be/tr8Y0ZUWGUc

**Comment by ddennedy** [comment] 2021-02-11 21:33
Part of what was found in #1030 was a deadlock immediately after clicking the check box, and that is what you described: "Pressing play does nothing. Dragging to timeline does not import anything."

The file names do matter - not with respect to this bug but with respect to the resulting duration. I tested with your names, and Shotcut determines the base of the image sequence name is "sula 20210210 1049 " followed by a 5 digit number. You have 3 sets of changing numbers, but the software does not understand your scheme (and neither do I except the first one I can guess is a date). I will not be changing it to take all files in a folder and order them by date created or modified. People do not always organize files well, dates get clobbered, or some images get processed. You can easily rename them to be sensible. Sure, these might be nice options, but we only use this area for hard defect tracking and not feature requests.

**Comment by frspp** [comment] 2021-02-12 09:34
> Part of what was found in #1030 was a deadlock immediately after clicking the check box, and that is what you described: "Pressing play does nothing. Dragging to timeline does not import anything."
Ok thanks for the reply. 

> The file names do matter - not with respect to this bug but with respect to the resulting duration. I tested with your names, and Shotcut determines the base of the image sequence name is "sula 20210210 1049 " followed by a 5 digit number. You have 3 sets of changing numbers, but the software does not understand your scheme (and neither do I except the first one I can guess is a date). 
Format is: text YYYYMMDD HHMM Currentfilename.
- text is description
- Date Time to keep files in order - and to actually read that information
- Sometimes Time is not saved so Currentfilename is used as backup to keep files in order 
- Date Time in filename is very useful in other applications. And very useful in case meta gets lost. 

> I will not be changing it to take all files in a folder and order them by date created or modified. People do not always organize files well, dates get clobbered, or some images get processed.  
How I expect it to work: Take all files in folder and order by name, no matter what the name is. 

But it works otherwise so **somewhere in the Shotcut UI should be description how image sequence works.** Like "Detects automatically sequence by file name. File name should be short and simple, only one running number. For example file000213.jpg."
