### ISSUE TITLE
Edit: Crash when using .flv video

### ISSUE THREAD

**Issue by drocks13** [mltframework/shotcut#205] opened 2016-03-12 23:44 UTC
Shotcut crashed when I was deleting a track. Here is the log file-

[Info   ] <Application::Application(int&, char**)> Starting Shotcut version 16.03.01 
[Info   ] <Application::Application(int&, char**)> Windows version 192 
[Info   ] <Application::Application(int&, char**)> number of logical cores = 8 
[Info   ] <Application::Application(int&, char**)> locale = QLocale(English, Default, UnitedKingdom) 
[Info   ] <Application::Application(int&, char**)> install dir = "C:/Program Files/Shotcut" 
[Debug  ] <> begin
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> begin
[Info   ] <MLT> plugin_mgr_get_object_file_plugins: error opening shared object file '\Program Files\Shotcut\lib\ladspa/AUTHORS': "\Program Files\Shotcut\lib\ladspa\AUTHORS": The specified module could not be found.
[Info   ] <MLT> plugin_mgr_get_object_file_plugins: error opening shared object file '\Program Files\Shotcut\lib\ladspa/COPYING': "\Program Files\Shotcut\lib\ladspa\COPYING": The specified module could not be found.
[Info   ] <MLT> plugin_mgr_get_object_file_plugins: error finding ladspa_descriptor symbol in object file '\Program Files\Shotcut\lib\ladspa/libfftw3f-3.dll': "ladspa_descriptor": The specified procedure could not be found.
[Info   ] <MLT> plugin_mgr_get_object_file_plugins: error opening shared object file '\Program Files\Shotcut\lib\ladspa/readme.txt': "\Program Files\Shotcut\lib\ladspa\readme.txt": 
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> end
[Debug  ] <> begin
[Error  ] <MLT> [ 0xa5c7818] The DeckLink drivers not installed.
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> setting to profile "Automatic"
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> begin true
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> end
[Debug  ] <> begin true
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> end
[Debug  ] <> begin true
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> end
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> end
[Warning] <> QSslSocket: cannot resolve TLSv1_1_client_method
[Warning] <> QSslSocket: cannot resolve TLSv1_2_client_method
[Warning] <> QSslSocket: cannot resolve TLSv1_1_server_method
[Warning] <> QSslSocket: cannot resolve TLSv1_2_server_method
[Warning] <> QSslSocket: cannot resolve SSL_select_next_proto
[Warning] <> QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb
[Warning] <> QSslSocket: cannot resolve SSL_get0_next_proto_negotiated
[Debug  ] <> 
[Debug  ] <> end
[Debug  ] <> Database version is 1
[Debug  ] <> 
[Debug  ] <> reading filter metadata "alpha_adjust" "meta.qml"
[Debug  ] <> added filter "Alpha Channel: Adjust"
[Debug  ] <> reading filter metadata "alpha_view" "meta.qml"
[Debug  ] <> added filter "Alpha Channel: View"
[Debug  ] <> reading filter metadata "audio_balance" "meta.qml"
[Debug  ] <> added filter "Balance"
[Debug  ] <> reading filter metadata "audio_bandpass" "meta.qml"
[Debug  ] <> added filter "Band Pass"
[Debug  ] <> reading filter metadata "audio_basstreble" "meta.qml"
[Debug  ] <> added filter "Bass & Treble"
[Debug  ] <> reading filter metadata "audio_channelcopy" "meta.qml"
[Debug  ] <> added filter "Copy Channel"
[Debug  ] <> reading filter metadata "audio_compressor" "meta.qml"
[Debug  ] <> added filter "Compressor"
[Debug  ] <> reading filter metadata "audio_delay" "meta.qml"
[Debug  ] <> added filter "Delay"
[Debug  ] <> reading filter metadata "audio_expander" "meta.qml"
[Debug  ] <> added filter "Expander"
[Debug  ] <> reading filter metadata "audio_fadein" "meta.qml"
[Debug  ] <> added filter "Fade In Audio"
[Debug  ] <> reading filter metadata "audio_fadeout" "meta.qml"
[Debug  ] <> added filter "Fade Out Audio"
[Debug  ] <> reading filter metadata "audio_gain" "meta.qml"
[Debug  ] <> added filter "Gain / Volume"
[Debug  ] <> reading filter metadata "audio_highpass" "meta.qml"
[Debug  ] <> added filter "High Pass"
[Debug  ] <> reading filter metadata "audio_limiter" "meta.qml"
[Debug  ] <> added filter "Limiter"
[Debug  ] <> reading filter metadata "audio_loudness" "meta.qml"
[Debug  ] <> added filter "Normalize"
[Debug  ] <> reading filter metadata "audio_lowpass" "meta.qml"
[Debug  ] <> added filter "Low Pass"
[Debug  ] <> reading filter metadata "audio_mono" "meta.qml"
[Debug  ] <> added filter "Downmix"
[Debug  ] <> reading filter metadata "audio_mute" "meta.qml"
[Debug  ] <> added filter "Mute"
[Debug  ] <> reading filter metadata "audio_notch" "meta.qml"
[Debug  ] <> added filter "Notch"
[Debug  ] <> reading filter metadata "audio_pan" "meta.qml"
[Debug  ] <> added filter "Pan"
[Debug  ] <> reading filter metadata "audio_reverb" "meta.qml"
[Debug  ] <> added filter "Reverb"
[Debug  ] <> reading filter metadata "audio_swapchannels" "meta.qml"
[Debug  ] <> added filter "Swap Channels"
[Debug  ] <> reading filter metadata "bluescreen0r" "meta.qml"
[Debug  ] <> added filter "Chroma Key: Simple"
[Debug  ] <> reading filter metadata "blur" "meta_boxblur.qml"
[Debug  ] <> added filter "Blur"
[Debug  ] <> reading filter metadata "blur" "meta_movit.qml"
[Debug  ] <> added filter "Blur"
[Debug  ] <> reading filter metadata "color" "meta.qml"
[Debug  ] <> added filter "Color Grading"
[Debug  ] <> reading filter metadata "color" "meta_frei0r_coloradj.qml"
[Debug  ] <> added filter "Color Grading"
[Debug  ] <> reading filter metadata "color" "meta_movit.qml"
[Debug  ] <> added filter "Color Grading"
[Debug  ] <> reading filter metadata "crop" "meta.qml"
[Debug  ] <> added filter "Crop"
[Debug  ] <> reading filter metadata "crop" "meta_movit.qml"
[Debug  ] <> added filter "Crop"
[Debug  ] <> reading filter metadata "dust" "meta.qml"
[Debug  ] <> added filter "Old Film: Dust"
[Debug  ] <> reading filter metadata "dynamictext" "meta.qml"
[Debug  ] <> added filter "Text"
[Debug  ] <> reading filter metadata "fadein_brightness" "meta.qml"
[Debug  ] <> added filter "Fade In Video"
[Debug  ] <> reading filter metadata "fadein_movit" "meta.qml"
[Debug  ] <> added filter "Fade In Video"
[Debug  ] <> reading filter metadata "fadeout_brightness" "meta.qml"
[Debug  ] <> added filter "Fade Out Video"
[Debug  ] <> reading filter metadata "fadeout_movit" "meta.qml"
[Debug  ] <> added filter "Fade Out Video"
[Debug  ] <> reading filter metadata "glow" "meta_frei0r.qml"
[Debug  ] <> added filter "Glow"
[Debug  ] <> reading filter metadata "glow" "meta_movit.qml"
[Debug  ] <> added filter "Glow"
[Debug  ] <> reading filter metadata "grain" "meta.qml"
[Debug  ] <> added filter "Old Film: Grain"
[Debug  ] <> reading filter metadata "invert" "meta.qml"
[Debug  ] <> added filter "Invert Colors"
[Debug  ] <> reading filter metadata "keyspillm0pup" "meta.qml"
[Debug  ] <> added filter "Key Spill: Advanced"
[Debug  ] <> reading filter metadata "lines" "meta.qml"
[Debug  ] <> added filter "Old Film: Scratches"
[Debug  ] <> reading filter metadata "mirror" "meta.qml"
[Debug  ] <> added filter "Mirror"
[Debug  ] <> reading filter metadata "mirror" "meta_movit.qml"
[Debug  ] <> added filter "Mirror"
[Debug  ] <> reading filter metadata "movit_diffusion" "meta.qml"
[Debug  ] <> added filter "Diffusion"
[Debug  ] <> reading filter metadata "oldfilm" "meta.qml"
[Debug  ] <> added filter "Old Film: Projector"
[Debug  ] <> reading filter metadata "opacity" "meta.qml"
[Debug  ] <> added filter "Opacity"
[Debug  ] <> reading filter metadata "opacity" "meta_movit.qml"
[Debug  ] <> added filter "Opacity"
[Debug  ] <> reading filter metadata "rotate" "meta.qml"
[Debug  ] <> added filter "Rotate"
[Debug  ] <> reading filter metadata "saturation" "meta_frei0r.qml"
[Debug  ] <> added filter "Saturation"
[Debug  ] <> reading filter metadata "saturation" "meta_movit.qml"
[Debug  ] <> added filter "Saturation"
[Debug  ] <> reading filter metadata "select0r" "meta.qml"
[Debug  ] <> added filter "Chroma Key: Advanced"
[Debug  ] <> reading filter metadata "sepia" "meta.qml"
[Debug  ] <> added filter "Sepia Tone"
[Debug  ] <> reading filter metadata "sharpen" "meta_frei0r.qml"
[Debug  ] <> added filter "Sharpen"
[Debug  ] <> reading filter metadata "sharpen" "meta_movit.qml"
[Debug  ] <> added filter "Sharpen"
[Debug  ] <> reading filter metadata "size_position" "meta_affine.qml"
[Debug  ] <> added filter "Size and Position"
[Debug  ] <> reading filter metadata "size_position" "meta_movit.qml"
[Debug  ] <> added filter "Size and Position"
[Debug  ] <> reading filter metadata "spillsuppress" "meta.qml"
[Debug  ] <> added filter "Key Spill: Simple"
[Debug  ] <> reading filter metadata "stabilize" "meta.qml"
[Debug  ] <> added filter "Stabilize"
[Debug  ] <> reading filter metadata "tcolor" "meta.qml"
[Debug  ] <> added filter "Old Film: Technocolor"
[Debug  ] <> reading filter metadata "vignette" "meta_movit.qml"
[Debug  ] <> added filter "Vignette"
[Debug  ] <> reading filter metadata "vignette" "meta_oldfilm.qml"
[Debug  ] <> added filter "Vignette"
[Debug  ] <> reading filter metadata "wave" "meta.qml"
[Debug  ] <> added filter "Wave"
[Debug  ] <> reading filter metadata "webvfx" "meta.qml"
[Debug  ] <> added filter "Overlay HTML"
[Debug  ] <> reading filter metadata "webvfx_circular_frame" "meta.qml"
[Debug  ] <> added filter "Circular Frame (HTML)"
[Debug  ] <> reading filter metadata "webvfx_ruttetraizer" "meta.qml"
[Debug  ] <> added filter "Rutt-Etra-Izer (HTML)"
[Debug  ] <> reading filter metadata "webvfx_threejs_text" "meta.qml"
[Debug  ] <> added filter "3D Text (HTML)"
[Debug  ] <> reading filter metadata "white" "meta_frei0r.qml"
[Debug  ] <> added filter "White Balance"
[Debug  ] <> reading filter metadata "white" "meta_movit.qml"
[Debug  ] <> added filter "White Balance"
[Warning] <> libpng warning: iCCP: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG
[Debug  ] <> "C:/Users/doug/AppData/Local/Meltytech/Shotcut/__untitled__.mlt"
[Debug  ] <> decimal point '.'
[Debug  ] <> begin
[Debug  ] <> end
[Debug  ] <> Disconnected from Leap Motion
[Debug  ] <> Leap Motion WebSocket error: "Connection refused"
[Debug  ] <> "D:/2016 CAAUK/Louis Rayne/Louis Rayne.mlt"
[Debug  ] <> decimal point '.'
[Debug  ] <> begin
[Debug  ] <> end
[Debug  ] <> begin
[Debug  ] <> OpenGL vendor "Google Inc."
[Debug  ] <> OpenGL renderer "ANGLE ( Direct3D11 vs_5_0 ps_5_0)"
[Debug  ] <> OpenGL threaded? false
[Debug  ] <> OpenGL ES? true
[Debug  ] <> end
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 0 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 0 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <> running
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <> running
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <> Changing selection to ()
[Debug  ] <> running
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <> Changing selection to ()
[Debug  ] <> running
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <> running
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:79:20: Unable to assign [undefined] to double
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:78:19: Unable to assign [undefined] to QString
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 0 total_channels 2 max_channels 2
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:101: ReferenceError: timeline is not defined
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 0 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 0 total_channels 2 max_channels 2
[Debug  ] <> Changing selection to ()
[Debug  ] <> running
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 0 total_channels 2 max_channels 2
[Debug  ] <> Changing selection to (5)
[Debug  ] <> Changing selection to ()
[Debug  ] <> 0
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <> running
[Debug  ] <> 0
[Debug  ] <> 0
[Debug  ] <> running
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <> running
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:79:20: Unable to assign [undefined] to double
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:78:19: Unable to assign [undefined] to QString
[Debug  ] <> Changing selection to ()
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:79:20: Unable to assign [undefined] to double
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:78:19: Unable to assign [undefined] to QString
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:77:22: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:76:21: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:71:27: Unable to assign [undefined] to bool
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:69:22: Unable to assign [undefined] to bool
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:68:23: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:67:22: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:66:25: Unable to assign [undefined] to QString
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:64:27: Unable to assign [undefined] to QString
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:79:20: Unable to assign [undefined] to double
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:78:19: Unable to assign [undefined] to QString
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:77:22: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:76:21: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:71:27: Unable to assign [undefined] to bool
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:69:22: Unable to assign [undefined] to bool
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:68:23: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:67:22: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:66:25: Unable to assign [undefined] to QString
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:64:27: Unable to assign [undefined] to QString
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:79:20: Unable to assign [undefined] to double
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:78:19: Unable to assign [undefined] to QString
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:77:22: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:76:21: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:71:27: Unable to assign [undefined] to bool
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:70:22: Unable to assign [undefined] to bool
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:69:22: Unable to assign [undefined] to bool
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:68:23: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:67:22: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:66:25: Unable to assign [undefined] to QString
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:65:27: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:64:27: Unable to assign [undefined] to QString
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:63:23: Unable to assign [undefined] to QString
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Clip.qml:120:5: QML Image: Failed to get image from provider: image://thumbnail///#0
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Clip.qml:107:5: QML Image: Failed to get image from provider: image://thumbnail///#0
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Clip.qml:120:5: QML Image: Failed to get image from provider: image://thumbnail///#0
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Clip.qml:107:5: QML Image: Failed to get image from provider: image://thumbnail///#0
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:79:20: Unable to assign [undefined] to double
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:78:19: Unable to assign [undefined] to QString
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:77:22: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:76:21: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:71:27: Unable to assign [undefined] to bool
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:69:22: Unable to assign [undefined] to bool
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:68:23: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:67:22: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:66:25: Unable to assign [undefined] to QString
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:64:27: Unable to assign [undefined] to QString
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:79:20: Unable to assign [undefined] to double
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:78:19: Unable to assign [undefined] to QString
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:77:22: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:76:21: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:71:27: Unable to assign [undefined] to bool
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:70:22: Unable to assign [undefined] to bool
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:69:22: Unable to assign [undefined] to bool
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:68:23: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:67:22: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:66:25: Unable to assign [undefined] to QString
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:65:27: Unable to assign [undefined] to int
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:64:27: Unable to assign [undefined] to QString
[Warning] <> file:///C:/Program Files/Shotcut/share/shotcut/qml/timeline/Track.qml:63:23: Unable to assign [undefined] to QString

**Comment by ddennedy** [comment] 2016-03-13 00:45
I am not able to reproduce this. It might be something in your project. With a way to reproduce it, there is not enough information to debug it. I will leave it open for a while to see if more information becomes available - possibly from others.

**Comment by drocks13** [comment] 2016-03-13 00:57
What sort of information can I provide to help you reproduce it?

**Comment by ddennedy** [comment] 2016-03-13 01:05
Is it repeatable with a new, small project? If so, list your steps. If not, adding what makes it fail? For example, a particular filter attached to a clip? You can also attach a project file, but the more complicated it is, the less likely someone is willing to use it.

**Comment by drocks13** [comment] 2016-03-13 01:21
Ah ok. So it has now crashed in several different ways- when removing a track, when clicking on a track, when moving a video over another video to create a transition, when moving a video to an audio channel. At this point it has crashed in so many different ways that I can't tell what actions cause it to crash other than all of them. 

The setup is as follows I have two video file (.flv) to create two tracks. On one video I have  used the crop filter to cut out the black spaces and then use the position filter (on that same video) to move it so it have a picture and picture effect with the other track (the other track has no filters on it). I have .png images as intros and outros. That is about it. As per the FAQ I have tried setting it to DirectX and OpenGL. Both seem to cause it to crash randomly. It is a windows 10 pc with i7 and a Geforce GTX 960m GPU. Let me know if you need more detailed information. Project file is attached - by project file I assumed you mean the .mlt file.
[project file.zip](https://github.com/mltframework/shotcut/files/170700/project.file.zip)

**Comment by drocks13** [comment] 2016-03-20 11:38
I have managed to replicate this same crash issue with kdenlive. So possible the issue might be with MLT or the frei0r plugins that are causing it to crash. So issues maynot be with Shotcut but the under lying frameworks.

**Comment by drocks13** [comment] 2016-03-21 13:44
I have mannaged to track down the issue, I think- it crashes because of a runtime error. I was using .flv video and there is some error with runtime sending the wrong information that causes the program to crash. Sorry, I can't be more detailed than that. I only found it using while OpenShot, which uses the MLT framework (testing different programs that use MLT to seem if I could find the issue with that), when the same sort of crash happened but its error reporting gave me a generic error about runtime. Converting my flash video to a diffierent format seems to have solved the problem in Shotcut so I suspect it is a runtime error.

**Comment by ddennedy** [comment] 2016-05-31 17:09
I have a FLV file that I use frequently while testing, and I have not experienced this problem. Perhaps the problem is specific to your particular file. I am still unable to reproduce this, and I am going to close this soon if no progress is made. You can make your FLV available for me to test:
https://www.shotcut.org/notes/support-upload/

**Comment by drocks13** [comment] 2016-06-02 08:54
Uploaded- it was created with Open Broadcast Systems. Its not too much of an issues as I can just rewarp the file into .mp4 but thought others might have an issue.

**Comment by ddennedy** [comment] 2016-06-15 15:30
Unable to reproduce and expired.

**Closed by ddennedy** 2016-06-15 15:30 UTC
Labels: crash, pending
