### ISSUE TITLE
Version 16.08 crashing on windows

### ISSUE THREAD

**Issue by klevstul** [mltframework/shotcut#288] opened 2016-08-10 14:40 UTC
# short description
shotcut is crashing very frequently. it is almost impossible to use the editor. the problem started after some images were imported to the video project, and size and position filters were added to the images, next to some transitions in between the cut. unsure if this there is a relation in between this and the crashes though.

note: i have used an earlier version of shotcut, without experiencing similar problems.

# details

## os
windows 7 ultimate - 64 bit

## shotcut version++
```
[Info   ] <Application::Application(int&, char**)> Starting Shotcut version 16.08.04 
[Info   ] <Application::Application(int&, char**)> Windows version 144 
[Info   ] <Application::Application(int&, char**)> number of logical cores = 8 
[Info   ] <Application::Application(int&, char**)> locale = QLocale(English, Default, Australia) 
[Info   ] <Application::Application(int&, char**)> install dir = "C:/Program Files/Shotcut" 
[Debug  ] <ShotcutSettings::singleton> language "en_AU" 
[Debug  ] <ShotcutSettings::singleton> deinterlacer "onefield" 
[Debug  ] <ShotcutSettings::singleton> external monitor "" 
[Debug  ] <ShotcutSettings::singleton> GPU processing false 
[Debug  ] <ShotcutSettings::singleton> interpolation "nearest" 
[Debug  ] <ShotcutSettings::singleton> video mode "" 
[Debug  ] <ShotcutSettings::singleton> realtime true 
```

## error log
```
[Debug  ] <MainWindow::open> "C:/Users/klevstul/AppData/Local/Meltytech/Shotcut/__untitled__.mlt" 
[Debug  ] <MltXmlChecker::MltXmlChecker()> decimal point '.' 
[Debug  ] <MltXmlChecker::check> begin 
[Debug  ] <MltXmlChecker::check> end 
[Debug  ] <AudioLoudnessScopeWidget::resetQview> begin 
[Debug  ] <Mlt::GLWidget::initializeGL> begin 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL vendor "NVIDIA Corporation" 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL renderer "GeForce GTX 780 Ti/PCIe/SSE2" 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL threaded? true 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL ES? false 
[Debug  ] <Mlt::GLWidget::initializeGL> end 
[Debug  ] <LeapNetworkListener::onDisconnected> Disconnected from Leap Motion 
[Debug  ] <LeapNetworkListener::onError> Leap Motion WebSocket error: "Connection refused" 
[Debug  ] <Mlt::GLWidget::~GLWidget> begin 
[Debug  ] <Application::~Application> exiting
```

![k003823](https://cloud.githubusercontent.com/assets/216850/17557782/cf766bb2-5f18-11e6-99ed-207563b7054f.jpg)
[shotcut-log.txt](https://github.com/mltframework/shotcut/files/411355/shotcut-log.txt)

**Comment by ldennedy** [comment] 2016-08-11 04:21
The Leap Motion message is normal for all users apparently. It just means that the Leap Motion device isn't connected and won't be used. It's not the cause of the issue, so the title has been changed to specify crashing on this version of Shotcut, as you've said this issue doesn't happen on older versions.

In this version there is a change in multi-track compositing that could be a source of problems. Are you using more than one video track?

I will try and reproduce it and get back to you.

**Comment by ldennedy** [comment] 2016-08-11 06:05
Okay, I've reproduced a crash like you described on OSX and it appears only to happen on the newest version of Shotcut. The issue seems to come from multi-track compositing like I thought.

What I did to reproduce this is create a track with 3 images that each have a size and position filter change on them, and include a transition between each of them. Then on a new composite track above that, I added a video. The crash occurred when the playhead was over any point during the video where the images were visible, excluding the very beginning.

Thank you for notifying us, we will begin working on a fix for this.

**Comment by klevstul** [comment] 2016-08-11 08:03
great that managed to reproduce this crash. and yes, i can confirm that i was using multi-track compositing. good luck fixing this bug. and keep up the brilliant work with shotcut.

**Comment by ddennedy** [comment] 2016-08-12 04:21
Tomorrow, I will give you a URL for the next nightly build to try it. I am quite confident about the fix.

**Comment by klevstul** [comment] 2016-08-12 09:05
that is fast. i will test it out in a couple of days (going away tonight), and report back to you. thank you!

**Comment by ddennedy** [comment] 2016-08-12 15:15
http://builds.us.meltytech.s3.amazonaws.com/shotcut/shotcut-win64-160812.exe

**Comment by ddennedy** [comment] 2016-08-13 03:50
I made a new release 16.08.12 with this fix.

**Closed by ddennedy** 2016-08-13 03:50 UTC
Labels: crash, reproduced by dev, resolved

**Comment by klevstul** [comment] 2016-08-14 22:04
thanks a lot for a very quick fix. tried opening one of the cuts that used to crash. seemed to work very nicely now.

keep up the great work with shotcut!
