### ISSUE TITLE
Can't open file contain asian letter.

### ISSUE THREAD

**Issue by anovsiradj** [mltframework/shotcut#315] opened 2016-09-29 06:02 UTC
for example a file with name: 
```
월드컵.mp4
```

Shotcut will show an error report:
```
Failed to open D:/path/to/video/월드컵.mp4
```

But, when I rename file with alphabet letter, it work fine.

OS: **Windows 8.1**
Shotcut: **16.09.01**

Thank you!

*[sorry for my bad english]*

**Comment by ddennedy** [comment] 2016-09-29 06:20
Duplicate of #278

**Closed by ddennedy** 2016-09-29 06:20 UTC
Labels: duplicate
